{10}{}{Hero Male}
{20}{}{Hero Female}
{30}{}{Villager}
{40}{}{Villager}
{50}{}{Radscorpion}
{51}{}{A small mutated scorpion.}
{60}{}{Radscorpion}
{61}{}{A mutated scorpion.}
{70}{}{Small Deathclaw}
{71}{}{A young Deathclaw.}
{80}{}{Alpha Male Deathclaw}
{81}{}{The most dangerous predator of the wastes.}
{90}{}{Dog}
{91}{}{A canine, probably of a mixed breed.}
{100}{}{Brahmin}
{101}{}{A two headed, mutant cow.}
{110}{}{Giant Rat}
{111}{}{A typical large rat.}
{120}{}{Mantis}
{121}{}{A mutated Mantis.}
{130}{}{Elder}
{140}{}{Hakunin}
{150}{}{Mynoc}
{160}{}{Spore Plant}
{161}{}{A carnivorous plant.}
{170}{}{Cute Slave}
{180}{}{Handsome Slave}
{190}{}{Healthy Slave}
{200}{}{Healthy Slave}
{210}{}{Strong Slave}
{220}{}{Strong Slave}
{230}{}{Combat Slave}
{240}{}{Combat Slave}
{250}{}{Clever Slave}
{260}{}{Clever Slave}
{270}{}{Generic Slave}
{280}{}{Generic Slave}
{290}{}{Anna}
{300}{}{Tough Thug}
{310}{}{Tough Thug}
{320}{}{Melee Thug}
{330}{}{Melee Thug}
{340}{}{Agile Thug}
{350}{}{Agile Thug}
{360}{}{Gun Thug}
{370}{}{Gun Thug}
{380}{}{Big Gun Thug}
{390}{}{Big Gun Thug}
{400}{}{Tough Guard}
{410}{}{Tough Guard}
{420}{}{Melee Guard}
{430}{}{Melee Guard}
{440}{}{Agile Guard}
{450}{}{Agile Guard}
{460}{}{Gun Guard}
{470}{}{Gun Guard}
{480}{}{Big Gun Guard}
{490}{}{Big Gun Guard}
{500}{}{Orphan (Male)}
{510}{}{Orphan (Female)}
{520}{}{Child (Male)}
{530}{}{Child (Female)}
{540}{}{Loser}
{550}{}{Loser}
{560}{}{Bad Merchant}
{570}{}{Bad Merchant}
{580}{}{Average Merchant}
{590}{}{Average Merchant}
{600}{}{Master Trader}
{610}{}{Master Trader}
{620}{}{Vic}
{630}{}{Person}
{640}{}{Person}
{650}{}{Person}
{660}{}{Person}
{670}{}{Person}
{680}{}{Person}
{690}{}{Guard}
{700}{}{Guard}
{710}{}{Guard}
{720}{}{Guard}
{730}{}{Repair Bot}
{740}{}{Repair Bot Mark II}
{750}{}{Robobrain}
{760}{}{Floating Eye Bot}
{770}{}{Sentry Bot}
{780}{}{Sentry Bot Mark II}
{790}{}{Robobrain}
{800}{}{Silver Gecko}
{810}{}{Tough Lil Gecko}
{820}{}{Wild Dog}
{821}{}{A mixed breed feral dog.}
{830}{}{Golden Gecko}
{840}{}{Deathclaw}
{850}{}{Deathclaw Spawn}
{860}{}{Tough Golden Gecko}
{870}{}{Lynette}
{880}{}{Doc Morbid}
{890}{}{John Cassidy}
{900}{}{Gregory}
{910}{}{Citizen}
{920}{}{Citizen}
{930}{}{Up Class Citizen}
{940}{}{Up Class Citizen}
{950}{}{Trapper}
{960}{}{Trapper}
{970}{}{Sulik}
{980}{}{Maida Buckner}
{990}{}{Torr}
{1000}{}{Lumpy}
{1010}{}{Reactor Glowing One}
{1020}{}{Reactor Ghoul}
{1030}{}{Reactor Guard}
{1040}{}{Zomak}
{1050}{}{Skeeter}
{1060}{}{The Brain}
{1070}{}{Lenny}
{1080}{}{Wooz}
{1090}{}{Harold}
{1100}{}{Molerat}
{1110}{}{Molerat}
{1120}{}{Pigrat}
{1130}{}{Tough Pig Rat}
{1140}{}{Weak Brahmin}
{1141}{}{A two-headed, mutant cow.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Mutated Rat}
{1161}{}{A tough mutant rat.}
{1170}{}{Mutated Molerat}
{1171}{}{A tough mutant molerat.}
{1180}{}{Mutated Pig Rat}
{1181}{}{A tough mutant pig rat.}
{1190}{}{Super Mutant}
{1200}{}{Mutant}
{1210}{}{Super Mutant}
{1220}{}{Hero Andro (don't use)}
{1230}{}{Hero Andro (don't use)}
{1240}{}{Hero Male (don't use)}
{1250}{}{Hero Female (don't use)}
{1260}{}{Hero Male (don't use)}
{1270}{}{Hero Female (don't use)}
{1280}{}{Hero Male (don't use)}
{1290}{}{Hero Female (don't use)}
{1300}{}{Hero Male (don't use)}
{1310}{}{Hero Female (don't use)}
{1320}{}{Hero Male (don't use)}
{1330}{}{Hero Female (don't use)}
{1340}{}{Vault City Guard}
{1350}{}{Vault City Guard}
{1360}{}{Cyberdog}
{1370}{}{NCR Guard}
{1380}{}{NCR Guard}
{1390}{}{NCR Melee Guard}
{1400}{}{Slaver Guard}
{1410}{}{Slaver Overseer}
{1420}{}{Grand Master Trader}
{1430}{}{Grand Master Trader}
{1440}{}{Tandi}
{1450}{}{Merc}
{1460}{}{Ratch}
{1470}{}{Skeeter}
{1480}{}{Mikey}
{1490}{}{NCR Bartender}
{1500}{}{Shop Owner}
{1510}{}{Gruthar}
{1520}{}{Goris}
{1530}{}{Molerat Fighter}
{1540}{}{Molerat Fighter}
{1550}{}{Molerat Fighter}
{1560}{}{Molerat Fighter}
{1570}{}{Molerat Fighter}
{1580}{}{Molerat Fighter}
{1590}{}{Generic Ghoul}
{1600}{}{Myron}
{1610}{}{Marcus}
{1620}{}{Doc Jones}
{1630}{}{Davin}
{1640}{}{Miria}
{1650}{}{Laddie}
{1660}{}{Rondo}
{1670}{}{Ranch Hand}
{1680}{}{Ranch Hand}
{1690}{}{Ranch Hand}
{1700}{}{Bouncer}
{1710}{}{Bouncer}
{1720}{}{Weak Mr. Handy}
{1730}{}{Generic Glowing One}
{1740}{}{Dar}
{1750}{}{Dalia}
{1760}{}{Gordon}
{1770}{}{test (don't use)}
{1780}{}{Reactor Ghoul}
{1790}{}{Generic Ghoul}
{1800}{}{Matt}
{1810}{}{B. Hunter Lead}
{1820}{}{Bounty Hunter}
{1830}{}{B. Hunter Lead}
{1840}{}{Bounty Hunter}
{1850}{}{Bounty Hunter}
{1860}{}{B. Hunter Lead}
{1870}{}{Bounty Hunter}
{1880}{}{Bounty Hunter}
{1890}{}{B. Hunter Lead}
{1900}{}{Bounty Hunter}
{1910}{}{Bess}
{1911}{}{A two headed, mutant cow.}
{1920}{}{Balthas}
{1930}{}{Grisham}
{1940}{}{Phil}
{1950}{}{Chicken}
{1960}{}{Karl}
{1970}{}{Jonny}
{1980}{}{Jo}
{1990}{}{Zeke}
{2000}{}{Butcher}
{2010}{}{Petey}
{2020}{}{Primitive Hunter}
{2030}{}{Primitive Hunter}
{2040}{}{Cannibal}
{2050}{}{Cannibal}
{2060}{}{Holy Man}
{2070}{}{Holy Woman}
{2080}{}{Nomad- Low}
{2090}{}{Nomad- Med}
{2100}{}{Nomad- Low}
{2110}{}{Nomad- Med}
{2120}{}{Bandit}
{2130}{}{Bandit}
{2140}{}{Farmer}
{2150}{}{Farmer}
{2160}{}{Mantis}
{2170}{}{Slaver}
{2180}{}{Slaver}
{2190}{}{Wild Brahmin}
{2200}{}{Homesteader}
{2210}{}{Homesteader}
{2220}{}{Vault City Patrol}
{2230}{}{Vault City Patrol}
{2240}{}{Strong Slaver}
{2250}{}{Strong Slaver}
{2260}{}{Crazies}
{2270}{}{Scavengers}
{2280}{}{Glow Crazies}
{2290}{}{Glow Scavengers}
{2300}{}{Fisherman}
{2310}{}{Fisherwoman}
{2320}{}{Wilder}
{2330}{}{Wilder}
{2340}{}{Bootlegger}
{2350}{}{Bootlegger}
{2360}{}{Prospector}
{2370}{}{Prospector}
{2380}{}{Raider}
{2390}{}{Raider}
{2400}{}{Fire Gecko}
{2410}{}{Tough Fire Gecko}
{2420}{}{Wanamingo}
{2430}{}{Tough Wanamingo}
{2440}{}{Deathclaw}
{2450}{}{Tough Deathclaw}
{2460}{}{Floater}
{2470}{}{Nasty Floater}
{2480}{}{Centaur}
{2490}{}{Mean Centaur}
{2500}{}{Enclave Patrol}
{2510}{}{Enclave Patrol}
{2520}{}{Press Gang}
{2530}{}{Press Gang}
{2540}{}{Mercenary}
{2550}{}{Mercenary}
{2560}{}{Nightkin}
{2570}{}{Tough Nightkin}
{2580}{}{Tough Ghoul}
{2590}{}{Mobster}
{2600}{}{Yakuza}
{2610}{}{NCR Ranger}
{2620}{}{NCR Ranger}
{2630}{}{Maurader}
{2640}{}{Maurader}
{2650}{}{Pretty Boy Lloyd}
{2660}{}{Vorpal Rat}
{2670}{}{Vault 13 Man}
{2680}{}{Vault 13 Woman}
{2690}{}{Bridge Guardian}
{2700}{}{Mysterious Stranger}
{2710}{}{Mysterious Stranger}
{2720}{}{Hakeswill}
{2730}{}{Big Jesus Mordino}
{2740}{}{Dumar}
{2741}{}{Dumar, the brahmin trader.}
{2750}{}{Mother Deathclaw}
{2760}{}{The Dragon}
{2770}{}{Lo Pan}
{2780}{}{Hubologist}
{2790}{}{Hubologist}
{2800}{}{Mysterious Stranger}
{2810}{}{Mysterious Stranger}
{2820}{}{Mysterious Stranger}
{2830}{}{Mysterious Stranger}
{2840}{}{Mysterious Stranger}
{2850}{}{Mysterious Stranger}
{2860}{}{Mysterious Stranger}
{2870}{}{Mysterious Stranger}
{2880}{}{Pres. Bodyguard}
{2890}{}{Deathclaw Egg}
{2900}{}{Metzger}
{2910}{}{Enclave Guard}
{2920}{}{Enclave Guard}
{2930}{}{President}
{2940}{}{Vice President}
{2950}{}{Technicion}
{2960}{}{Badger}
{2970}{}{Dr. Fung}
{2980}{}{Kid}
{2990}{}{Kid}
{3000}{}{Gun Merchant}
{3010}{}{Shi Lab Tech}
{3020}{}{Shi Guard}
{3030}{}{Shi Peasant}
{3040}{}{Shi Peasant}
{3050}{}{Lo Pan Peasant}
{3060}{}{Lo Pan Peasant}
{3070}{}{Dock Worker}
{3080}{}{Shi Merchant}
{3090}{}{Keeng Ra'at}
{3100}{}{Sulik - Stage 1}
{3110}{}{Sulik - Stage 2}
{3120}{}{Sulik - Stage 3}
{3130}{}{Sulik - Stage 4}
{3140}{}{Sulik - Stage 5}
{3150}{}{Sulik - Stage 6}
{3160}{}{Lenny - Stage 1}
{3170}{}{Lenny - Stage 2}
{3180}{}{Lenny - Stage 3}
{3190}{}{Goris - Stage 1}
{3200}{}{Goris - Stage 2}
{3210}{}{Goris - Stage 3}
{3220}{}{Goris - Stage 4}
{3230}{}{Goris - Stage 5}
{3240}{}{Goris - Stage 6}
{3250}{}{Myron - Stage 1}
{3260}{}{Myron - Stage 2}
{3270}{}{Myron - Stage 3}
{3280}{}{Myron - Stage 4}
{3290}{}{Marcus - Stage 1}
{3300}{}{Marcus - Stage 2}
{3310}{}{Marcus - Stage 3}
{3320}{}{Marcus - Stage 4}
{3330}{}{Marcus - Stage 5}
{3340}{}{Cyberdog - Stage 1}
{3350}{}{Cyberdog - Stage 2}
{3360}{}{Cyberdog - Stage 3}
{3370}{}{Cyberdog - Stage 4}
{3380}{}{Cassidy - Stage 1}
{3390}{}{Cassidy - Stage 2}
{3400}{}{Cassidy - Stage 3}
{3410}{}{Cassidy - Stage 4}
{3420}{}{Dogmeat}
{3430}{}{Dogmeat - Stage 1}
{3440}{}{Dogmeat - Stage 2}
{3450}{}{Dogmeat - Stage 3}
{3460}{}{Dogmeat - Stage 4}
{3470}{}{Dogmeat - Stage 5}
{3480}{}{Dogmeat - Stage 6}
{3490}{}{Robobrain - Stage 1}
{3500}{}{Robobrain - Stage 2}
{3510}{}{Robobrain - Stage 3}
{3520}{}{Robobrain - Stage 4}
{3530}{}{Robobrain - Stage 5}
{3540}{}{Queen Wanamingo}
{3550}{}{Black Radscorpion}
{3560}{}{Black Radscorpion}
{3570}{}{Spud}
{3580}{}{Mercenary Captain}
{3590}{}{Mercenary}
{3600}{}{Mercenary}
{3610}{}{Shadow-Who-Walks}
{3620}{}{Punk}
{3630}{}{Punk}
{3640}{}{Marc}
{3650}{}{Dave H.}
{3660}{}{Capt. A. Ron Meyers}
{3670}{}{Chip}
{3680}{}{AHS-9}
{3690}{}{Hubologist Guard}
{3700}{}{Hubologist Guard}
{3710}{}{Juan}
{3720}{}{Vikki}
{3730}{}{Vic}
{3740}{}{Vic}
{3750}{}{Vic}
{3760}{}{Vic}
{3770}{}{Vic}
{3780}{}{Vic}
{3790}{}{RoboBrain - Chimp}
{3800}{}{Robobrain - Abnormal}
{3810}{}{Robobrain - Human}
{3820}{}{Giant Ant}
{3830}{}{Tough Giant Ant}
{3840}{}{Pariah Dog}
{3850}{}{Zurak}
{3860}{}{Imbot}
{3870}{}{Jimmy}
{3880}{}{Wejungh}
{3890}{}{Herb}
{3900}{}{Loopal}
{3910}{}{Jobe}
{3920}{}{Smitty}
{3930}{}{Rube}
{3940}{}{Master Krall}
{3950}{}{Ziggy}
{3960}{}{Master Khung}
{3970}{}{John Bishop}
{3980}{}{Angela Bishop}
{3990}{}{Mrs. Bishop}
{4000}{}{Bishop's Guard}
{4010}{}{Bishop's Guard}
{4020}{}{Bishop's Thug}
{4030}{}{Bishop's Thug}
{4040}{}{Angry Brahmin}
{4050}{}{Lil' Jesus}
{4060}{}{Big Jesus}
{4070}{}{Mordino Men}
{4080}{}{Mordino Men}
{4090}{}{Mordino Men}
{4100}{}{Myron's Guard}
{4110}{}{Myron's Guard}
{4120}{}{Mr. Wright}
{4130}{}{Mrs. Wright}
{4140}{}{Chris Wright}
{4150}{}{Keith Wright}
{4160}{}{Wright Son}
{4170}{}{Wright Son}
{4180}{}{Wright Daughter}
{4190}{}{Wright Daughter}
{4200}{}{Mr. Salvatore}
{4210}{}{Mason}
{4220}{}{Salvatore Thug}
{4230}{}{Salvatore Thug}
{4240}{}{Generic Bartender}
{4250}{}{Generic Bartender}
{4260}{}{Generic Bartender}
{4270}{}{Boxer}
{4280}{}{Boxer}
{4290}{}{Boxer}
{4300}{}{Boxer}
{4310}{}{Mike the Masticator}
{4320}{}{Holyfeld}
{4330}{}{McKneely}
{4340}{}{Stuart Little}
{4350}{}{Corsican Brothers}
{4360}{}{Corsican Bitches}
{4370}{}{Father Tully}
{4380}{}{Casino Bouncer}
{4390}{}{Casino Bouncer}
{4400}{}{Casino Girl}
{4410}{}{Drug Dealer}
{4420}{}{Drug Dealer}
{4430}{}{Drug Dealer}
{4440}{}{Drug Dealer}
{4450}{}{McGee}
{4460}{}{Miss Kitty}
{4470}{}{Slut}
{4480}{}{Slut}
{4490}{}{Jagged Jimmy J}
{4500}{}{Renesco}
{4510}{}{Scientist}
{4520}{}{Eldridge}
{4530}{}{Algernon}
{4540}{}{Jules}
{4550}{}{Bureaucrat}
{4560}{}{Bureaucrat}
{4570}{}{Trader}
{4580}{}{Trader}
{4590}{}{Guard}
{4600}{}{Guard}
{4610}{}{Guard}
{4620}{}{Guard}
{4630}{}{Soldier}
{4640}{}{Soldier}
{4650}{}{Soldier}
{4660}{}{Soldier}
{4670}{}{Sgt. Stark}
{4680}{}{"Doc" Andrew}
{4690}{}{Bartender}
{4700}{}{Gun Turret}
{4701}{}{This is an automated gun turret equipped with a Dual Plasma Cannon.}
{4710}{}{Wild Dog}
{4720}{}{Wild Dog}
{4730}{}{Wild Dog}
{4740}{}{Wild Dog}
{4750}{}{Coyote}
{4760}{}{Wild Dog}
{4770}{}{Wanamingo Egg}
{4780}{}{Lo Pan Guard}
{4790}{}{Marjorie}
{4800}{}{Auto-Cannon}
{4810}{}{Special Gecko Critter}
{4820}{}{Grim Reaper}
{4830}{}{Frank Horrigan}
{4831}{}{The President's Body Guard}
{4840}{}{Wolf}
{4850}{}{Rabid Dog}
{4860}{}{Coyote}
{4870}{}{Mutated Radscorpion}
{4880}{}{Small Golden Gecko}
{4890}{}{Rebel}
{4900}{}{Deadly Beetle}
{4910}{}{Engineer}
{4920}{}{Enclave Infantry}
{4930}{}{Engineer}
{4940}{}{Brotherhood Initiate}
{4950}{}{Special Ops Soldier}
{4960}{}{Enclave Soldier}
{4970}{}{Brotherhood Paladin}
{4980}{}{Regulator}
{4990}{}{Bandit}
{5000}{}{Bandit}
{5010}{}{Raider}
{5020}{}{Raider}
{5030}{}{Raider}
{5040}{}{Raider}
{5050}{}{Giant wasp}
{5051}{}{Огромное кровожадное насекомое}
{5060}{}{Гвардеец}
{5061}{}{Боец Гвардии ГУ}
{5070}{}{Giant Bat}
{5080}{}{Arroyo Patrol}
{5090}{}{Arroyo Patrol}
{5100}{}{Arroyo Patrol}
{5110}{}{Fugitive}
{5120}{}{Fugitive}
{5130}{}{Fugitive}
{5140}{}{Fugitive}
{5150}{}{Fugitive}
{5160}{}{Eli}
{5170}{}{Champion}
{5180}{}{Helacyton type  1}
{5181}{}{A strange creature resembling Master's pets.}
{5190}{}{Angry helacyton type  1}
{5191}{}{A strange creature resembling Master's pets.}
{5200}{}{Helacyton type  2}
{5201}{}{A strange creature resembling Master's pets.}
{5210}{}{Angry helacyton type  2}
{5211}{}{A strange creature resembling Master's pets.}
{5220}{}{Helacyton type  3}
{5221}{}{A strange creature resembling Master's pets.}
{5230}{}{Henrietta}
{5231}{}{Skin of this animal looks like one big callus.}
{5240}{}{Android}
{5250}{}{Tim Cain}
{5260}{}{Carlos Jackal}
{5270}{}{Carlos Jackal}
{5280}{}{Behemoth}
{5281}{}{Огромный механический жук на шести лапах, оснащен крупнокалиберным пулеметом.}
{5300}{}{Junktown guard}
{5301}{}{A smart looking guard, who knows how to handle his gun.}
{5310}{}{Junktown guard}
{5311}{}{A smart looking guard, who knows how to handle his gun.}
{5320}{}{Ron Winkley}
{5321}{}{Ron Winkley, local jail warden.}
{5330}{}{Guard}
{5331}{}{Guard of The Slayer.}
{5340}{}{The Slayer}
{5341}{}{The Slayer.}
{5350}{}{Junktown guard}
{5351}{}{A smart looking guard, who knows how to handle his gun.}
{5360}{}{Hub policeman}
{5361}{}{Hub policeman carefully watching the area.}
{5370}{}{Hub policeman}
{5371}{}{Hub policeman carefully watching the area.}
{5380}{}{Nightkin}
{5381}{}{Strong and agressive super mutant.}
{5390}{}{Nightkin}
{5391}{}{Strong super mutant. He seems to have some device to make him hardly visible.}
{5400}{}{Mutant}
{5401}{}{Super mutant. He looks very aggressive.}
{5410}{}{Claim Jumper}
{5420}{}{Claim Jumper}
{5430}{}{Claim Jumper}
{5440}{}{Claim Jumper}
{5450}{}{Claim Jumper}
{5460}{}{Chuck Lee}
{5461}{}{Chuck Lee, the caravan leader.}
{5470}{}{Manequin}
{5480}{}{Manequin}
{5490}{}{Manequin}
{5500}{}{Manequin}
{5510}{}{Manequin}
{5520}{}{Manequin}
{5530}{}{Manequin}
{5540}{}{Manequin}
{5550}{}{Manequin}
{5560}{}{Manequin}
{5570}{}{Manequin}
{5580}{}{Manequin}
{5590}{}{Manequin}
{5600}{}{Manequin}
{5610}{}{Manequin}
{5620}{}{Manequin}
{5630}{}{Manequin}
{5640}{}{Manequin}
{5650}{}{Manequin}
{5660}{}{Manequin}
{5670}{}{Manequin}
{5680}{}{Manequin}
{5690}{}{Manequin}
{5700}{}{Manequin}
{5710}{}{Manequin}
{5720}{}{Manequin}
{5730}{}{Manequin}
{5740}{}{Manequin}
{5750}{}{Manequin}
{5760}{}{Manequin}
{5770}{}{Manequin}
{5780}{}{Manequin}
{5790}{}{Manequin}
{5800}{}{Manequin}
{5810}{}{Manequin}
{5820}{}{Manequin}
{5830}{}{Manequin}
{5840}{}{Manequin}
{5850}{}{Manequin}
{5860}{}{Manequin}
{5870}{}{Manequin}
{5880}{}{Manequin}
{5890}{}{Manequin}
{5900}{}{Manequin}
{5910}{}{Manequin}
{5920}{}{Manequin}
{5930}{}{Manequin}
{5940}{}{Manequin}
{5950}{}{Manequin}
{5960}{}{Manequin}
{5970}{}{Manequin}
{5980}{}{Manequin}
{5990}{}{Manequin}
{6000}{}{Manequin}
{6010}{}{Tough Junktown guard}
{6011}{}{A tough looking guard, who is carefully paying attention to everything what is going on around him.}
{6030}{}{Tough Junktown guard}
{6031}{}{A tough looking guard, who is carefully paying attention to everything what is going on around him.}
{6040}{}{Tough Junktown guard}
{6041}{}{A tough looking guard, who is carefully paying attention to everything what is going on around him.}
{6050}{}{Trader KLAMATH}
{6060}{}{Trader DEN}
{6070}{}{Trader REDDING}
{6080}{}{Trader MODOC}
{6090}{}{Trader GECKO}
{6100}{}{Trader VC OUT}
{6110}{}{Trader VC IN}
{6120}{}{Trader BROKEN HILLS}
{6130}{}{Trader NEW RENO}
{6140}{}{Trader SAN FRANCISCO}
{6150}{}{Trader NCR OUT}
{6160}{}{Trader NCR IN}
{6170}{}{Trader HUB}
{6180}{}{Trader BONEYARD}
{6190}{}{Doctor VC IN}
{6200}{}{Doctor VC OUT}
{6210}{}{Doctor NCR}
{6220}{}{Doctor HUB}
{6230}{}{Doctor BONEYARD}
{6240}{}{Doctor SANFRANCISCO}
{6250}{}{Doctor NEW RENO}
{6260}{}{Doctor BROKEN HILLS}
{6270}{}{Doctor REDDING}
{6280}{}{BAR SF}
{6290}{}{BAR BH}
{6300}{}{BAR BHWIFE}
{6310}{}{BAR SALVNR}
{6320}{}{BAR CASINONR}
{6330}{}{BAR GECKO}
{6340}{}{BAR VC}
{6350}{}{BAR MODOC}
{6360}{}{BAR WIFEKLAMATH}
{6370}{}{BAR DUDEKLAMATH}
{6380}{}{BAR CASINODEN}
{6390}{}{BAR DEN}
{6400}{}{BAR MOMDEN}
{6410}{}{BAR HUB}
{6420}{}{BAR JT}
{6430}{}{BAR MALAMUTREDDING}
{6440}{}{BAR COFFINREDDING}
{6450}{}{BAR NCROUT}
{6460}{}{BAR NCRIN}
{6470}{}{SFTANK GUNS}
{6480}{}{SFTANK ARMOR}
{6490}{}{BALDCHINA}
{6500}{}{BH CARAVANDUDE}
{6510}{}{BH HUSBAND}
{6520}{}{NEWR ARMS}
{6530}{}{GECKO SKEET}
{6540}{}{GECKO SHERIFF}
{6550}{}{VC A ARMOR}
{6560}{}{VC B WEAPON}
{6570}{}{MODOC TANNER}
{6580}{}{MODOC WILLY}
{6590}{}{DEN SECOND}
{6600}{}{HUB JACOB}
{6610}{}{HUB GUNS}
{6620}{}{BONE GUNRUNNERS}
{6630}{}{Mother Deathclaw}
{6631}{}{Holy fuck. Better run!}
{6640}{}{Deathclaw}
{7000}{}{Claim Jumper}
{7010}{}{Bandit}
{7020}{}{Bandit}
{7030}{}{Bandit}
{7040}{}{Bandit}
{7050}{}{Bandit}
{7060}{}{Bandit}
{7070}{}{Robber}
{7080}{}{Robber}
{7090}{}{Robber}
{7100}{}{Robber}
{7110}{}{Robber}
{7120}{}{Robber}
{7130}{}{Bootlegger}
{7140}{}{Bootlegger}
{7150}{}{Bootlegger}
{7160}{}{Bootlegger}
{7170}{}{Thug}
{7180}{}{Thug}
{7190}{}{Thug}
{7200}{}{Thug}
{7210}{}{Thug}
{7220}{}{Thug}
{7230}{}{Moonshiner}
{7240}{}{Moonshiner}
{7250}{}{Moonshiner}
{7260}{}{Moonshiner}
{7270}{}{Moonshiner}
{7280}{}{Moonshiner}
{7290}{}{Marauder}
{7300}{}{Marauder}
{7310}{}{Marauder}
{7320}{}{Marauder}
{7330}{}{Marauder}
{7340}{}{Marauder}
{7350}{}{Raider}
{7360}{}{Raider}
{7370}{}{Raider}
{7380}{}{Raider}
{7390}{}{Raider}
{7400}{}{Raider}
{7410}{}{Ghoul}
{7420}{}{Ghoul}
{7430}{}{Ghoul}
{7440}{}{Ghoul}
{7450}{}{Ghoul}
{7460}{}{Punker}
{7470}{}{Punker}
{7480}{}{Punker}
{7490}{}{Punker}
{7500}{}{Punker}
{7510}{}{Ripper}
{7520}{}{Ripper}
{7530}{}{Ripper}
{7540}{}{Ripper}
{7550}{}{Ripper}
{7560}{}{Raider}
{7570}{}{Raider}
{7580}{}{Raider}
{7590}{}{Raider}
{7600}{}{Raider}
{7610}{}{Gunman}
{7620}{}{Crazy Slut}
{7630}{}{Badass}
{7640}{}{Goon}
{7650}{}{Gangsta}
{7660}{}{Highwayman}
{7670}{}{Highwayman}
{7680}{}{Highwayman}
{7690}{}{Highwayman}
{7700}{}{Highwayman}
{7710}{}{Angry Bitch}
{7720}{}{Lunatic}
{7730}{}{Mad Man}
{7740}{}{Ugly Bag}
{7750}{}{Scum}
{7760}{}{Mercenary}
{7770}{}{Mercenary}
{7780}{}{Mercenary}
{7790}{}{Mercenary}
{7800}{}{Mercenary}
{7810}{}{Ghoul}
{7820}{}{Regulator}
{7830}{}{Regulator}
{7840}{}{Regulator}
{7850}{}{Regulator}
{7860}{}{Khan Raider}
{7870}{}{Khan Raider}
{7880}{}{Khan Raider}
{7890}{}{Khan Raider}
{7900}{}{Khan Raider}
{7910}{}{Rogue}
{7920}{}{Rogue}
{7930}{}{Rogue}
{7940}{}{Rogue}
{7950}{}{Rogue}
{7960}{}{Enclave Recruit}
{7970}{}{Enclave Trooper}
{7980}{}{Enclave Trooper}
{7990}{}{Enclave Veteran Trooper}
{8000}{}{Enclave Veteran Trooper}
{8010}{}{Mutant}
{8020}{}{Super Mutant}
{8030}{}{Super Mutant}
{8040}{}{Nightkin}
{8050}{}{Nightkin}
{8060}{}{Ghoul}
{8070}{}{Ghoul}
{8080}{}{Ghoul}
{8090}{}{Ghoul}
{8100}{}{Ghoul}
{8110}{}{Ghoul}
{8120}{}{Ghoul}
{8130}{}{Ghoul}
{8140}{}{Ghoul}
{8150}{}{Ghoul}
{8160}{}{Ghoul}
{8170}{}{Enclave Recruit}
{8180}{}{Enclave Trooper}
{8190}{}{Enclave Trooper}
{8200}{}{Enclave Veteran Trooper}
{8210}{}{Brotherhood Initiate}
{8220}{}{Brotherhood Knight}
{8230}{}{Brotherhood Knight}
{8240}{}{Brotherhood Paladin}
{8250}{}{Abomination}
{8260}{}{Monstrosity}
{8270}{}{Cave Rat}
{8280}{}{Mutated Pigrat}
{8290}{}{Mutated Molerat}
{8300}{}{Gore}
{8301}{}{Angry, smartass.. conversation is futile.}
{8310}{}{Robobrain}
{8320}{}{Eye Bot}
{8330}{}{Ghoul Guard}
{8340}{}{Zed}
{8350}{}{Khan Raider}
{8360}{}{Khan Raider}
{8370}{}{Khan Raider}
{8380}{}{Khan Raider}
{8390}{}{Khan Raider}
{8400}{}{Junktown Scout}
{8410}{}{Junktown Scout}
{8420}{}{Junktown Scout}
{8430}{}{Junktown Scout}
{8440}{}{Junktown Scout}
{8450}{}{Trader's Guard}
{8460}{}{Trader's Guard}
{8470}{}{Trader's Guard}
{8480}{}{Trader's Guard}
{8490}{}{Trader}
{8500}{}{Bandit}
{8510}{}{Bandit}
{8520}{}{Bandit}
{8530}{}{Bandit}
{8540}{}{Bandit}
{8550}{}{Bandit}
{8560}{}{Robber}
{8570}{}{Robber}
{8580}{}{Robber}
{8590}{}{Robber}
{8600}{}{Robber}
{8610}{}{Robber}
{8620}{}{Caravan Leader}
{8630}{}{Caravan Guard}
{8640}{}{Caravan Guard}
{8650}{}{Caravan Guard}
{8660}{}{Caravan Guard}
{8670}{}{Caravan Guard}
{8680}{}{Caravan Guard}
{8690}{}{Caravan Guard}
{8700}{}{Caravan Guard}
{8710}{}{Brotherhood Initiate}
{8720}{}{Brotherhood Knight}
{8730}{}{Brotherhood Knight}
{8740}{}{Brotherhood Paladin}
{8750}{}{Brotherhood Paladin}
{8760}{}{Hub Guard}
{8770}{}{Hub Guard}
{8780}{}{Hub Guard}
{8790}{}{Hub Guard}
{8800}{}{Hub Guard}
{8810}{}{Vault City Guard}
{8820}{}{Vault City Guard}
{8830}{}{Vault City Guard}
{8840}{}{Vault City Guard}
{8850}{}{Vault City Guard}
{8860}{}{Ghoul}
{8870}{}{Ghoul}
{8880}{}{Ghoul}
{8890}{}{Ghoul}
{8900}{}{Ghoul}
{8910}{}{Blade}
{8920}{}{Blade}
{8930}{}{Blade}
{8940}{}{Blade}
{8950}{}{Blade}
{8960}{}{Unity Patrol}
{8970}{}{Unity Patrol}
{8980}{}{Unity Patrol}
{8990}{}{NCR Ranger}
{9000}{}{NCR Ranger}
{9010}{}{NCR Ranger}
{9020}{}{NCR Trooper}
{9030}{}{NCR Recruit}
{9040}{}{Caravan Leader}
{9050}{}{Caravan Guard}
{9060}{}{Caravan Guard}
{9070}{}{Caravan Guard}
{9080}{}{Caravan Guard}
{9090}{}{Caravan Guard}
{9100}{}{Caravan Guard}
{9110}{}{Caravan Guard}
{9120}{}{Caravan Guard}
{9130}{}{Farmer}
{9140}{}{Farmer}
{9150}{}{Farmer}
{9160}{}{Farmer}
{9170}{}{Child}
{9180}{}{Peasant}
{9190}{}{Peasant}
{9200}{}{Peasant}
{9210}{}{Peasant}
{9220}{}{Child}
{9230}{}{Peasant}
{9240}{}{Scavenger}
{9250}{}{Scavenger}
{9260}{}{Scavenger}
{9270}{}{Scavenger}
{9280}{}{Scavenger}
{9290}{}{Hobo}
{9300}{}{Hobo}
{9310}{}{Hobo}
{9320}{}{Hobo}
{9330}{}{Trapper}
{9340}{}{Trapper}
{9350}{}{Trapper}
{9360}{}{Hunter}
{9370}{}{Hunter}
{9380}{}{Hunter}
{9390}{}{Prospector}
{9400}{}{Prospector}
{9410}{}{Prospector}
{9420}{}{Homesteader}
{9430}{}{Homesteader}
{9440}{}{Homesteader}
{9450}{}{Homesteader}
{9460}{}{Hubulogist}
{9470}{}{Hubologist}
{9480}{}{Hubologist}
{9490}{}{Hubologist}
{9500}{}{Hubologist}
{9510}{}{Chupacabra}
{9511}{}{Better run!}
{9520}{}{Aberration}
{9530}{}{Patrol leader}
{9540}{}{Vayne}
{9550}{}{Junktown Scout}
{9560}{}{Junktown Scout}
{9570}{}{Junktown Scout}
{9580}{}{Junktown Scout}
{9590}{}{Junktown Scout}
{9600}{}{Nightkin}
{9610}{}{Suspicious Robed Man}
{9620}{}{Bishop's Thug}
{9630}{}{Bishop's Thug}
{9640}{}{Bishop's Thug}
{9650}{}{Bishop's Thug}
{9660}{}{Wright Son}
{9670}{}{Wright Son}
{9680}{}{Wright Son}
{9690}{}{Wright Son}
{9700}{}{Commander}
{9710}{}{26}
{9720}{}{31}
{9730}{}{40}
{9740}{}{41}
{9750}{}{43}
{9760}{}{44}
{9770}{}{45}
{9780}{}{48}
{9790}{}{56}
{9800}{}{57}
{9810}{}{62}
{9820}{}{64}
{9830}{}{72}
{9840}{}{77}
{9850}{}{78}
{9860}{}{82}
{9870}{}{87}
{9880}{}{88}
{9890}{}{Chemist}
{9900}{}{91}
{9910}{}{92}
{9920}{}{93}
{9930}{}{95}
{9940}{}{96}
{9950}{}{98}
{9960}{}{105}
{9970}{}{110}
{9980}{}{135}
{9990}{}{136}
{10000}{}{137}
{10010}{}{139}
{10020}{}{140}
{10030}{}{33}
{10040}{}{34}
{10050}{}{35}
{10060}{}{36}
{10070}{}{37}
{10080}{}{61}
{10090}{}{73}
{10100}{}{94}
{10110}{}{145}
{10120}{}{146}
{10130}{}{148}
{10140}{}{149}
{10150}{}{Furniture Scavenger}
{10160}{}{Toxic Gecko}
{10170}{}{Mature Toxic Gecko}
{10180}{}{Small Radiated Gecko}
{10190}{}{Radiated Gecko}
{10200}{}{Tough Radiated Gecko}
{10210}{}{Nightmare}
{10220}{}{Deathbringer}
{10230}{}{Caravan Leader}
{10240}{}{Vault Dweller}
{10250}{}{Tribal Leader}
{11200}{}{Man}
{11210}{}{Woman}
{14000}{}{Radscorpion Egg}
{14010}{}{Ant Egg}
{14020}{}{Gecko Egg}
{14030}{}{Deathclaw Egg}
{14040}{}{Wanamingo Egg}
{14050}{}{Centaur Egg}
