{1}{}{PID_BPACK_TENT@Сложенная палатка, используется обычно в качестве укрытия в суровых условиях пустоши.@@@PID_BRAHMIN_SKIN 10&PID_FIREWOOD 2@@PID_BPACK_TENT 1@exp 230 script fix_boy@fix_AnyStuff}
{50}{}{PID_ZIP_GUN@Самодельный однозарядный пистолет. Мин. сила: 4.@@@PID_TUBE 1&PID_JUNK 1@@PID_ZIP_GUN 1@exp 35 script fix_boy@fix_AnyStuff}
{51}{}{PID_SPRINGER_RIFLE@Самодельное однозарядное ружье. Мин. сила: 5.@@@PID_JUNK 1&PID_TUBE 1&PID_FIREWOOD 1@@PID_SPRINGER_RIFLE 1@exp 50 script fix_boy@fix_AnyStuff}
{52}{}{PID_10MM_PISTOL@Самозарядный пистолет Кольт 6520 калибра 10 мм. При каждом нажатии на курок оружие автоматически перезаряжается, пока магазин не опустеет. Только одиночные выстрелы. Используются мощные 10-мм патроны. Мин. сила: 3.@@SK_SMALL_GUNS 70@PID_JUNK 1&PID_TUBE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_10MM_PISTOL 1@exp 85 script fix_boy@fix_AnyStuff}
{53}{}{PID_SHOTGUN@Винчестер Видоумейкер - двуствольный дробовик 12 калибра. Короткоствольный, с прикладом из красного дерева. Мин. сила: 4.@@SK_SMALL_GUNS 70@PID_METAL_TRASH 1&PID_TUBE 2&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_SHOTGUN 1@exp 105 script fix_boy@fix_AnyStuff}
{54}{}{PID_SAWED_OFF_SHOTGUN@Кто-то потратил время и отрезал последние несколько сантиметров ствола и ложа этого дробовика. Теперь широкий разброс дроби делает его идеальным для контроля толпы на ближнем расстоянии. Мин. сила: 4.@@SK_SMALL_GUNS 70@PID_SHOTGUN 1@PID_SPECIAL_WB1 1@PID_SAWED_OFF_SHOTGUN 1@script fix_boy@fix_AnyStuff}
{55}{}{PID_44_MAGNUM_REVOLVER@Держа в руке самый мощный револьвер в мире, который может подчистую снести кому-нибудь голову, вам хочется задать себе один вопрос: "Эй, чудила, везет тебе? Везет тебе, а?" Мин. сила: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_44_MAGNUM_REVOLVER 1@exp 135 script fix_boy@fix_Blueprint}
{56}{}{PID_44_MAGNUM_SPEEDLOADER@Револьвер Магнум калибра 0,44 с ускорителем заряжания. Мин. сила: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_44_MAGNUM_REVOLVER 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 60 script fix_boy@fix_Blueprint}
{57}{}{PID_DESERT_EAGLE@Древний Дезерт Игл, модель 0,44 калибра Магнум. Благодаря художественным фильмам конца ХХ века стал самым популярным пистолетом всех времен и народов. Этот конкретный оснащен увеличенным магазином, чтобы можно было дольше играть и веселиться! Мин. сила: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_DESERT_EAGLE 1@exp 135 script fix_boy@fix_Blueprint}
{58}{}{PID_DESERT_EAGLE_EXT_MAG@Древний Дезерт Игл, модель 0,44 калибра Магнум. Благодаря художественным фильмам конца ХХ века стал самым популярным пистолетом всех времен и народов. Этот конкретный оснащен увеличенным магазином, чтобы можно было дольше играть и веселиться! Мин. сила: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_DESERT_EAGLE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 35 script fix_boy@fix_Blueprint}
{59}{}{PID_9MM_MAUSER@Маузер M/96 калибра 9x19 мм Парабеллум. В отличном состоянии. Идеальная точность выстрела. Мин. сила: 3.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_9MM_MAUSER 1@exp 85 script fix_boy@fix_AnyStuff}
{60}{}{PID_10MM_SMG@Пистолет-пулемет H&K MP9 (модель калибра 10 мм). ПП среднего размера с возможностью одиночного выстрела и стрельбы очередями. Мин. сила: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 1&PID_METAL_TRASH 3&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_10MM_SMG 1@exp 180 script fix_boy@fix_Blueprint}
{61}{}{PID_GREASE_GUN@Эти пистолеты-пулеметы были оружием Национальной гвардии до перевооружения. Производство "Гриз Ганов" было простым и недорогим, поэтому их все еще несложно найти. Мин. сила: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 4@PID_SPECIAL_WB1 1@PID_GREASE_GUN 1@exp 235 script fix_boy@fix_Blueprint}
{62}{}{PID_TOMMY_GUN@Пистолет-пулемет Томпсона M1928 - очень грозное оружие. Когда берешь его, появляется желание надеть мягкую фетровую шляпу и размять пальцы. Снабжен большим 50-зарядным барабаном. Мин. сила: 6.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_METAL_TRASH 3&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_TOMMY_GUN 1@exp 185 script fix_boy@fix_Blueprint}
{63}{}{PID_COMBAT_SHOTGUN@Боевой дробовик Винчестер Ситикиллер 12 калибра. Конструкция "буллпап". В отличном состоянии. Поставляется с герметиком "Война в пустыне", повышающим надежность оружия. Мин. сила: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_FIREWOOD 1&PID_METAL_TRASH 4@PID_SPECIAL_WB1 1@PID_COMBAT_SHOTGUN 1@exp 235 script fix_boy@fix_Blueprint}
{64}{}{PID_HUNTING_RIFLE@Полуавтоматическое ружье Кольт Рейнджмастер калибра 0,223. Только одиночные выстрелы. Мин. сила: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_FIREWOOD 1&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_HUNTING_RIFLE 1@exp 65 script fix_boy@fix_Blueprint}
{65}{}{PID_SCOPED_HUNTING_RIFLE@Нет ничего лучше, чем увидеть удивленное выражение лица мишени. 20х оптический прицел Бойница, установленный на этом ружье, намного облегчает эту задачу. Ваши выстрелы будут точными от первого до последнего независимо от того, на кого вы охотитесь. Мин. сила: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_HUNTING_RIFLE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_SCOPED_HUNTING_RIFLE 1@exp 35 script fix_boy@fix_Blueprint}
{66}{}{PID_14MM_PISTOL@Автоматический пистолет ЗИГ-Зауэр калибра 14 мм. Крупное, однозарядное оружие отличного качества. Мин. сила: 4.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 2&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_14MM_PISTOL 1@exp 150 script fix_boy@fix_Blueprint}
{67}{}{PID_NEEDLER_PISTOL@Вы подозреваете, что этот пистолет-инъектор Брингама когда-то использовался для научных исследований. В качестве боеприпасов пистолет использует шприцы-дротики из твердого пластика. Мин. сила: 3.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 2&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_NEEDLER_PISTOL 1@exp 150 script fix_boy@fix_Blueprint}
{68}{}{PID_ASSAULT_RIFLE@Штурмовая винтовка AK-112 калибра 5 мм. Старая военная модель, вышедшая из употребления примерно во время войны. Может производить одиночные выстрелы или стрелять очередью. Использует высокоскоростные заряды калибра 5 мм. Мин. сила: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_FIREWOOD 2&PID_METAL_TRASH 8@PID_SPECIAL_WB1 1@PID_ASSAULT_RIFLE 1@exp 450 script fix_boy@fix_Blueprint}
{69}{}{PID_ASSAULT_RIFLE_EXT_MAG@Эта штурмовая винтовка оснащена увеличенным магазином армейского образца, благодаря чему теперь еще приятнее поливать всех огнем, чем когда-либо. Мин. сила: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_ASSAULT_RIFLE 1&PID_METAL_TRASH 3@PID_SPECIAL_WB1 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 100 script fix_boy@fix_Blueprint}
{70}{}{PID_FN_FAL@Эта винтовка была использована вооруженными силами более широко, чем какая-либо другая винтовка в истории. Эта модель была усовершенствована для увеличения убойной силы. Мин. сила: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 4&PID_JUNK 1&PID_HIGH_GRADE_STEEL 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_FN_FAL 1@exp 500 script fix_boy@fix_Blueprint}
{71}{}{PID_HK_CAWS@Дробовик ШОББ (Штурмовое оружие ближнего боя). Конструкция "буллпап" обеспечивает небольшой размер и также легкость обращения, в то же время сохраняя достаточную длину ствола. Мин. сила: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 2&PID_METAL_TRASH 10@PID_SPECIAL_WB1 1@PID_HK_CAWS 1@exp 540 script fix_boy@fix_Blueprint}
{72}{}{PID_HK_P90C@Хеклер-Кох P90c стал широко использоваться во время войны. Конструкция "буллпап" и компактный дизайн делают его легким в обращении. Он ценится за прочность, высокую огневую мощь и небольшой размер. Мин. сила: 4.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1&PID_HK_P90C_RECIPE 1@PID_SPECIAL_WB1 1@PID_HK_P90C 1@exp 420 script fix_boy@fix_Blueprint}
{73}{}{PID_223_PISTOL@Модифицированная винтовка калибра 0,223, обрезанная до размера пистолета. Это единственное в своем роде оружие, явно изготовленное с большим мастерством и любовью. Мин. сила: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_223_PISTOL 1@exp 420 script fix_boy@fix_Blueprint}
{74}{}{PID_XL70E3@Во время войны это оружие было экспериментальным. Так как производится оно в основном из высокопрочных полимеров, его практически невозможно разрушить. Оно обладает малым весом, большой скорострельностью и точностью, а разобрать его можно без помощи каких-либо инструментов. Мин. сила: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_KEVLAR_POLYMER 1&PID_METAL_TRASH 6&PID_HIGH_GRADE_STEEL 1&PID_XL70E3_RECIPE 1@PID_SPECIAL_WB1 1@PID_XL70E3 1@exp 720 script fix_boy@fix_Blueprint}
{75}{}{PID_SNIPER_RIFLE@Снайперская винтовка DKS-501. Отличное огнестрельное оружие дальнего действия. В оригинале оно было калибра 0,308, но конкретно этот экземпляр использует патроны более распространенного калибра 0,223. Мин. сила: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 5&PID_SNIPER_RIFLE_RECIPE 1@PID_SPECIAL_WB1 1@PID_SNIPER_RIFLE 1@exp 520 script fix_boy@fix_Blueprint}
{100}{}{PID_LASER_PISTOL@Лазерный пистолет 1000-Ватт. Гражданская модель - мощность снижена по сравнению с военными или полицейскими моделями. Использует малые батарейки. Мин. сила: 3.@@SK_ENERGY_WEAPONS 60|PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_LASER_PISTOL 1@exp 160 script fix_boy@fix_AnyStuff}
{101}{}{PID_MAGNETO_LASER_PISTOL@Этот лазерный пистолет 1000-Ватт был усовершенствован, и на него установлена  магнитная система калибровки, которая уплотняет лазерный пучок, увеличивая пробивную способность. Мин. сила: 3.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_LASER_PISTOL 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_MAGNETO_LASER_PISTOL 1@exp 40 script fix_boy@fix_Blueprint}
{102}{}{PID_PLASMA_PISTOL@Плазменный пистолет Глок 86. Разработан ИИ Гастона Глока. Выстреливает небольшим зарядом нагретой до предела плазмы. Питание осуществляется при помощи малых батареек. Мин. сила: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_JUNK 1&PID_ELECTRONIC_PART 3@PID_SPECIAL_WB1 1@PID_PLASMA_PISTOL 1@exp 345 script fix_boy@fix_Blueprint}
{103}{}{PID_PLASMA_PISTOL_EXT_CART@Магнитный патронник этого плазменного пистолета Глок 86 был усовершенствован с целью снижения нагрузки на аккумуляторные элементы. Эффективность оружия  повысилась вдвое, что позволяет произвести большее количество выстрелов до разряда батареи. Мин. сила: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_PLASMA_PISTOL 1&PID_METAL_TRASH 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 120 script fix_boy@fix_Blueprint}
{104}{}{PID_LASER_RIFLE@Лазерное ружье 2000-Ватт. Использует ядерные микрореакторы, что увеличивает мощность лазера. Ствол удлинен с целью увеличения дальнобойности. Мин. сила: 6.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 5&PID_JUNK 2&PID_ELECTRONIC_PART 6@PID_SPECIAL_WB1 1@PID_LASER_RIFLE 1@exp 640 script fix_boy@fix_Blueprint}
{105}{}{PID_LASER_RIFLE_EXT_CAP@Система перезарядки этого лазерного ружья 2000-Ватт усовершенствована. Установлен специальный рециркулирующий чип, который снижает нагрузку на ядерный микрореактор на 50%. Мин. сила: 6.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_LASER_RIFLE 1&PID_ENERGY_TRANSFORMER 1&PID_LASER_RIFLE_EXT_CAP_RECIPE 1@PID_SPECIAL_WB1 1@PID_LASER_RIFLE_EXT_CAP 1@exp 200 script fix_boy@fix_Blueprint}
{106}{}{PID_YK32_PULSE_PISTOL@YK32 - импульсное оружие, разработанное энергетическим консорциумом Юма Флэтс. Несмотря на свою мощность, YK32 никогда не был популярен - из-за большого расхода энергии и громоздкости. Мин. сила: 3.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 3&PID_ENERGY_TRANSFORMER 1@PID_SPECIAL_WB1 1@PID_YK32_PULSE_PISTOL 1@exp 630 script fix_boy@fix_Blueprint}
{107}{}{PID_PLASMA_RIFLE@Плазменное ружье Винчестер P94. Энергетическое оружие индустриальной эпохи, стреляющее нагретой до предела плазмой через сверхпроводящий ствол. Питание осуществляется при помощи ядерных микрореакторов. Мин. сила: 6.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_ENERGY_TRANSFORMER 1&PID_METAL_TRASH 4&PID_ELECTRONIC_PART 4&PID_PLASMA_RIFLE_RECIPE 1@PID_SPECIAL_WB1 1@PID_PLASMA_RIFLE 1@exp 740 script fix_boy@fix_Blueprint}
{130}{}{PID_FLAMER@Огнемет Факел-450. Стреляет струями горящей жидкости. Для работы необходимо топливо. Улучшенная модель - использует более "горячее" топливо. Мин. сила: 6.@@SK_BIG_GUNS 60|PE_PROF_GUNSMITH 1@PID_FIREWOOD 1&PID_TUBE 3&PID_METAL_TRASH 3&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_FLAMER 1@exp 255 script fix_boy@fix_AnyStuff}
{131}{}{PID_M60@Этот относительно легкий пулемет ценился солдатами всего мира за свою высокую скорострельность. Оружие, доказавшее свою надежность на поле боя, устанавливалось на машины и использовалось для огневой поддержки на уровне подразделений. Мин. сила: 7.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 5&PID_TUBE 3&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_M60 1@exp 340 script fix_boy@fix_Blueprint}
{132}{}{PID_IMPROVED_FLAMETHROWER@Огнемет Факел-450. Стреляет струями горящей жидкости. Для работы необходимо топливо. Улучшенная модель - использует более "горячее" топливо. Мин. сила: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_FLAMER 1&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_IMPROVED_FLAMETHROWER 1@exp 170 script fix_boy@fix_Blueprint}
{133}{}{PID_ROCKET_LAUNCHER@Гранатомет Роквелла "Супербазука". Оснащен шикарным трехфунтовым пусковым механизмом. Стреляет бронебойными или разрывными ракетами. Мин. сила: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_JUNK 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_ROCKET_LAUNCHER 1@exp 275 script fix_boy@fix_Blueprint}
{134}{}{PID_LIGHT_SUPPORT_WEAPON@Это штатное оружие поддержки имеет конструкцию "буллпап". Поэтому его довольно сложно использовать из позиции лежа, что послужило причиной для возвращения его войскам Национальной гвардии. Однако это оружие заслужило репутацию надежного и очень эффективного для своего размера. Мин. сила: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 3&PID_METAL_TRASH 4&PID_HIGH_GRADE_STEEL 1&PID_LIGHT_SUPPORT_WEAPON_RECIPE 1@PID_SPECIAL_WB1 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 410 script fix_boy@fix_Blueprint}
{135}{}{PID_MINIGUN@Персональный миниган CZ53 Роквелла. Многоствольный пулемет, стреляющий 5-мм патронами со скоростью свыше 60000 выстрелов в минуту. Мин. сила: 7.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 6&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_MINIGUN 1@exp 760 script fix_boy@fix_Blueprint}
{136}{}{PID_AVENGER_MINIGUN@Рокуэлл разработал "Мститель" как замену устаревшего CZ53. Среди новшеств - стабилизированные, охлаждаемые и хромированные каналы ствола. Это увеличивает дальнобойность и мощность оружия. Мин. сила: 7.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_MINIGUN 1&PID_HIGH_GRADE_STEEL 1&PID_ELECTRONIC_PART 1&PID_AVENGER_MINIGUN_RECIPE 1@PID_SPECIAL_WB1 1@PID_AVENGER_MINIGUN 1@exp 250 script fix_boy@fix_Blueprint}
{160}{}{PID_THROWING_KNIFE@Нож, специально сбалансированный для метания. Изготовлен из титана, с лазерной заточкой. Мин. сила: 3.@@SK_THROWING 50@PID_METAL_TRASH 2&PID_FIREWOOD 2@PID_SPECIAL_WB1 1@PID_THROWING_KNIFE 10@exp 60 script fix_boy@fix_Blueprint}
{161}{}{PID_MOLOTOV_COCKTAIL@Самодельная граната с запалом. Мин. сила: 3.@@SK_THROWING 50@PID_ROT_GUT 5@PID_SPECIAL_WB1 1@PID_MOLOTOV_COCKTAIL 10@exp 75 script fix_boy@fix_AnyStuff}
{162}{}{PID_FRAG_GRENADE@Обыкновенная осколочная граната. Содержит небольшое количество бризантного взрывчатого вещества. Большая часть опасных осколков формируется непосредственно из оболочки гранаты. Взрывается при ударе. Мин. сила: 3.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_FRAG_GRENADE 10@exp 225 script fix_boy@fix_Blueprint}
{163}{}{PID_PLASMA_GRENADE@Граната, в которой запечатана уплотненная при помощи магнитных полей плазма. Детонирует при помощи взрывчатого вещества. При ударе возникает взрыв перегретой плазмы. Мин. сила: 4.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_METAL_TRASH 4&PID_REFINED_ORE 2&PID_PLASMA_GRENADE_RECIPE 1@PID_SPECIAL_WB1 1@PID_PLASMA_GRENADE 10@exp 300 script fix_boy@fix_Blueprint}
{180}{}{PID_KNIFE@Острое колюще-режущее оружие. Мин. сила: 2.@@@PID_JUNK 1&PID_FIREWOOD 1@@PID_KNIFE 1@exp 30 script fix_boy@fix_AnyStuff}
{181}{}{PID_COMBAT_KNIFE@Высококачественный боевой нож модели "Сталлона" производства корпорации Остряк. Его лезвие гарантированно останется таким же острым даже через десять лет использования! Мин. сила: 2.@SK_UNARMED 70@SK_UNARMED 100@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_COMBAT_KNIFE 1@exp 75 script fix_boy@fix_AnyStuff}
{182}{}{PID_BRASS_KNUCKLES@Прочный кастет, изготовленный из стали. Защищает руку и обеспечивает больший урон при рукопашном бое. Мин. сила: 1.@@@PID_JUNK 2@@PID_BRASS_KNUCKLES 1@exp 30 script fix_boy@fix_AnyStuff}
{183}{}{PID_SPIKED_KNUCKLES@Улучшенная версия классического кастета. Такие кастеты наносят больший урон благодаря своим шипам, которые впиваются в противника, при рукопашном бое. Мин. сила: 1.@SK_UNARMED 70@SK_UNARMED 100@PID_BRASS_KNUCKLES 1&PID_JUNK 1@@PID_SPIKED_KNUCKLES 1@exp 10 script fix_boy@fix_AnyStuff}
{184}{}{PID_CLUB@Военная или полицейская дубинка из крепкого дерева. Мин. сила: 3.@SK_UNARMED 70@SK_UNARMED 100@PID_METAL_TRASH 1&PID_JUNK 1@PID_SPECIAL_WB1 1@PID_CLUB 1@exp 75 script fix_boy@fix_AnyStuff}
{185}{}{PID_SLEDGEHAMMER@Большой молот с массивной рукоятью. Очень популярное оружие среди мускулистых типов. Мин. сила: 6.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_SLEDGEHAMMER 1@exp 30 script fix_boy@fix_AnyStuff}
{186}{}{PID_SUPER_SLEDGE@Суперкувалда, произведенная Братством Стали с применением самых современных оружейных технологий. Оснащена накопителем кинетической энергии для усиления удара. Мин. сила: 5.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_FIREWOOD 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_SUPER_SLEDGE 1@exp 285 script fix_boy@fix_Blueprint}
{187}{}{PID_SPEAR@Заточенное до бритвенной остроты оружие. Древко деревянное, а наконечник изготовлен из кованой стали. Мин. сила: 4.@@@PID_JUNK 1&PID_FIREWOOD 1@@PID_SPEAR 1@exp 30 script fix_boy@fix_AnyStuff}
{188}{}{PID_SHARP_SPEAR@Оружие бритвенной остроты. Древко деревянное, наконечник из закаленной стали. Мин. сила: 4.@@@PID_SPEAR 1&PID_FLINT 1@PID_SPECIAL_WB1 1@PID_SHARP_SPEAR 1@exp 5 script fix_boy@fix_AnyStuff}
{189}{}{PID_CATTLE_PROD@Электрокнут модели "Лучший друг фермера" производства Ватт Электроникс. Эта модель была усовершенствована. Теперь электрический разряд стал мощнее. Мин. сила: 4.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_JUNK 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_CATTLE_PROD 1@exp 235 script fix_boy@fix_Blueprint}
{190}{}{PID_SUPER_CATTLE_PROD@Электрокнут модели "Лучший друг фермера" производства Ватт Электроникс. Эта модель была усовершенствована. Теперь электрический разряд стал мощнее. Мин. сила: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_CATTLE_PROD 1&PID_METAL_TRASH 2&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_SUPER_CATTLE_PROD 1@exp 150 script fix_boy@fix_Blueprint}
{191}{}{PID_RIPPER@Вибронож "Потрошитель"(tm). Питается от аккумуляторного элемента, зазубренное лезвие впивается в плоть жертвы, разрывая ее. Мин. сила: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_RIPPER 1@exp 270 script fix_boy@fix_Blueprint}
{192}{}{PID_POWER_FIST@Силовой кастет "Большой таран" производства компании Бью. Большинство считает его лучшим оружием для рукопашного боя. Остальные же просто его боятся. Питание обеспечивается малыми батарейками. Мин. сила: 1.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 2&PID_REFINED_ORE 1@PID_SPECIAL_WB1 1@PID_POWER_FIST 1@exp 380 script fix_boy@fix_Blueprint}
{193}{}{PID_MEGA_POWER_FIST@Силовой кастет "Большой таран" производства компании Бью. Многие считают его лучшим оружием для рукопашного боя. Конкретно этот кастет оснащен улучшенным  сервогенератором, увеличивающим силу удара. Питание обеспечивается малыми батарейками. Мин. сила: 1.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_POWER_FIST 1&PID_METAL_TRASH 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_MEGA_POWER_FIST 1@exp 110 script fix_boy@fix_Blueprint}
{210}{}{PID_LEATHER_JACKET@Черная плотная кожаная куртка.@@SK_OUTDOORSMAN 20@PID_CORD 1&PID_JUNK 1&PID_BRAHMIN_SKIN 1@PID_SPECIAL_WB1 1@PID_LEATHER_JACKET 1@exp 55 script fix_boy@fix_AnyStuff}
{211}{}{PID_CURED_LEATHER_ARMOR@Необычность этой очень прочной кожаной куртки в том, что у нее два рукава. Где бы и когда бы вы ее ни надели, вы наверняка произведете фурор.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 2&PID_JUNK 1&PID_BRAHMIN_SKIN 2&PID_LEATHER_JACKET 1@PID_SPECIAL_WB1 1@PID_CURED_LEATHER_ARMOR 1@exp 50 script fix_boy@fix_Blueprint}
{212}{}{PID_LEATHER_ARMOR@Ваша основная одежда из кожи. Искусно изготовлена из выделанной шкуры брамина.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 1&PID_GECKO_PELT 3&PID_GOLDEN_GECKO_PELT 1@PID_SPECIAL_WB1 1@PID_LEATHER_ARMOR 1@exp 170 script fix_boy@fix_Blueprint}
{213}{}{PID_LEATHER_ARMOR_MK_II@Усовершенствованная версия стандартной кожаной брони с несколькими уровнями защиты. Искусно изготовлена из выделанной шкуры брамина.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 1&PID_GOLDEN_GECKO_PELT 2&PID_LEATHER_ARMOR 1@PID_SPECIAL_WB1 1@PID_LEATHER_ARMOR_MK_II 1@exp 100 script fix_boy@fix_Blueprint}
{214}{}{PID_METAL_ARMOR@Броня, грубо сформированная из полированных металлических пластин.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_JUNK 1&PID_METAL_TRASH 4&PID_BRAHMIN_SKIN 1@PID_SPECIAL_WB1 1@PID_METAL_ARMOR 1@exp 235 script fix_boy@fix_Blueprint}
{215}{}{PID_METAL_ARMOR_MK_II@Броня, искусно сформированная из полированных металлических пластин.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_HIGH_GRADE_STEEL 2&PID_METAL_ARMOR 1@PID_SPECIAL_WB1 1@PID_METAL_ARMOR_MK_II 1@exp 360 script fix_boy@fix_Blueprint}
{216}{}{PID_TESLA_ARMOR@Эта блестящая броня обеспечивает лучшую защиту против энергетической атаки. Три электромагнитных уловителя Тесла частично рассеивают направленные энергетические удары.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_ENERGY_TRANSFORMER 1&PID_ELECTRONIC_PART 1&PID_METAL_ARMOR_MK_II 1@PID_SPECIAL_WB1 1@PID_TESLA_ARMOR 1@exp 360 script fix_boy@fix_Blueprint}
{217}{}{PID_COMBAT_ARMOR@Высокотехнологичная броня, изготовленная из улучшенных защитных полимеров.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_COMBAT_ARMOR_RECIPE 1&PID_KEVLAR_POLYMER 3&PID_BRAHMIN_SKIN 1&PID_CORD 3@PID_SPECIAL_WB1 1@PID_COMBAT_ARMOR 1@exp 530 script fix_boy@fix_Blueprint}
{218}{}{PID_COMBAT_ARMOR_MK_II@Высокотехнологичная броня, изготовленная из улучшенных защитных полимеров.@PE_PROF_ARMORER 3@PE_PROF_ARMORER 3@PID_COMBAT_ARMOR_MARK_II_RECIPE 1&PID_KEVLAR_POLYMER 2&PID_METAL_TRASH 3&PID_COMBAT_ARMOR 1@PID_SPECIAL_WB1 1@PID_COMBAT_ARMOR_MK_II 1@exp 380 script fix_boy@fix_Blueprint}
{219}{}{PID_BLACK_ROBE@Robe made from high-tech materials designed by Hubologist's which highly absorb photons gaining a camouflage effect to help you scouting some areas undetected.@PE_PROF_ARMORER 3@PE_PROF_ARMORER 3@PID_CORD 4&PID_CHEMICAL_COMPONENTS 3&PID_KEVLAR_POLYMER 2&PID_FIRE_GECKO_PELT 2&PID_HUBOLOGIST_ROBE_RECIPE 1@PID_SPECIAL_WB1 1@PID_BLACK_ROBE 1@exp 540 script fix_boy@fix_Blueprint}
{240}{}{PID_10MM_JHP@Вид боеприпасов. Калибр: 10 мм, полуоболочечные@@@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_10MM_JHP 100@exp 155 script fix_boy@fix_AnyStuff}
{241}{}{PID_10MM_AP@Вид боеприпасов. Калибр: 10 мм, бронебойные.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_10MM_AP 100@exp 275 script fix_boy@fix_AnyStuff}
{242}{}{PID_SHOTGUN_SHELLS@Вид боеприпасов для дробовика. На данных патронах стоит отметка: "12 калибр. Не давать детям до 3 лет".@@@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_SHOTGUN_SHELLS 100@exp 155 script fix_boy@fix_AnyStuff}
{243}{}{PID_FLAMETHROWER_FUEL@Цилиндр, в котором содержится легковоспламеняемое жидкое топливо для огнеметов.@@@PID_ROT_GUT 5@PID_SPECIAL_WB1 1@PID_FLAMETHROWER_FUEL 30@exp 75 script fix_boy@fix_AnyStuff}
{244}{}{PID_FLAMETHROWER_FUEL_MK_II@Это топливо для огнемета представляет собой улучшенную сверхгорючую смесь.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_CHEMICAL_COMPONENTS 1&PID_FLAMETHROWER_FUEL 30@PID_SPECIAL_WB1 1@PID_FLAMETHROWER_FUEL_MK_II 30@exp 60 script fix_boy@fix_AnyStuff}
{245}{}{PID_SMALL_ENERGY_CELL@Небольшая автономная единица хранения энергии.@@@PID_METAL_TRASH 2&PID_ELECTRONIC_PART 2&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_SMALL_ENERGY_CELL 50@exp 250 script fix_boy@fix_AnyStuff}
{246}{}{PID_44_MAGNUM_JHP@Обойма патронов, калибр 0,44 Магнум, полуоболочечные.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_44_MAGNUM_JHP 100@exp 155 script fix_boy@fix_AnyStuff}
{247}{}{PID_44_FMJ_MAGNUM@Обойма боеприпасов. Калибр 0,44 Магнум. Оболочечные.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_44_FMJ_MAGNUM 100@exp 275 script fix_boy@fix_AnyStuff}
{248}{}{PID_9MM_BALL@Древние патроны калибра 9х19 мм. Обильная смазка защищает их от повреждений. Стандартные пули.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 3@PID_SPECIAL_WB1 1@PID_9MM_BALL 100@exp 105 script fix_boy@fix_AnyStuff}
{249}{}{PID_45_CALIBER_AMMO@Вид боеприпасов. Калибр 0,45.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_45_CALIBER_AMMO 100@exp 155 script fix_boy@fix_AnyStuff}
{250}{}{PID_223_FMJ@Магазин с пулями, калибр 0,223, оболочечные.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_JUNK 2&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_223_FMJ 100@exp 330 script fix_boy@fix_AnyStuff}
{251}{}{PID_7_62MM_AMMO@Вид боеприпасов. Калибр: 7,62 мм.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_JUNK 2&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_7_62MM_AMMO 100@exp 330 script fix_boy@fix_AnyStuff}
{252}{}{PID_EXPLOSIVE_ROCKET@Ракета, оснащенная мощной разрывной боеголовкой.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 6&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_EXPLOSIVE_ROCKET 10@exp 425 script fix_boy@fix_AnyStuff}
{253}{}{PID_ROCKET_AP@Снаряд, обладающий меньшей взрывной силой, но разработанный с целью пробивать броню.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 8&PID_GUNPOWDER 6&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_ROCKET_AP 10@exp 670 script fix_boy@fix_AnyStuff}
{254}{}{PID_14MM_AP@Боеприпасы крупного калибра. 14 мм, бронебойные.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_14MM_AP 100@exp 325 script fix_boy@fix_AnyStuff}
{255}{}{PID_HN_NEEDLER_CARTRIDGE@Вид боеприпасов. Судя по всему, это боеприпасы для пистолета-инъектора. Каждая "пуля" представляет собой маленький шприц, содержимое которого впрыскивается под кожу цели при контакте.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_HN_NEEDLER_CARTRIDGE 100@exp 275 script fix_boy@fix_AnyStuff}
{257}{}{PID_5MM_JHP@Обойма небольших легких пуль. Калибр: 5 мм, полуоболочечные.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_5MM_JHP 100@exp 350 script fix_boy@fix_AnyStuff}
{258}{}{PID_5MM_AP@Обойма малокалиберных пуль. 5 мм, бронебойные.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 6&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_5MM_AP 100@exp 450 script fix_boy@fix_AnyStuff}
{259}{}{PID_MICRO_FUSION_CELL@Средняя по величине единица производства энергии. Автономный ядерный реактор.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_SMALL_ENERGY_CELL 100@PID_SPECIAL_WB1 1@PID_MICRO_FUSION_CELL 30@exp 100 script fix_boy@fix_AnyStuff}
{260}{}{PID_MICRO_FUSION_CELL@Средняя по величине единица производства энергии. Автономный ядерный реактор.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_REFINED_ORE 3@PID_SPECIAL_WB1 1@PID_MICRO_FUSION_CELL 100@exp 450 script fix_boy@fix_AnyStuff}
{280}{}{PID_METAL_TRASH@Металлические части, могут быть использованы в производстве.@@@PID_METAL_ORE 2@PID_SPECIAL_WB1 1|PID_SPECIAL_WB2 1@PID_METAL_TRASH 1@exp 20 script fix_boy@fix_AnyStuff}
{281}{}{PID_GUNPOWDER@Коробочка с черным порохом.@@@PID_MINERAL 2@PID_SPECIAL_WB1 1|PID_SPECIAL_WB2 1@PID_GUNPOWDER 1@exp 20 script fix_boy@fix_AnyStuff}
{282}{}{PID_ROT_GUT@Очень крепкий алкогольный напиток или чистящая жидкость - как вам больше нравится.@@@PID_MUTATED_FRUIT 5&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_ROT_GUT 5@exp 40 script fix_boy@fix_AnyStuff}
{283}{}{PID_CIGARETTES@Совершенно обычные постядерные американские сигареты известной марки "Нюкаборо".@@@PID_TOBACCO 1&PID_TORN_PAPER 5@PID_SPECIAL_WB1 1@PID_CIGARETTES 1@exp 105 script fix_boy@fix_AnyStuff}
{284}{}{PID_HEALING_POWDER@Сильное народное средство. Залечивает раны, но вызывает сонливость.@@@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@@PID_HEALING_POWDER 1@exp 10 script fix_boy@fix_AnyStuff}
{285}{}{PID_ANTIDOTE@Бутылка с самодельным противоядием. Молочная жидкость с плавающими в ней кусочками мяса радскорпионов.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_SCORPION_TAIL 2@@PID_ANTIDOTE 1@exp 20 script fix_boy@fix_AnyStuff}
{286}{}{PID_STIMPAK@Лекарственное вещество. При инъекции это вещество обеспечивает немедленное исцеление небольших ран.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_HYPODERMIC_NEEDLE 1@PID_SPECIAL_WB1 1@PID_STIMPAK 1@exp 20 script fix_boy@fix_AnyStuff}
{287}{}{PID_SUPER_STIMPAK@Усовершенствованный лекарственный препарат. Очень мощный. Суперстимуляторы через определенное время наносят небольшой урон здоровью из-за  сильнодействующих химических веществ, входящих в их состав.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_BROC_FLOWER 2&PID_XANDER_ROOT 2&PID_CHEMICAL_COMPONENTS 2&PID_HYPODERMIC_NEEDLE 5@PID_SPECIAL_WB1 1@PID_SUPER_STIMPAK 5@exp 270 script fix_boy@fix_AnyStuff}
{288}{}{PID_MENTATS@Таблетки из химического вещества, расширяющего сознание. Улучшает функции головного мозга, связанные с памятью, а также убыстряет некоторые умственные процессы.  Вызывает сильное привыкание.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_MUTATED_FRUIT 5&PID_CHEMICAL_COMPONENTS 1@PID_SPECIAL_WB1 1@PID_MENTATS 1@exp 135 script fix_boy@fix_AnyStuff}
{289}{}{PID_RADAWAY@Химический раствор, молекулы которого связывают радиоактивные частицы и выводят их из организма. Для полного эффекта требует времени.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_CHEMICAL_COMPONENTS 1&PID_HYPODERMIC_NEEDLE 1&PID_XANDER_ROOT 2&PID_ROENTGEN_RUM 2@PID_SPECIAL_WB1 1@PID_RADAWAY 1@exp 140 script fix_boy@fix_Blueprint}
{290}{}{PID_RAD_X@Антирадиационный препарат, который необходимо принять до облучения. Побочных эффектов не вызывает.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_CHEMICAL_COMPONENTS 1&PID_GAMMA_GULP_BEER 2&PID_BROC_FLOWER 2@PID_SPECIAL_WB1 1@PID_RAD_X 1@exp 130 script fix_boy@fix_Blueprint}
{292}{}{PID_BUFFOUT@Мощные стероиды. Их действие состоит в увеличении силы и обострении рефлексов. Вызывают сильное привыкание.@PE_PROF_CHEMIST 3@PE_PROF_CHEMIST 3@PID_CHEMICAL_COMPONENTS 3@PID_SPECIAL_WB1 1@PID_BUFFOUT 1@exp 300 script fix_boy@fix_Blueprint}
{293}{}{PID_JET@Винт - мощный амфетамин, стимулирующий центральную нервную систему. Первоначальный прилив эйфории редко длится больше пары минут, но в это время энергия и сила употребляющего значительно возрастают.@PE_PROF_CHEMIST 3@PE_PROF_CHEMIST 3@PID_CHEMICAL_COMPONENTS 3@PID_SPECIAL_WB1 1@PID_JET 1@exp 300 script fix_boy@fix_AnyStuff}
{309}{}{PID_PICKAXE@Обычная кирка. Такую используют шахтеры.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_PICKAXE 1@exp 30 script fix_boy@fix_AnyStuff}
{310}{}{PID_AXE@Повидавший виды топор. Лезвие все-ещё в относительно хорошем состоянии.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_AXE 1@exp 30 script fix_boy@fix_AnyStuff}
{311}{}{PID_ROPE@Прочная толстая веревка. Примерно 45 футов в длину.@@@PID_CORD 3@PID_SPECIAL_WB1 1@PID_ROPE 1@exp 60 script fix_boy@fix_AnyStuff}
{312}{}{PID_LOCKPICKS@Набор инструментов взломщика. Включает в себя все необходимые отмычки и гаечные ключи для открытия классических механических замков. Конкретно в этот набор также входят некоторые инструменты для взлома более сложных механических замков.@@@PID_METAL_TRASH 1&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_LOCKPICKS 1@exp 70 script fix_boy@fix_AnyStuff}
{313}{}{PID_FLARE@Сигнальный фонарь. Дает освещение на короткое время, виден с большого расстояния. Бумага несколько истрепалась, но в остальном все в порядке. Для включения поверните верхнюю часть.@@SK_SCIENCE 30@PID_CHEMICAL_COMPONENTS 2&PID_MINERAL 1&PID_TUBE 1@PID_SPECIAL_WB1 1@PID_FLARE 1@exp 125 script fix_boy@fix_AnyStuff}
{314}{}{PID_RADIO@Рация модели 2043B от прекрасной компании Ватт Электроникс. Надежная, прочная и камуфлированная. С дополнительным разъемом RS-121.@@SK_REPAIR 30@PID_JUNK 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_RADIO 1@exp 75 script fix_boy@fix_AnyStuff}
{315}{}{PID_PRIMITIVE@Просто камень прикрепленный к палке. Можно использовать для добычи дерева или руды.@@@PID_FLINT 1@@PID_PRIMITIVE 1@exp 5 script fix_boy@fix_AnyStuff}
{316}{}{PID_MOVABLE_AMMO_BOX_L1@Деревянный ящик для хранения патронов.@@@PID_FIREWOOD 20&PID_CORD 5&PID_METAL_TRASH 8@@PID_MOVABLE_AMMO_BOX_L1 1@exp 800 script fix_boy@fix_AnyStuff}
{317}{}{PID_MOVABLE_AMMO_BOX_S1@Деревянный ящик для хранения патронов.@@@PID_FIREWOOD 10&PID_CORD 2&PID_METAL_TRASH 4@@PID_MOVABLE_AMMO_BOX_S1 1@exp 390 script fix_boy@fix_AnyStuff}
{318}{}{PID_MOVABLE_POOR_BOX@Небольшая коробка, в которую собирают деньги для бедных.@@@PID_FIREWOOD 5&PID_CORD 3@@PID_MOVABLE_POOR_BOX 1@exp 135 script fix_boy@fix_AnyStuff}
{319}{}{PID_MOVABLE_CHEST@Деревянный сундук.@@@PID_FIREWOOD 15&PID_CORD 5@@PID_MOVABLE_CHEST 1@exp 325 script fix_boy@fix_AnyStuff}
{329}{}{PID_MOVABLE_CRATE@Деревянный ящик.@@@PID_FIREWOOD 10&PID_CORD 5@@PID_MOVABLE_CRATE 1@exp 250 script fix_boy@fix_AnyStuff}
{330}{}{PID_MOVABLE_FOOTLOCKER1@Сундучок. Предназначен для хранения вещей, удобно располагается у кровати.@@@PID_METAL_TRASH 12@PID_SPECIAL_WB1 1@PID_MOVABLE_FOOTLOCKER1 1@exp 600 script fix_boy@fix_AnyStuff}
{331}{}{PID_MOVABLE_LOCKER1@Обычный сундучок для хранения вещей.@@@PID_METAL_TRASH 18@PID_SPECIAL_WB1 1@PID_MOVABLE_LOCKER1 1@exp 900 script fix_boy@fix_AnyStuff}
{332}{}{PID_MOVABLE_SAFE@Тяжелый металлический сейф.@@@PID_METAL_TRASH 25@PID_SPECIAL_WB1 1@PID_MOVABLE_SAFE 1@exp 1250 script fix_boy@fix_AnyStuff}
{401}{}{PID_YK42B_PULSE_RIFLE@YK42B - импульсное оружие, разработанное консорциумом Юма Флэтс. Оно считается более совершенным по сравнению с пистолетом YK32, обладая большей дальнобойностью и энергоемкостью. Мин. сила: 6.@@@PID_YK42B_PULSE_RIFLE_RECIPE 1&PID_PARTICLE_ACCELERATOR 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 3&PID_METAL_TRASH 6@PID_T4_WBSierra 1@PID_YK42B_PULSE_RIFLE 1@exp 1000 script fix_boy@fix_Sierra}
{402}{}{PID_GATLING_LASER@Гатлинг-лазер H&K L30. В начале войны представлял собой прототип. Благодаря нескольким стволам некоторое время удается избежать перегрева. Питание осуществляется при помощи ядерных микрореакторов. Мин. сила: 6.@@@PID_GATLING_LASER_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 4&PID_METAL_TRASH 8@PID_T4_WBSierra 1@PID_GATLING_LASER 1@exp 1000 script fix_boy@fix_Sierra}
{403}{}{PID_BOZAR@Вершина снайперского вооружения. Хотя это оружие, возможно, слишком наворочено и часто заедает, если не держать его в идеальной чистоте, его точность более чем компенсирует эти дополнительные требования к уходу за оружием. Мин. сила: 6.@@@PID_BOZAR_RECIPE 1&PID_RECOIL_COMPENSATOR 1&PID_TELESCOPIC_SIGHTS 1&PID_HIGH_GRADE_STEEL 4&PID_METAL_TRASH 10@PID_T4_WBSierra 1@PID_BOZAR 1@exp 1000 script fix_boy@fix_Sierra}
{404}{}{PID_VINDICATOR_MINIGUN@Немецкая компания Рейнметал АГ разработала совершенный миниган. "Виндикатор" производит из своих шести углепластиковых стволов более 90 000 выстрелов в минуту. Это идеальное оружие - пик тевтонской инженерной мысли. Мин. сила: 7.@@@PID_VINDICATOR_MINIGUN_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_ROTARY_CHAMBER 1&PID_HIGH_GRADE_STEEL 3&PID_METAL_TRASH 8@PID_T4_WBSierra 1@PID_VINDICATOR_MINIGUN 1@exp 1000 script fix_boy@fix_Sierra}
{405}{}{PID_HK_G11@Эта винтовка - революция в дизайне оружия. В ней используются безгильзовые боеприпасы, состоящие из метательного ВВ, внутри которого находится пуля. Так экономятся вес и пространство, что повышает объем магазина. Мин. сила: 5.@@@PID_HK_G11_RECIPE 1&PID_ROTARY_CHAMBER 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 2&PID_METAL_TRASH 8&PID_TUBE 1@PID_T4_WBSierra 1@PID_HK_G11 1@exp 1000 script fix_boy@fix_Sierra}
{406}{}{PID_HK_G11E@Это оружие - сенсация в конструкции вооружения. Оно использует безгильзовые патроны из метательного ВВ, внутри которого находится пуля. Так экономится вес и пространство, что повышает объем магазина. Мин. сила: 6.@@@PID_HK_G11E_RECIPE 1&PID_HK_G11 1&PID_ELECTRONIC_FIRE_MECHANISM 1@PID_T4_WBSierra 1@PID_HK_G11E 1@exp 1000 script fix_boy@fix_Sierra}
{407}{}{PID_PK12_GAUSS_PISTOL@Гауссов пистолет PPK12, разработанный в Германии, ценится за высокую мощность  и дальнобойность. Он позволяет стрелять с невероятной скоростью и пробивает практически любую броню. Мин. сила: 4.@@@PID_PPK12_GAUSS_PISTOL_RECIPE 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_PARTICLE_ACCELERATOR 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 6@PID_T4_WBSierra 1@PID_PK12_GAUSS_PISTOL 1@exp 1000 script fix_boy@fix_Sierra}
{408}{}{PID_M72_GAUSS_RIFLE@M72 разработали в Германии. Снаряд разгоняется электромагнитным полем и пробивает практически любое препятствие. Дальнобойность, точность и мощность этого оружия не сравнима ни с чем. Мин. сила: 6.@@@PID_M72_GAUSS_RIFLE_RECIPE 1&PID_PK12_GAUSS_PISTOL 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 4&PID_TUBE 1@PID_T4_WBSierra 1@PID_M72_GAUSS_RIFLE 1@exp 1000 script fix_boy@fix_Sierra}
{409}{}{PID_POWERED_ARMOR@Высокотехнологичная автономная броня. Питается от ядерного микрореактора с запасом топлива лет на сто.@@@PID_POWER_ARMOR_SHELL 1&PID_HIFLO_HYDRAULIC 1&PID_MICRO_FUSION_PACK 1&PID_TECHNICAL_MANUAL 1@PID_T4_WBSierra 1@PID_POWERED_ARMOR 1@exp 1000 script fix_boy@fix_Sierra}
{410}{}{PID_ADVANCED_POWER_ARMOR@Эта силовая броня изготовлена из облегченных металлических сплавов и усилена в ключевых местах керамическими накладками. Сервоприводы, облегчающие движение, также высокого качества.@@@PID_ADVANCED_POWER_ARMOR_SHELL 1&PID_IMPROVED_SERVOS 1&PID_MICRO_FUSION_PACK 1&PID_ADVANCED_POWER_ARMOR_MANUAL 1@PID_T4_WBSierra 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000 script fix_boy@fix_Sierra}
{411}{}{PID_YK42B_PULSE_RIFLE@YK42B - импульсное оружие, разработанное консорциумом Юма Флэтс. Оно считается более совершенным по сравнению с пистолетом YK32, обладая большей дальнобойностью и энергоемкостью. Мин. сила: 6.@@@PID_YK42B_PULSE_RIFLE_RECIPE 1&PID_PARTICLE_ACCELERATOR 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 3&PID_METAL_TRASH 6&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_YK42B_PULSE_RIFLE 1@exp 1000 script fix_boy@fix_Vault}
{412}{}{PID_GATLING_LASER@Гатлинг-лазер H&K L30. В начале войны представлял собой прототип. Благодаря нескольким стволам некоторое время удается избежать перегрева. Питание осуществляется при помощи ядерных микрореакторов. Мин. сила: 6.@@@PID_GATLING_LASER_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 4&PID_METAL_TRASH 8&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_GATLING_LASER 1@exp 1000 script fix_boy@fix_Vault}
{413}{}{PID_BOZAR@Вершина снайперского вооружения. Хотя это оружие, возможно, слишком наворочено и часто заедает, если не держать его в идеальной чистоте, его точность более чем компенсирует эти дополнительные требования к уходу за оружием. Мин. сила: 6.@@@PID_BOZAR_RECIPE 1&PID_RECOIL_COMPENSATOR 1&PID_TELESCOPIC_SIGHTS 1&PID_HIGH_GRADE_STEEL 4&PID_METAL_TRASH 10&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_BOZAR 1@exp 1000 script fix_boy@fix_Vault}
{414}{}{PID_VINDICATOR_MINIGUN@Немецкая компания Рейнметал АГ разработала совершенный миниган. "Виндикатор" производит из своих шести углепластиковых стволов более 90 000 выстрелов в минуту. Это идеальное оружие - пик тевтонской инженерной мысли. Мин. сила: 7.@@@PID_VINDICATOR_MINIGUN_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_ROTARY_CHAMBER 1&PID_HIGH_GRADE_STEEL 3&PID_METAL_TRASH 8&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_VINDICATOR_MINIGUN 1@exp 1000 script fix_boy@fix_Vault}
{415}{}{PID_HK_G11@Эта винтовка - революция в дизайне оружия. В ней используются безгильзовые боеприпасы, состоящие из метательного ВВ, внутри которого находится пуля. Так экономятся вес и пространство, что повышает объем магазина. Мин. сила: 5.@@@PID_HK_G11_RECIPE 1&PID_ROTARY_CHAMBER 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 2&PID_METAL_TRASH 8&PID_TUBE 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_HK_G11 1@exp 1000 script fix_boy@fix_Vault}
{416}{}{PID_HK_G11E@Это оружие - сенсация в конструкции вооружения. Оно использует безгильзовые патроны из метательного ВВ, внутри которого находится пуля. Так экономится вес и пространство, что повышает объем магазина. Мин. сила: 6.@@@PID_HK_G11E_RECIPE 1&PID_HK_G11 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_HK_G11E 1@exp 1000 script fix_boy@fix_Vault}
{417}{}{PID_PK12_GAUSS_PISTOL@Гауссов пистолет PPK12, разработанный в Германии, ценится за высокую мощность  и дальнобойность. Он позволяет стрелять с невероятной скоростью и пробивает практически любую броню. Мин. сила: 4.@@@PID_PPK12_GAUSS_PISTOL_RECIPE 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_PARTICLE_ACCELERATOR 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 6&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_PK12_GAUSS_PISTOL 1@exp 1000 script fix_boy@fix_Vault}
{418}{}{PID_M72_GAUSS_RIFLE@M72 разработали в Германии. Снаряд разгоняется электромагнитным полем и пробивает практически любое препятствие. Дальнобойность, точность и мощность этого оружия не сравнима ни с чем. Мин. сила: 6.@@@PID_M72_GAUSS_RIFLE_RECIPE 1&PID_PK12_GAUSS_PISTOL 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 4&PID_TUBE 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_M72_GAUSS_RIFLE 1@exp 1000 script fix_boy@fix_Vault}
{419}{}{PID_POWERED_ARMOR@Высокотехнологичная автономная броня. Питается от ядерного микрореактора с запасом топлива лет на сто.@@@PID_POWER_ARMOR_SHELL 1&PID_HIFLO_HYDRAULIC 1&PID_MICRO_FUSION_PACK 1&PID_TECHNICAL_MANUAL 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_POWERED_ARMOR 1@exp 1000 script fix_boy@fix_Vault}
{420}{}{PID_ADVANCED_POWER_ARMOR@Эта силовая броня изготовлена из облегченных металлических сплавов и усилена в ключевых местах керамическими накладками. Сервоприводы, облегчающие движение, также высокого качества.@@@PID_ADVANCED_POWER_ARMOR_SHELL 1&PID_IMPROVED_SERVOS 1&PID_MICRO_FUSION_PACK 1&PID_ADVANCED_POWER_ARMOR_MANUAL 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000 script fix_boy@fix_Vault}
{500}{}{PID_CATS_PAW@ONLY FOR SCIENCING@ST_STRENGTH 200@ST_STRENGTH 200@PID_TORN_PAPER 3@PID_SPECIAL_WB1 1@PID_CATS_PAW 1@script fix_boy@fix_AnyStuff}
