{10}{}{Герой}
{20}{}{Героиня}
{30}{}{Деревенщина}
{40}{}{Деревенщина}
{50}{}{Рад-скорпион}
{51}{}{Небольшой мутировавший скорпион.}
{60}{}{Рад-скорпион}
{61}{}{Мутировавший скорпион}
{70}{}{Коготь Смерти}
{71}{}{Маленький Коготь Смерти}
{80}{}{Коготь Смерти}
{81}{}{Маленький Коготь Смерти}
{90}{}{Пес}
{91}{}{Собака, наверняка бездомная, дворняжьей породы.}
{100}{}{Брамин}
{101}{}{Двухголовая корова-мутант.}
{110}{}{Грызун}
{111}{}{Самый обыкновенный большой грызун.}
{120}{}{Мантис}
{121}{}{Страшно надоедливое существо.}
{130}{}{Старейшая}
{140}{}{Хакунин}
{150}{}{Минок}
{160}{}{Хищный Цветок}
{161}{}{Плотоядное растение.}
{170}{}{Симпатичный раб}
{180}{}{Красивый раб}
{190}{}{Здоровая рабыня}
{200}{}{Здоровый раб}
{210}{}{Сильная рабыня}
{220}{}{Сильный раб}
{230}{}{Боевая рабыня}
{240}{}{Боевой раб}
{250}{}{Умная рабыня}
{260}{}{Умный раб}
{270}{}{Обычная рабыня}
{280}{}{Обычный раб}
{290}{}{Анна}
{300}{}{Крутой бандит}
{310}{}{Крутая воровка}
{320}{}{Жестокий бандит}
{330}{}{Лихая разбойница}
{340}{}{Проворный бандит}
{350}{}{Ловкая потаскуха}
{360}{}{Мощный бандит}
{370}{}{Стерва с пушкой}
{380}{}{Бандит с пушкой}
{390}{}{Дешевая шлюха}
{400}{}{Крутой Охранник}
{410}{}{Крутая Охранница}
{420}{}{Мощный Охранник}
{430}{}{Мощная Охранница}
{440}{}{Ловкий Охранник}
{450}{}{Ловкая Охранница}
{460}{}{Охранник со стволом}
{470}{}{Охранница со стволом}
{480}{}{Охранник с пушкой}
{490}{}{Охранница с пушкой}
{500}{}{Сирота}
{510}{}{Сирота}
{520}{}{Ребенок}
{530}{}{Ребенок}
{540}{}{Нищий}
{550}{}{Нищенка}
{560}{}{Плохой торговец}
{570}{}{Плохая торговка}
{580}{}{Обычный продавец}
{590}{}{Обычная продавщица}
{600}{}{Мастер-купец}
{610}{}{Мастерица-купчиха}
{620}{}{Вик}
{630}{}{Слабый крестьянин}
{640}{}{Слабая крестьянка}
{650}{}{Обычный крестьянин}
{660}{}{Обычная крестьянка}
{670}{}{Сильный крестьянин}
{680}{}{Сильная крестьянка}
{690}{}{Слабый охранник}
{700}{}{Слабая охранница}
{710}{}{Слабый стрелок}
{720}{}{Слабая снайперша}
{730}{}{Робот-ремонтник}
{740}{}{Робот-ремонтник тип 2}
{750}{}{Робомозг}
{760}{}{Летучий Глаз}
{770}{}{Робот-страж}
{780}{}{Робот-страж тип 2}
{790}{}{Робомозг}
{800}{}{Мелкий ящер}
{810}{}{Крутой ящерок}
{820}{}{Волк}
{821}{}{Жестокое и свирепое хищное животное.}
{830}{}{Золотой ящер}
{840}{}{Коготь Смерти}
{850}{}{Отродье Когтя Смерти}
{860}{}{Сильный Золотой ящер}
{870}{}{Линетта}
{880}{}{Доктор Трой}
{890}{}{Джон Кэссиди}
{900}{}{Грегори}
{910}{}{Гражданка}
{920}{}{Гражданин}
{930}{}{Богатая гражданка}
{940}{}{Богатый гражданин}
{950}{}{Траппер}
{960}{}{Траппер}
{970}{}{Сулик}
{980}{}{Майда Бакнер}
{990}{}{Торр}
{1000}{}{Лумпи}
{1010}{}{Светящийся призрак}
{1020}{}{Призрак реактора}
{1030}{}{Стражник реактора}
{1040}{}{Зомак}
{1050}{}{Скитер}
{1060}{}{Крысиный Мозг}
{1070}{}{Ленни}
{1080}{}{Вузи}
{1090}{}{Гарольд}
{1100}{}{Крот-гризли}
{1110}{}{Большой крот-гризли}
{1120}{}{Крысокабан}
{1130}{}{Свирепый крысокабан}
{1140}{}{Слабый брамин}
{1141}{}{Мутировавшая двухголовая корова.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Крыса-мутант}
{1161}{}{Мутировавшая от радиации крыса.}
{1170}{}{Мутировавший крот-гризли}
{1171}{}{Покрутевший и злой крот-гризли.}
{1180}{}{Мутировавший крысокабан}
{1181}{}{Сильно оголодавший от мутации монстр.}
{1190}{}{Супер Мутант}
{1200}{}{Мутант}
{1210}{}{Супер Мутант}
{1220}{}{Нero Andro (don't use)}
{1230}{}{Нero Andro (don't use)}
{1240}{}{Нero Male (don't use)}
{1250}{}{Нero Female (don't use)}
{1260}{}{Нero Male (don't use)}
{1270}{}{Нero Female (don't use)}
{1280}{}{Нero Male (don't use)}
{1290}{}{Нero Female (don't use)}
{1300}{}{Нero Male (don't use)}
{1310}{}{Нero Female (don't use)}
{1320}{}{Нero Male (don't use)}
{1330}{}{Нero Female (don't use)}
{1340}{}{Гвардеец Города}
{1350}{}{Гвардеец Города}
{1360}{}{Кибердог}
{1370}{}{Стражник НКР}
{1380}{}{Стражник НКР}
{1390}{}{Полицейский НКР}
{1400}{}{Сторож рабов}
{1410}{}{Надсмотрщик}
{1420}{}{Великий торговец людьми}
{1430}{}{Великая торговка людьми}
{1440}{}{Танди}
{1450}{}{Мерк}
{1460}{}{Ратч}
{1470}{}{Скитер}
{1480}{}{Майки}
{1490}{}{Бармен НКР}
{1500}{}{Владелец магазина}
{1510}{}{Грунтар}
{1520}{}{Горис}
{1530}{}{Хищный крот-гризли}
{1540}{}{Хищный крот-гризли}
{1550}{}{Хищный крот-гризли}
{1560}{}{Хищный крот-гризли}
{1570}{}{Хищный крот-гризли}
{1580}{}{Хищный крот-гризли}
{1590}{}{Обычный призрак}
{1600}{}{Мирон}
{1610}{}{Маркус}
{1620}{}{Доктор Джонс}
{1630}{}{Дэвин}
{1640}{}{Мирия}
{1650}{}{Лэдди}
{1660}{}{Рондо}
{1670}{}{Подмастерье}
{1680}{}{Подмастерье}
{1690}{}{Подмастерье}
{1700}{}{Вышибала}
{1710}{}{Вышибала}
{1720}{}{Слабый мр. Хэнди}
{1730}{}{Обычный Светящийся}
{1740}{}{Дар}
{1750}{}{Далиа}
{1760}{}{Гордон}
{1770}{}{test (don't use)}
{1780}{}{Призрак реактора}
{1790}{}{Обычный призрак}
{1800}{}{Мэтт}
{1810}{}{Командир охотников}
{1820}{}{Охотник за бандитами}
{1830}{}{Командир охотников}
{1840}{}{Охотник за бандитами}
{1850}{}{Охотник за бандитами}
{1860}{}{Командир охотников}
{1870}{}{Охотник за бандитами}
{1880}{}{Охотник за бандитами}
{1890}{}{Командир охотников}
{1900}{}{Охотник за бандитами}
{1910}{}{Бесс}
{1911}{}{Двухголовая мутировавшая корова.}
{1920}{}{Балтас}
{1930}{}{Гришэм}
{1940}{}{Фил}
{1950}{}{Цыпленок}
{1960}{}{Карл}
{1970}{}{Джонни}
{1980}{}{Джо}
{1990}{}{Зеке}
{2000}{}{Мясник}
{2010}{}{Питти}
{2020}{}{Воин племени}
{2030}{}{Воительница племени}
{2040}{}{Каннибал}
{2050}{}{Людоедка}
{2060}{}{Святой муж}
{2070}{}{Святая женщина}
{2080}{}{Кочевник}
{2090}{}{Кочевник}
{2100}{}{Кочевница}
{2110}{}{Кочевница}
{2120}{}{Убийца}
{2130}{}{Убийца}
{2140}{}{Крестьянин}
{2150}{}{Крестьянка}
{2160}{}{Мантис}
{2170}{}{Рабовладелец}
{2180}{}{Рабовладелица}
{2190}{}{Дикий брамин}
{2200}{}{Переселенец}
{2210}{}{Переселенка}
{2220}{}{Патрульный Города}
{2230}{}{Патрульная Города}
{2240}{}{Сильный рабовладелец}
{2250}{}{Сильная рабовладелица}
{2260}{}{Чокнутый}
{2270}{}{Мародер}
{2280}{}{Чокнутый из Глоу}
{2290}{}{Мародер из Глоу}
{2300}{}{Рыбак}
{2310}{}{Рыбачка}
{2320}{}{Дикарь}
{2330}{}{Дикарка}
{2340}{}{Самогонщик}
{2350}{}{Самогонщица}
{2360}{}{Артельщик}
{2370}{}{Артельщица}
{2380}{}{Рейдер}
{2390}{}{Рейдерша}
{2400}{}{Огнедышащий ящер}
{2410}{}{Крутой огнедышащий ящер}
{2420}{}{Инопланетянин}
{2430}{}{Чужой}
{2440}{}{Мелкий сильный Коготь Смерти}
{2450}{}{Злобный Коготь Смерти}
{2460}{}{Летатель}
{2470}{}{Подлый Летатель}
{2480}{}{Псевдо-кентавр}
{2490}{}{Кентавр Апдайка}
{2500}{}{Патрульный АНКЛАВА}
{2510}{}{Патрульная АНКЛАВА}
{2520}{}{Саботажник}
{2530}{}{Саботажница}
{2540}{}{Наемник}
{2550}{}{Наемница}
{2560}{}{Найткин}
{2570}{}{Мощный Найткин}
{2580}{}{Крутой Призрак}
{2590}{}{Мафиози}
{2600}{}{Якудза}
{2610}{}{Рейнджер НКР}
{2620}{}{Рейнджер НКР}
{2630}{}{Мародер}
{2640}{}{Мародер}
{2650}{}{Симпатяга Ллойд}
{2660}{}{Зубастый грызун}
{2670}{}{Житель 13-го}
{2680}{}{Жительница 13-го}
{2690}{}{Хранитель Моста}
{2700}{}{Таинственный незнакомец}
{2710}{}{Таинственная незнакомка}
{2720}{}{Хэйксвилл}
{2730}{}{Большой Езус Мордино}
{2740}{}{Думар}
{2741}{}{Думар, торговец браминами.}
{2750}{}{Мать Когтей Смерти}
{2760}{}{Дракон}
{2770}{}{Ло Пан}
{2780}{}{Хабологист}
{2790}{}{Хабологистка}
{2800}{}{Неопознанная личность}
{2810}{}{Неопознанная личность}
{2820}{}{Неопознанная личность}
{2830}{}{Неопознанная личность}
{2840}{}{Неопознанная личность}
{2850}{}{Неопознанная личность}
{2860}{}{Неопознанная личность}
{2870}{}{Неопознанная личность}
{2880}{}{Суперагент Президента}
{2890}{}{Яйцо Когтя Смерти}
{2900}{}{Метцгер}
{2910}{}{Гвардеец АНКЛАВА}
{2920}{}{Гвардеец АНКЛАВА}
{2930}{}{Президент}
{2940}{}{Вице-президент}
{2950}{}{Техник}
{2960}{}{Бадгер}
{2970}{}{Доктор Фанг}
{2980}{}{Дитя}
{2990}{}{Дитя}
{3000}{}{Продавец оружия}
{3010}{}{Лаборант Ши}
{3020}{}{Страж Ши}
{3030}{}{Крестьянин Ши}
{3040}{}{Крестьянка Ши}
{3050}{}{Крестьянин Ло Пана}
{3060}{}{Крестьянка Ло Пана}
{3070}{}{Докер}
{3080}{}{Торговец Ши}
{3090}{}{Пинки}
{3100}{}{Сулик - Стадия 1}
{3110}{}{Сулик - Стадия 2}
{3120}{}{Сулик - Стадия 3}
{3130}{}{Сулик - Стадия 4}
{3140}{}{Сулик - Стадия 5}
{3150}{}{Сулик - Стадия 6}
{3160}{}{Ленни - Стадия 1}
{3170}{}{Ленни - Стадия 2}
{3180}{}{Ленни - Стадия 3}
{3190}{}{Горис - Стадия 1}
{3200}{}{Горис - Стадия 2}
{3210}{}{Горис - Стадия 3}
{3220}{}{Горис - Стадия 4}
{3230}{}{Горис - Стадия 5}
{3240}{}{Горис - Стадия 6}
{3250}{}{Мирон - Стадия 1}
{3260}{}{Мирон - Стадия 2}
{3270}{}{Мирон - Стадия 3}
{3280}{}{Мирон - Стадия 4}
{3290}{}{Маркус - Стадия 1}
{3300}{}{Маркус - Стадия 2}
{3310}{}{Маркус - Стадия 3}
{3320}{}{Маркус - Стадия 4}
{3330}{}{Маркус - Стадия 5}
{3340}{}{Кибердог - Стадия 1}
{3350}{}{Кибердог - Стадия 2}
{3360}{}{Кибердог - Стадия 3}
{3370}{}{Кибердог - Стадия 4}
{3380}{}{Кэссиди - Стадия 1}
{3390}{}{Кэссиди - Стадия 2}
{3400}{}{Кэссиди - Стадия 3}
{3410}{}{Кэссиди - Стадия 4}
{3420}{}{Догмит}
{3430}{}{Догмит - Стадия 1}
{3440}{}{Догмит - Стадия 2}
{3450}{}{Догмит - Стадия 3}
{3460}{}{Догмит - Стадия 4}
{3470}{}{Догмит - Стадия 5}
{3480}{}{Догмит - Стадия 6}
{3490}{}{Робомозг - Стадия 1}
{3500}{}{Робомозг - Стадия 2}
{3510}{}{Робомозг - Стадия 3}
{3520}{}{Робомозг - Стадия 4}
{3530}{}{Робомозг - Стадия 5}
{3540}{}{Инопланетное существо}
{3550}{}{Черный Рад-скорпион}
{3560}{}{Черный Рад-скорпион}
{3570}{}{Спад}
{3580}{}{Капитан рейдеров}
{3590}{}{Рейдер}
{3600}{}{Рейдер}
{3610}{}{Тень-что-бродит}
{3620}{}{Панк}
{3630}{}{Панк}
{3640}{}{Марк}
{3650}{}{Дэйв Х.}
{3660}{}{Капитан Арон Мейерс}
{3670}{}{Чип}
{3680}{}{АХС-9}
{3690}{}{Стражник хабологистов}
{3700}{}{Стражница хабологистов}
{3710}{}{Хуан}
{3720}{}{Викки}
{3730}{}{Вик}
{3740}{}{Вик}
{3750}{}{Вик}
{3760}{}{Вик}
{3770}{}{Вик}
{3780}{}{Вик}
{3790}{}{Робомозг - Шимпанзе}
{3800}{}{Робомозг - Ненормальный}
{3810}{}{Робомозг - Человек}
{3820}{}{Муравей}
{3830}{}{Крутой муравей}
{3840}{}{Пария}
{3850}{}{Зурак}
{3860}{}{Имбот}
{3870}{}{Джимми}
{3880}{}{Вейунгх}
{3890}{}{Херб}
{3900}{}{Лупал}
{3910}{}{Джобе}
{3920}{}{Смитти}
{3930}{}{Рубе}
{3940}{}{Мастер Кралл}
{3950}{}{Зигги}
{3960}{}{Мастер Кунг}
{3970}{}{Джон Бишоп}
{3980}{}{Анжела Бишоп}
{3990}{}{Миссис Бишоп}
{4000}{}{Телохранитель}
{4010}{}{Телохранитель}
{4020}{}{Громила Бишопа}
{4030}{}{Громила Бишопа}
{4040}{}{Сердитый брамин}
{4050}{}{Малый Езус}
{4060}{}{Большой Езус}
{4070}{}{Человек Мордино}
{4080}{}{Человек Мордино}
{4090}{}{Человек Мордино}
{4100}{}{Телохранитель Мирона}
{4110}{}{Телохранитель Мирона}
{4120}{}{Мистер Врайт}
{4130}{}{Миссис Врайт}
{4140}{}{Крис Врайт}
{4150}{}{Кейт Врайт}
{4160}{}{Сын Врайта}
{4170}{}{Сын Врайта}
{4180}{}{Дочь Врайта}
{4190}{}{Дочь Врайта}
{4200}{}{Мистер Сальваторе}
{4210}{}{Мэйсон}
{4220}{}{Вышибала Сальваторе}
{4230}{}{Вышибала Сальваторе}
{4240}{}{Обычный бармен}
{4250}{}{Обычный бармен}
{4260}{}{Обычный бармен}
{4270}{}{Боксер}
{4280}{}{Боксер}
{4290}{}{Боксер}
{4300}{}{Боксер}
{4310}{}{Майк Мастикатор}
{4320}{}{Холифелд}
{4330}{}{МакКнили}
{4340}{}{Малыш Стюарт}
{4350}{}{Братья с Корсики}
{4360}{}{Порноактрисы}
{4370}{}{Отец Тулли}
{4380}{}{Вышибала Казино}
{4390}{}{Вышибала Казино}
{4400}{}{Крупье}
{4410}{}{Сутенер}
{4420}{}{Сутенер}
{4430}{}{Сутенер}
{4440}{}{Сутенер}
{4450}{}{МакГи}
{4460}{}{Мисс Китти}
{4470}{}{Обычная Шлюха}
{4480}{}{Обычная Шлюха}
{4490}{}{Джимми Джей}
{4500}{}{Ренеско}
{4510}{}{Ученый}
{4520}{}{Элдридж}
{4530}{}{Алжернон}
{4540}{}{Джулс}
{4550}{}{Бюрократ}
{4560}{}{Бюрократ}
{4570}{}{Продавец}
{4580}{}{Продавец}
{4590}{}{Охранник}
{4600}{}{Охранник}
{4610}{}{Охранник}
{4620}{}{Охранник}
{4630}{}{Солдат}
{4640}{}{Солдат}
{4650}{}{Солдат}
{4660}{}{Солдат}
{4670}{}{Сержант Старк}
{4680}{}{Доктор Эндрю}
{4690}{}{Бармен}
{4700}{}{Орудийная башня}
{4701}{}{Автоматическое оборонительное устройство, снабженное двумя плазма-пушками.}
{4710}{}{Дикая псина}
{4720}{}{Дикая псина}
{4730}{}{Дикая псина}
{4740}{}{Дикая псина}
{4750}{}{Койот}
{4760}{}{Дикая псина}
{4770}{}{Яйцо Ванаминго}
{4780}{}{Страж Ло Пана}
{4790}{}{Мэрджори}
{4800}{}{Авто-пушка}
{4810}{}{Особенный ящер}
{4820}{}{Смертушка}
{4830}{}{Фрэнк Хорриган}
{4831}{}{Суперагент и телохранитель президента}
{4840}{}{Волк}
{4850}{}{Бешеный пес}
{4860}{}{Койот}
{4870}{}{Мутировавший скорпион}
{4880}{}{Мелкий золотой ящер}
{4890}{}{Мятежник}
{4900}{}{Опасный жук}
{4910}{}{Инженер}
{4920}{}{Пехотинец Анклава}
{4930}{}{Инженер}
{4940}{}{Солдат Братства}
{4950}{}{Диверсант}
{4960}{}{Солдат Анклава}
{4970}{}{Паладин Братства}
{4980}{}{Патрульный регулятор}
{4990}{}{Бандит}
{5000}{}{Разбойница}
{5010}{}{Рейдер}
{5020}{}{Рейдер}
{5030}{}{Рейдер}
{5040}{}{Рейдер}
{5050}{}{Гигантская оса}
{5051}{}{Огромное кровожадное насекомое}
{5060}{}{Гвардеец}
{5061}{}{Боец Гвардии ГУ}
{5070}{}{Летучая мышь}
{5080}{}{Патрульный Арройо}
{5090}{}{Патрульный Арройо}
{5100}{}{Патрульный Арройо}
{5110}{}{Беглец}
{5120}{}{Беглец}
{5130}{}{Беглец}
{5140}{}{Беглец}
{5150}{}{Беглец}
{5160}{}{Илай}
{5170}{}{Чемпион}
{5180}{}{Хелацитон тип 1}
{5181}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5190}{}{Злобный хелацитон тип 1}
{5191}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5200}{}{Хелацитон тип 2}
{5201}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5210}{}{Злобный хелацитон тип 2}
{5211}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5220}{}{Хелацитон тип 3}
{5221}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5230}{}{Генриетта}
{5231}{}{Кожа этого существа напоминает одну большую мозоль.}
{5240}{}{Андроид}
{5250}{}{Тим Кейн}
{5260}{}{Шакал Карлоса}
{5270}{}{Шакал Карлоса}
{5280}{}{Бегемот}
{5281}{}{Огромный механический жук на шести лапах, оснащен крупнокалиберным пулеметом.}
{5300}{}{Охранник Джинктауна}
{5301}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{5310}{}{Охранник Джинктауна}
{5311}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{5320}{}{Рон Уинкли}
{5321}{}{Рон Уинкли, местный тюремщик.}
{5330}{}{Охранник}
{5331}{}{Охранник.}
{5340}{}{Убийца}
{5341}{}{Убийца.}
{5350}{}{Охранник Джинктауна}
{5351}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{5360}{}{Полициейский Хаба}
{5361}{}{Полициейский Хаба внимательно наблюдает за окресностями.}
{5370}{}{Полициейский Хаба}
{5371}{}{Полициейский Хаба внимательно наблюдает за окресностями.}
{5380}{}{Найткин}
{5381}{}{Сильный и агрессивный супермутант.}
{5390}{}{Найткин}
{5391}{}{Сильный супер мутант. У него, кажется, есть некоторое устройства, которое делает его не заметным.}
{5400}{}{Мутант}
{5401}{}{Супермутант. Он выглядит очень агрессивно.}
{5410}{}{Бандит}
{5420}{}{Бандит}
{5430}{}{Бандит}
{5440}{}{Бандит}
{5450}{}{Бандит}
{5460}{}{Чак Ли}
{5461}{}{Чак Ли, он тут главный.}
{5470}{}{Manequin}
{5480}{}{Manequin}
{5490}{}{Manequin}
{5500}{}{Manequin}
{5510}{}{Manequin}
{5520}{}{Manequin}
{5530}{}{Manequin}
{5540}{}{Manequin}
{5550}{}{Manequin}
{5560}{}{Manequin}
{5570}{}{Manequin}
{5580}{}{Manequin}
{5590}{}{Manequin}
{5600}{}{Manequin}
{5610}{}{Manequin}
{5620}{}{Manequin}
{5630}{}{Manequin}
{5640}{}{Manequin}
{5650}{}{Manequin}
{5660}{}{Manequin}
{5670}{}{Manequin}
{5680}{}{Manequin}
{5690}{}{Manequin}
{5700}{}{Manequin}
{5710}{}{Manequin}
{5720}{}{Manequin}
{5730}{}{Manequin}
{5740}{}{Manequin}
{5750}{}{Manequin}
{5760}{}{Manequin}
{5770}{}{Manequin}
{5780}{}{Manequin}
{5790}{}{Manequin}
{5800}{}{Manequin}
{5810}{}{Manequin}
{5820}{}{Manequin}
{5830}{}{Manequin}
{5840}{}{Manequin}
{5850}{}{Manequin}
{5860}{}{Manequin}
{5870}{}{Manequin}
{5880}{}{Manequin}
{5890}{}{Manequin}
{5900}{}{Manequin}
{5910}{}{Manequin}
{5920}{}{Manequin}
{5930}{}{Manequin}
{5940}{}{Manequin}
{5950}{}{Manequin}
{5960}{}{Manequin}
{5970}{}{Manequin}
{5980}{}{Manequin}
{5990}{}{Manequin}
{6000}{}{Manequin}
{6010}{}{Охранник Джинктауна}
{6011}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{6030}{}{Охранник Джинктауна}
{6031}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{6040}{}{Охранник Джинктауна}
{6041}{}{Серьезный охранник, он точно умеет обращаться с оружием.}
{6050}{}{Trader KLAMATH}
{6060}{}{Trader DEN}
{6070}{}{Trader REDDING}
{6080}{}{Trader MODOC}
{6090}{}{Trader GECKO}
{6100}{}{Trader VC OUT}
{6110}{}{Trader VC IN}
{6120}{}{Trader BROKEN HILLS}
{6130}{}{Trader NEW RENO}
{6140}{}{Trader SAN FRANCISCO}
{6150}{}{Trader NCR OUT}
{6160}{}{Trader NCR IN}
{6170}{}{Trader HUB}
{6180}{}{Trader BONEYARD}
{6190}{}{Doctor VC IN}
{6200}{}{Doctor VC OUT}
{6210}{}{Doctor NCR}
{6220}{}{Doctor HUB}
{6230}{}{Doctor BONEYARD}
{6240}{}{Doctor SANFRANCISCO}
{6250}{}{Doctor NEW RENO}
{6260}{}{Doctor BROKEN HILLS}
{6270}{}{Doctor REDDING}
{6280}{}{BAR SF}
{6290}{}{BAR BH}
{6300}{}{BAR BHWIFE}
{6310}{}{BAR SALVNR}
{6320}{}{BAR CASINONR}
{6330}{}{BAR GECKO}
{6340}{}{BAR VC}
{6350}{}{BAR MODOC}
{6360}{}{BAR WIFEKLAMATH}
{6370}{}{BAR DUDEKLAMATH}
{6380}{}{BAR CASINODEN}
{6390}{}{BAR DEN}
{6400}{}{BAR MOMDEN}
{6410}{}{BAR HUB}
{6420}{}{BAR JT}
{6430}{}{BAR MALAMUTREDDING}
{6440}{}{BAR COFFINREDDING}
{6450}{}{BAR NCROUT}
{6460}{}{BAR NCRIN}
{6470}{}{SFTANK GUNS}
{6480}{}{SFTANK ARMOR}
{6490}{}{BALDCHINA}
{6500}{}{BH CARAVANDUDE}
{6510}{}{BH HUSBAND}
{6520}{}{NEWR ARMS}
{6530}{}{GECKO SKEET}
{6540}{}{GECKO SHERIFF}
{6550}{}{VC A ARMOR}
{6560}{}{VC B WEAPON}
{6570}{}{MODOC TANNER}
{6580}{}{MODOC WILLY}
{6590}{}{DEN SECOND}
{6600}{}{HUB JACOB}
{6610}{}{HUB GUNS}
{6620}{}{BONE GUNRUNNERS}
{6630}{}{Мать Когтей Смерти}
{6631}{}{Срань. Лучше уносить отсюда ноги!}
{6640}{}{Коготь Смерти}
{7000}{}{Бандит}
{7010}{}{Бандит}
{7020}{}{Бандит}
{7030}{}{Бандит}
{7040}{}{Бандит}
{7050}{}{Бандит}
{7060}{}{Бандит}
{7070}{}{Грабитель}
{7080}{}{Грабитель}
{7090}{}{Грабитель}
{7100}{}{Грабитель}
{7110}{}{Грабитель}
{7120}{}{Грабитель}
{7130}{}{Самогонщик}
{7140}{}{Самогонщик}
{7150}{}{Самогонщик}
{7160}{}{Самогонщик}
{7170}{}{Бандит}
{7180}{}{Бандит}
{7190}{}{Бандит}
{7200}{}{Бандит}
{7210}{}{Бандит}
{7220}{}{Бандит}
{7230}{}{Самогонщик}
{7240}{}{Самогонщик}
{7250}{}{Самогонщик}
{7260}{}{Самогонщик}
{7270}{}{Самогонщик}
{7280}{}{Самогонщик}
{7290}{}{Мародер}
{7300}{}{Мародер}
{7310}{}{Мародер}
{7320}{}{Мародер}
{7330}{}{Мародер}
{7340}{}{Мародер}
{7350}{}{Рейдер}
{7360}{}{Рейдер}
{7370}{}{Рейдер}
{7380}{}{Рейдер}
{7390}{}{Рейдер}
{7400}{}{Рейдер}
{7410}{}{Гуль}
{7420}{}{Гуль}
{7430}{}{Гуль}
{7440}{}{Гуль}
{7450}{}{Гуль}
{7460}{}{Панк}
{7470}{}{Панк}
{7480}{}{Панк}
{7490}{}{Панк}
{7500}{}{Панк}
{7510}{}{Потрошитель}
{7520}{}{Потрошитель}
{7530}{}{Потрошитель}
{7540}{}{Потрошитель}
{7550}{}{Потрошитель}
{7560}{}{Рейдер}
{7570}{}{Рейдер}
{7580}{}{Рейдер}
{7590}{}{Рейдер}
{7600}{}{Рейдер}
{7610}{}{Стрелок}
{7620}{}{Шиза}
{7630}{}{Задира}
{7640}{}{Гун}
{7650}{}{Гангстер}
{7660}{}{Разбойник}
{7670}{}{Разбойник}
{7680}{}{Разбойник}
{7690}{}{Разбойник}
{7700}{}{Разбойник}
{7710}{}{Злая сука}
{7720}{}{Сумасшедший}
{7730}{}{Сумасшедший}
{7740}{}{Уродливый мешок}
{7750}{}{Сволочь}
{7760}{}{Наемник}
{7770}{}{Наемник}
{7780}{}{Наемник}
{7790}{}{Наемник}
{7800}{}{Наемник}
{7810}{}{Гуль}
{7820}{}{Регулятор}
{7830}{}{Регулятор}
{7840}{}{Регулятор}
{7850}{}{Регулятор}
{7860}{}{Ханский Рейдер}
{7870}{}{Ханский Рейдер}
{7880}{}{Ханский Рейдер}
{7890}{}{Ханский Рейдер}
{7900}{}{Ханский Рейдер}
{7910}{}{Жулик}
{7920}{}{Жулик}
{7930}{}{Жулик}
{7940}{}{Жулик}
{7950}{}{Жулик}
{7960}{}{Рекрут Анклава}
{7970}{}{Солдат Анклава}
{7980}{}{Солдат Анклава}
{7990}{}{Боец-Ветеран Анклава}
{8000}{}{Боец-Ветеран Анклава}
{8010}{}{Мутант}
{8020}{}{Супермутант}
{8030}{}{Супермутант}
{8040}{}{Найткин}
{8050}{}{Найткин}
{8060}{}{Гуль}
{8070}{}{Гуль}
{8080}{}{Гуль}
{8090}{}{Гуль}
{8100}{}{Гуль}
{8110}{}{Гуль}
{8120}{}{Гуль}
{8130}{}{Гуль}
{8140}{}{Гуль}
{8150}{}{Гуль}
{8160}{}{Гуль}
{8170}{}{Рекрут Анклава}
{8180}{}{Солдат Анклава}
{8190}{}{Солдат Анклава}
{8200}{}{Боец-Ветеран Анклава}
{8210}{}{Рекрут Братства}
{8220}{}{Солдат Братства}
{8230}{}{Солдат Братства}
{8240}{}{Паладин Братства}
{8250}{}{Мерзость}
{8260}{}{Чудовище}
{8270}{}{Пещерная крыса}
{8280}{}{Мутировааший крысокабан}
{8290}{}{Мутировавший крот-гризли}
{8300}{}{Жесть}
{8301}{}{Злой, умник.. разговаривать бесполезно.}
{8310}{}{Робомозг}
{8320}{}{Летучий глаз}
{8330}{}{Гуль охранник}
{8340}{}{Зет}
{8350}{}{Ханский Рейдер}
{8360}{}{Ханский Рейдер}
{8370}{}{Ханский Рейдер}
{8380}{}{Ханский Рейдер}
{8390}{}{Ханский Рейдер}
{8400}{}{Патрульный Джанктауна}
{8410}{}{Патрульный Джанктауна}
{8420}{}{Патрульный Джанктауна}
{8430}{}{Патрульный Джанктауна}
{8440}{}{Патрульный Джанктауна}
{8450}{}{Охранник}
{8460}{}{Охранник}
{8470}{}{Охранник}
{8480}{}{Охранник}
{8490}{}{Торговец}
{8500}{}{Бандит}
{8510}{}{Бандит}
{8520}{}{Бандит}
{8530}{}{Бандит}
{8540}{}{Бандит}
{8550}{}{Бандит}
{8560}{}{Грабитель}
{8570}{}{Грабитель}
{8580}{}{Грабитель}
{8590}{}{Грабитель}
{8600}{}{Грабитель}
{8610}{}{Грабитель}
{8620}{}{Лидер каравана}
{8630}{}{Охранник каравана}
{8640}{}{Охранник каравана}
{8650}{}{Охранник каравана}
{8660}{}{Охранник каравана}
{8670}{}{Охранник каравана}
{8680}{}{Охранник каравана}
{8690}{}{Охранник каравана}
{8700}{}{Охранник каравана}
{8710}{}{Brotherhood Initiate}
{8720}{}{Brotherhood Knight}
{8730}{}{Brotherhood Knight}
{8740}{}{Brotherhood Paladin}
{8750}{}{Brotherhood Paladin}
{8760}{}{Охранник Хаба}
{8770}{}{Охранник Хаба}
{8780}{}{Охранник Хаба}
{8790}{}{Охранник Хаба}
{8800}{}{Охранник Хаба}
{8810}{}{Охранник Города Убежища}
{8820}{}{Охранник Города Убежища}
{8830}{}{Охранник Города Убежища}
{8840}{}{Охранник Города Убежища}
{8850}{}{Охранник Города Убежища}
{8860}{}{Гуль}
{8870}{}{Гуль}
{8880}{}{Гуль}
{8890}{}{Гуль}
{8900}{}{Гуль}
{8910}{}{Лезвие}
{8920}{}{Лезвие}
{8930}{}{Лезвие}
{8940}{}{Лезвие}
{8950}{}{Лезвие}
{8960}{}{Патруль Единства}
{8970}{}{Патруль Единства}
{8980}{}{Патруль Единства}
{8990}{}{Рейнджер НКР}
{9000}{}{Рейнджер НКР}
{9010}{}{Рейнджер НКР}
{9020}{}{Солдат НКР}
{9030}{}{Рекрут НКР}
{9040}{}{Лидер каравана}
{9050}{}{Охранник каравана}
{9060}{}{Охранник каравана}
{9070}{}{Охранник каравана}
{9080}{}{Охранник каравана}
{9090}{}{Охранник каравана}
{9100}{}{Охранник каравана}
{9110}{}{Охранник каравана}
{9120}{}{Охранник каравана}
{9130}{}{Фермер}
{9140}{}{Фермер}
{9150}{}{Фермер}
{9160}{}{Фермер}
{9170}{}{Ребенок}
{9180}{}{Крестьянин}
{9190}{}{Крестьянин}
{9200}{}{Крестьянин}
{9210}{}{Крестьянин}
{9220}{}{Ребенок}
{9230}{}{Крестьянин}
{9240}{}{Мусорщик}
{9250}{}{Мусорщик}
{9260}{}{Мусорщик}
{9270}{}{Мусорщик}
{9280}{}{Мусорщик}
{9290}{}{Бродяга}
{9300}{}{Бродяга}
{9310}{}{Бродяга}
{9320}{}{Бродяга}
{9330}{}{Траппер}
{9340}{}{Траппер}
{9350}{}{Траппер}
{9360}{}{Охотник}
{9370}{}{Охотник}
{9380}{}{Охотник}
{9390}{}{Артельщик}
{9400}{}{Артельщик}
{9410}{}{Артельщик}
{9420}{}{Переселенец}
{9430}{}{Переселенец}
{9440}{}{Переселенец}
{9450}{}{Переселенец}
{9460}{}{Хаболог}
{9470}{}{Хаболог}
{9480}{}{Хаболог}
{9490}{}{Хаболог}
{9500}{}{Хаболог}
{9510}{}{Чупакабра}
{9511}{}{Бежиииим!}
{9520}{}{Аберрация}
{9530}{}{Начальник патруля}
{9540}{}{Вэйн}
{9550}{}{Разведчик Джанктауна}
{9560}{}{Разведчик Джанктауна}
{9570}{}{Разведчик Джанктауна}
{9580}{}{Разведчик Джанктауна}
{9590}{}{Разведчик Джанктауна}
{9600}{}{Найткин}
{9610}{}{Подозрительный человек}
{9620}{}{Головорез Бишопа}
{9630}{}{Головорез Бишопа}
{9640}{}{Головорез Бишопа}
{9650}{}{Головорез Бишопа}
{9660}{}{Сын Райта}
{9670}{}{Сын Райта}
{9680}{}{Сын Райта}
{9690}{}{Сын Райта}
{9700}{}{Командир}
{9710}{}{26}
{9720}{}{31}
{9730}{}{40}
{9740}{}{41}
{9750}{}{43}
{9760}{}{44}
{9770}{}{45}
{9780}{}{48}
{9790}{}{56}
{9800}{}{57}
{9810}{}{62}
{9820}{}{64}
{9830}{}{72}
{9840}{}{77}
{9850}{}{78}
{9860}{}{82}
{9870}{}{87}
{9880}{}{88}
{9890}{}{Химик}
{9900}{}{91}
{9910}{}{92}
{9920}{}{93}
{9930}{}{95}
{9940}{}{96}
{9950}{}{98}
{9960}{}{105}
{9970}{}{110}
{9980}{}{135}
{9990}{}{136}
{10000}{}{137}
{10010}{}{139}
{10020}{}{140}
{10030}{}{33}
{10040}{}{34}
{10050}{}{35}
{10060}{}{36}
{10070}{}{37}
{10080}{}{61}
{10090}{}{73}
{10100}{}{94}
{10110}{}{145}
{10120}{}{146}
{10130}{}{148}
{10140}{}{149}
{10150}{}{Мусорщик}
{10160}{}{Токсичный ящер}
{10170}{}{Матерый токсичный ящер}
{10180}{}{Маленький Радиактивный ящер}
{10190}{}{Радиактивный ящер}
{10200}{}{Мощный радиактивный ящер}
{10210}{}{Кошмар}
{10220}{}{Смертоносный}
{10230}{}{Начальник каравана}
{10240}{}{Выходец из Убежища}
{10250}{}{Лидер племени}
{11200}{}{Мужчина}
{11210}{}{Женщина}
{14000}{}{Яйцо рад-скорпиона}
{14010}{}{Яйцо муравья}
{14020}{}{Яйцо ящера}
{14030}{}{Яйцо когтесмерта}
{14040}{}{Яйцо пришельца}
{14050}{}{Яйцо Псевдо-кентавр}