# 22.06.2013 Fonline2 Team

#
#
#

{4}{}{%d. }
{5}{}{Текущее состояние: }
{6}{}{@lex questName@^@lex questTask@}
{7}{}{@lex Title@^@lex Message@^@lex File@^@lex TitleColor@^@lex MessageColor@}

#
# ID
# Quest name
#

#
# Formulas are:
#	ID * 1000 + %exp%. (1-100) - Text player sees with quest var equal to %exp%.
#	ID * 1000 + 101 - Quest tab name.
#	ID * 1000 + 102 - Overall quest description.

# 7000
# Caravan from Hub to VC
{7000001}{}{Вы нанялись в охрану каравана. Хозяин каравана сказал быть готовым к 10:00.}
{7000002}{}{Итак караван отправляется. Задача очень проста - охранять караван любой ценой.}
{7000003}{}{Провал: Похоже это была не очень удачная идея.}
{7000004}{}{Провал: Вы бросили караван.}
{7000005}{}{Провал: Вы умерли.}
{7000006}{}{Провал: Хозяин каравана погиб.}
{7000007}{}{Провал: Вы убили хозяина каравана. Похоже не видать вам больше этой работы.}
{7000008}{}{Выполнено: Наконец-то добрались до места назначения. Самое время получить мое вознаграждение.}
{7000009}{}{Караван отправляется. Задача, как всегда, очень проста - охранять караван любой ценой.}
{7000010}{}{Выполнено: Наконец-то добрались до места назначения. Самое время получить мое вознаграждение.}
{7000011}{}{Караван успешно добрался доместа назначения.}


# 9001 - My first tent
{9001001}{}{Поговорите с местным погонщиком браминов.}
{9001002}{}{Скорее всего у Мельсака найдется пара шкур для палатки.}
{9001003}{}{В обмен на шкуры Мельсак попросил забрать 10 мешков для воды у Фрэнки.}
{9001004}{}{Фрэнки дал всего 4 мешка для воды. Пора идти к Мельсаку.}
{9001005}{}{Вы убили одного из браминов Фрэнки. Фрэнки обязательно сообщит об этом Мельсаку.}
{9001006}{}{Вы услышали какой то странный звук неподалеку, как раз перед тем как Фрэнки испустил последний вздох. Надеюсь свидетелей все же не было.}
{9001007}{}{Мельсак попросил принести шило. чтобы сделать недостающие мешки для воды самому. Надо поискать у местных торговцев.}
{9001008}{}{Выполнено: Мельсак выдал мне 10 шкур брамина, как раз то, что надо для первой палатки.}
{9001009}{}{Провал: Из-за ваших действий Мельсак передумал помогать в поисках шкур для палатки.}
{9001101}{}{Джанктаун}
{9001102}{}{Моя первая палатка}

# 9002 - Melsak's revenge
{9002001}{}{Мельсак рассказал о своей деревне и лидере работорговцев, более известном как "Убийца". Поговорите с ним об этом позже.}
{9002002}{}{Найдите Лиану в Кламате, она должна знать, где искать "Убийцу".}
{9002005}{}{Один из местных дикарей видел работорговцев из Дена, говорящих с Лианой пару дней тому назад.}
{9002006}{}{По словам Метцегера Лианы уже нет в Дене. Стоит продолжить ее поиски.}
{9002007}{}{Метцеер готов показать вам местоположение лагеря за 5000 капсов. Придется заплатить или искать другой способ его найти.}
{9002008}{}{Метцегер показал вам местоположение лагеря работорговцев, в котором содержится Лиана.}
{9002009}{}{Один из охранников показал вам местоположение лагеря работорговцев, в котором содержится Лиана.}
{9002010}{}{Один из дикарей местоположение лагеря работорговцев, в котором возможно содержится Лиана.}
{9002011}{}{Вы освободили Лиану из лап работорговцев.}
{9002012}{}{"Убийца" скрывается где-то на северо-западном побережье. Исследуйте местность и попытайтесь его найти.}
{9002013}{}{Вы нашли место, где похоже скрывается "Убийца".}
{9002014}{}{"Убийца" мертв. Возвращайтесь к Мельсаку.}
{9002015}{}{Провал: Слишком поздно, скорее всего Лиана уже мертва.}
{9002016}{}{Провал: Слишком поздно, "Убийца уже покинул свой лагерь.}
{9002017}{}{Выполнено: В конце концов, Мельсак теперь отомщен.}
{9002101}{}{Джанктаун}
{9002102}{}{Месть Мельсака}

# 9004 - Dude ... Where is my tool!?!
{9004001}{}{Пит попросил принести ему новый набор инструментов. Вы не совсем представляете, что же он имел ввиду.}
{9004002}{}{Вы принесли Питу Суперремнабор и он взамен обучил вас азам ремонта.}
{9004003}{}{Вы принесли Питу Суперремнабор, ему очень жаль но не может обучить вас ремонту, вы итак знаете достаточно.}
{9004101}{}{Джанктаун}
{9004102}{}{Инструменты}

# 9005 - Broken delivery
{9005001}{}{Мэриэн хочет, чтобы вы доставили аудиомагнитофон Бенджами, бармену в Скам Питт.}
{9005002}{}{Выполнено: Аудиомагнитофон успешно доставлен Бенджами, в благодарность он угостил вас парой бутылочек пива.}
{9005101}{}{Джанктаун}
{9005102}{}{Сорванная доставка}

# 9007 - It's complicated
{9007001}{}{Слишком застенчивый Майк попросил вас пойти к Мэриэн и разузнать, сможет ли она пойти с ним на свидание.}
{9007002}{}{Ваши безуспешные попытки наладить личную жизнь Майка не увенчались успехом. Возвращайтесь к Майку и сообщите о ее отказе.}
{9007003}{}{Мэриэн согласилась пойти на свидание с Майком, пора сообщить бедолаге хорошие новости.}
{9007004}{}{Вы хорошо провели время с Мэриэн, но она все же оказалась непрочь пойти на свидание с Майком (шлюха))) Самое время сообщить Майку.}
{9007005}{}{Выполнено: Майк похоже не слишком расстроился из-за отказа Мэриэн, чтож попытка не пытка.}
{9007006}{}{Выполнено: Вы успешно организовали свидание Майку и Мэриэн, похоже теперь все зависит только от него.}
{9007007}{}{Выполнено: Майк никак не может поверить, что вы так легко нашли с Мэриэн общий язык. чтож пускай и дальше живет в своем воображаемом мире.}
{9007101}{}{Джанктаун}
{9007102}{}{Слишком запутанно}

# 9008 - Electronic revolution
{9008001}{}{Вы спросили Мэиэн о том, над чем она сейчас работает, и она заметила, что ей не помещают несколько электронных частей. Принесите ей как минимум 5.}
{9008002}{}{Похоже электронные части, которые вы принесли, вполне подходят. Не забудьте по возможности принести еще через некоторое время.}
{9008101}{}{Джанктаун}
{9008102}{}{Электронная революция}

# 9010 - Purify
{9010001}{}{После трогательной истории, произошедшей в жизни Бенджами, он попросил предложить проститутке Кайли работу официантки.}
{9010002}{}{После разговора с вами Кайли согласилась работать на Бенджами при условии, что вы одолжите ей 400 капсов.}
{9010003}{}{Бенджами поблагодарил вас за беспокойство и угостил выпивкой. Поговорите с Кайли позже, если хотите вернуть свои деньги.}
{9010004}{}{Кайли была очень рада тому, что вы одолжили ей денег. Через некоторое время она собирается поговорить с Бенджами о деталя, и просит сообщить ему хорошую новость прямо сейчас.}
{9010005}{}{Когда вы пытаетесь поговорить с Кайли о возврате ее долга, Кайли вас игнорирует. Разговор со шерифом или Бенджами возможно поможет разобраться в ситуации.}
{9010006}{}{Майк проговорился о том, что Кайли работает на него. Попробуйте надавить на нее еще раз.}
{9010007}{}{Кайли напугана тем, что вам стало известно о ее работе на Майка. Она внезапно поменяла свое отношение и попросила сказать Бенджами, что все кончено.}
{9010008}{}{Выполнено: Бенджами признался, что он пытался навариться на вас и вернул деньги.}
{9010101}{}{Джанктаун}
{9010102}{}{Раскаяние}

# 9013 - King of the junk
{9013001}{}{Питу нужен мусор, чтобы поддерживать насос в рабочем состоянии. Принесите ему 5 мусора.}
{9013002}{}{Пит остался доволен мусором, который вы ему принесли. Через некоторое время ему понадобится еще мусор.}
{9013101}{}{Джанктаун}
{9013102}{}{Король мусора!}

# 9015 - Be cool
{9015001}{}{Маргарет недовольна нежеланием Пита починить ее холодильник. Она попросила вас сходить и напомнить ему об этом.}
{9015002}{}{Пит пообещал починить холодильник в ближайшее время. Возвращайтесь к Маргарет и сообщите ей хорошие новости.}
{9015003}{}{Выполнено: Хотя Пит лишь снова наобещал с три короба, в благодарность за вашу помощь Маргарет бесплатно выделила вам свободную комнату на 3 дня.}
{9015101}{}{Джанктаун}
{9015102}{}{Разморозка}

# 9017 - Zach's scorpion tails
{9017001}{}{Зач предложил вам непыльную работенку. Принесите ему 5 хвостов радскорпионов и он вас обязательно отблагодарит.}
{9017002}{}{Зача вполне устроило качество хвостов, что вы принесли, через некоторое время понадобятся еще.}
{9017101}{}{Джанктаун}
{9017102}{}{Хвосты скорпиона для Зача}

# 9019 - Kylee's condition
{9019001}{}{Доктор Зачариус попросил вас помочь с поисками валидола для Кайли.}
{9019002}{}{Выполнено: Лекарство, что вы принесли, вполне подходит.}
{9019101}{}{Джанктаун}
{9019102}{}{Самочувствие Кайли}

# 9020 - Thirst of the west
{9020001}{}{Джо мучает ужасная жажда. Принесите ему наполненный мешок с водой.}
{9020002}{}{Джо выпил все одним глотком. Чуть позже его наверняка опять будет мучить жажда.}
{9020003}{}{Джо снова мучается от жажды. Принесите ему наполненный мешок с водой.}
{9020101}{}{Джанктаун}
{9020102}{}{Жажда}

# 9021 - Aldo's medicine
{9021001}{}{Альдо очень "болеет". Принесите немного его любимого лекарства, чтоб поправить здоровье.}
{9021002}{}{Альдо употребил все "лекарство" за считанные секунды. Такими темпами он явно скоро снова "заболеет".}
{9021101}{}{Кламат}
{9021102}{}{С утра выпил, весь день свободен.}

# 9023 - Bob's booze run
{9023001}{}{Виски Боб попросил вас отправиться в Ден и найти там владельца бара "Дыра" по имени Фрэнки.Надо напомнить ему про последнюю партию спиртного и обещании заплатить двойную цену.}
{9023002}{}{Фрэнки сделал вид, что ничего об этом не слышал и отказался платить двойную цену. Возвращайтесь обратно к Виски Бобу.}
{9023003}{}{Боб вовсе не удивился реакции Фрэнки. В скором времени ему снова понадобиться курьер в Ден.}
{9023101}{}{Кламат}
{9023102}{}{Курьерская доставка Боба}

# 9025 - Maida's gecko skins
{9025001}{}{Майда просит вас принести 4 шкурки золотых гекко.}
{9025002}{}{Вы принесли Майде шкурки гекко. Чуть позже ей понадобятся еще шкурки.}
{9025101}{}{Кламат}
{9025102}{}{Шкурки золотых гекко для Майды.}

# 9027 - Brahmin shortage
{9027001}{}{Кожевнику модока нужны регулярные поставки браминьих шкур. Кожевник Ли Балтон просит раздобыть ему хотя бы 10 шкур.}
{9027002}{}{В благодарность за принесенные шкуры Ли смастерил вам улучшенную кожанную броню. Для работы кожевенной мастерской в скором времени понадобятся еще шкуры.}
{9027003}{}{В благодарность за принесенные шкуры Ли смастерил вам улучшенную кожанную броню. Для работы кожевенной мастерской в скором времени понадобятся еще шкуры.}
{9027101}{}{Модок}
{9027102}{}{Дефицит браминов}

# 9031 - Gunsmith profession
{9031001}{}{Эдвард из Хаба согласился поделиться своими умениями в создании простейшего огнестрельного оружия в обмен на 2000 капсов и кусок Высококачественной стали.}
{9031002}{}{Выполнено: Вы обучились профессии "Огнестрельное оружие" первого уровня.}
{9031003}{}{Эдвард посоветовал вам отправиться в Брокен Хиллс, чтобы повысить свои профессиональные навыки.}
{9031004}{}{Похоже что Нейл, главный торговец Брокен Хиллс, как раз тот кто надо для продвижения в вашей профессии. В обмен на обучение он хочет 4000 капсов.}
{9031005}{}{Выполнено: Вы обучились профессии "Огнестрельное оружие" 2 уровня.}
{9031006}{}{Нейл направил вас в Нью Рено на поиски старика по имени Алженон. Он настоящий специалист в оружейном деле.}
{9031007}{}{Алженон пообещал обучить вас всему, что он умеет при условии, что вы принесете ему образец экспериментальной винтовки XL70E3 и 6000 капсов.}
{9031008}{}{Выполнено: Вы обучились профессии "Огнестрельное оружие" 3 уровня, похоже теперь вы настоящий специалист во всем, что касается огнестрельного оружия.}
{9031101}{}{Хаб}
{9031102}{}{Профессия: "Огнестрельное оружие"}

# 9032 - Armorer profession
{9032001}{}{Джим из Джанктауна может научить вас мастерить простейшую броню в обмен на журнал "Кошачья лапка", 6 бутылок пива и 2000 капсов.}
{9032002}{}{Выполнено: вы обучились профессии "Бронезащита" первого уровня.}
{9032003}{}{Джим посоветовал обратиться к кожевнику в Модоке, если вы хотите улучшить свои навыки.}
{9032004}{}{Ли Балтон из Модока может научить вас создавать улучшенные виды брони. Для того чтобы убедить его поделиться своими знаниями ему придется принести комплект Боевой брони, 4 части кевлавровых полимеров и 4000 капсов.}
{9032005}{}{Выполнено: Вы обучились профессии "Бронезащита" 2 уровня.}
{9032006}{}{По мнению Ли Сан-Франциско отличное место для того, кто хочет обучиться созданию высокотехнологичных видов брони.}
{9032007}{}{Бак, бывший инженер, живущий в Сан-Франциско, готов поделиться своими знаниями в обмен на 6000 капсов.}
{9032008}{}{Выполнено: Вы обучились профессии "Бронезащита" третьего уровня.}
{9032101}{}{Джанктаун}
{9032102}{}{Профессия: "Бронезащита"}

# 9033 - Chemist profession
{9033001}{}{Доктор Оеткер из Ваулт Сити может научить вас азам химии в обмен на 12 минералов, 10 Химических кмпонентов и 2000 капсов.}
{9033002}{}{Выполнено: Вы обучились профессии "Химия" 1 уровня.}
{9033003}{}{Оеткер в восторженых тонах отзывался о Докторе Фунге как о химике намного более опытном чем он.}
{9033004}{}{Доктор Фунг, живущий в Сан-Франциско, согласен обучить вас чему-нибудь новому в химии в обмен на суперстимпак, Рад-эвэй, Рад-икс и 4000 капсов.}
{9033005}{}{Выполнено: Вы обучились профессии "Химия" 2 уровня.}
{9033006}{}{Человек по имени Ренеско из Нью-Рено вполне мог бы вывести ваши знания в химии на новый уровень.}
{9033008}{}{Выполнено: Вы обучились профессии "Химия" 3 уровня. Похоже для вас больше нет темных пятен в химии.}
{9033101}{}{Ваулт Сити}
{9033102}{}{Профессия: Химик}

# 9034 - Scientist profession
{9034001}{}{Эмброуз, библиотекарь из Бониярда, готова научить вас создавать энергетическое оружие в обмен на 12 электронных частей, 1 лазерный пистолет, 1 энергетический трансформатор и 2000 капсов.}
{9034002}{}{Выполнено: Вы обучились профессии "Ученый" 1 уровня.}
{9034003}{}{Эмброуз направила вас в Реддинг на поиски кого-то по имени Лукас.}
{9034004}{}{Лукас из Реддинга согласен обучить вас созданию продвинутых видов энергетического оружия при условии что вы добудете ему: 1 лазерную винтовку, 2 энергетических трансформатора, 12 химических компонентов и 4000 капсов.}
{9034005}{}{Выполнено: Вы обучились профессии "Ученый" 2 уровня.}
{9034006}{}{Лукас рассказал вам о знаменитом ученом из Сан-Франциско по имени Альберто Унпьедро и посоветовал отправиться на его поиски.}
{9034007}{}{Альберто Унпьедро из Сан-Франциско научит вас новейшему слову в энергетическом оружии в обмен на 1 лазерную винтовку и 6000 капсов.}
{9034008}{}{Выполнено: Вы обучились профессии "Ученый" 3 уровня.}
{9034101}{}{Бониярд}
{9034102}{}{Профессия: Ученый}

# 9102 - Dan's delivery
{9102001}{}{Дэн, человек из Хаба, нанял вас в качестве курьера. Необходимо доставить посылку помощнику шерифа Адаму, и ни при каких условиях не открывать ее.}
{9102002}{}{Посылка успешно доставлена Адаму, упаковка не повреждена. Пора возвращаться к Дэну, рассказать о исполненом поручении.}
{9102003}{}{Выполнено: Посылка доставлена без происшествий.}
{9102101}{}{Хаб}
{9102102}{}{Посылка от Дэна}

# 9104 - Get some beer for Adam!
{9104001}{}{Адам мучается от жажды под пост-ядерным солнышком. Пара бутылочек пивка бы не помешали.}
{9104002}{}{Выполнено: Вы спасли Адама от смертельной жажды, в благодарность он с удовольствием подеился местными сплетнями.}
{9104101}{}{Хаб}
{9104102}{}{Раздобыть пивка для Адама!}

# 9105 - Is there a doctor in the house?
{9105001}{}{Бледный вид кристофера заставляет задуматься о его здоровье, ему срочно необходимо принять лекарства. Отправляйтесь к местному доктору по имени Энни, она знает что делать.}
{9105002}{}{Энни выдала вам нужные лекарства. Стоит поторопиться и найти Кристофера как можно скорей, что-то он совсем плохо выглядел.}
{9105003}{}{Выполнено: Вы практически вытащили Кристофера с того света.}
{9105101}{}{Хаб}
{9105102}{}{Врача! Срочно вызовите врача!}

# 9116 - Iguana treat
{9116001}{}{Игуана Боб попросил вас доставить пакет шерифу Чарльзу.}
{9116002}{}{Чарльз радовался как ребенок, получив бесплатный шашлык из игуаны от Боба. Возвращайтесь и расскажите ему об этом.}
{9116003}{}{Вы выполнили просьбу Игуаны Боба, получив в награду немножко наличных и шашлык из игуаны. похоже у Боба есть еще какое-то дело к вам.}
{9116004}{}{Игуана Боб показал вам новый напиток - Нью кока-колу. Поставка ингридиентов задерживается, поэтому Боб попросил вас принести ему 10 фруктов в обмен на хорошее вознаграждение.}
{9116005}{}{Выполнено: Вы доставили Бобу 10 фруктов. Теперь он таки сможет варить свою содовую.}
{9116101}{}{Хаб}
{9116102}{}{Угощения от Игуаны Боба}

# 9300 - Waterpump
{9300001}{}{Вы наполнили мешок для воды.}
{9300002}{}{У вас нет мешка, чтобы наполнить его водой.}

# 9301 - Fridge
{9301001}{}{Вам удалось починить холодильник.}
{9301002}{}{Похоже это слишком сложно для вас, может поискать инструменты.}

# 9311 - Caravaneer's secret
{9311001}{}{Кенни попросил вас выяснить, что случилось с караваном, который он никак не может дождаться. Следует поискать его где-то к востоку от Хаба.}
{9311002}{}{Вы выяснили, что на караван кто-то напал. У одного из нападавших был голодиск, стоит показать его Кенни.}
{9311003}{}{Кенни осавил вам свою палатку и ушел. С его слов в Ваулт Сити есть человек, способный расшифровать запись.}
{9311004}{}{Билл, компьютерный техник из Ваулт Сити, согласился расшифровать запись для вас в обмен на радио.}
{9311005}{}{Билл расшифровал запись, вот только его содержание все еще непонятно. Билл предположил, что главный компьютер в Убежище вполне мог бы с этим помочь. Осталось получить разрешение консула Маклюра на вход в само Убежище.}
{9311006}{}{Вы расшифровали данные на диске. Исследуйте место, упомянутое в послании.}
{9311007}{}{Вы обнаружили планы буровой вышки у умирающего главаря местных рейдеров. Нужно как можно быстрей доставить их на указанное место назначения и получить ваше вознаграждение.}
{9311008}{}{Выполнено: Вы передали планы буровой вышки патрульным анклава и получили свою награду.}
{9311009}{}{Выполнено: Вы передали планы буровой вышки патрульным анклава и получили свою награду.}
{9311010}{}{Выполнено: Вы передали планы буровой вышки Кенни и получили свою награду}
{9311101}{}{Торговец Кенни}
{9311102}{}{Секрет пропавшего каравана}

# 9312 - Radscorpion cave
{9312001}{}{Кенни спас вам жизнь, теперь вы обязаны ему помочь и выполнить его просьбу убив радскорпионов в соседней пещере. Принесите ему клешни самого большого из них в доказательство.}
{9312002}{}{Выполнено: You've cleaned the cave and gave claw to Kenny.}
{9312101}{}{Торговец Кенни}
{9312102}{}{Пещера радскорпионов}

# 9313 - That's all for your health
{9313001}{}{Если вам доведется найти немного сырных крекеров, принесите их Биллу. Он готов хорошенько заплатить за каждую принесенную пачку его обожаемых крекеров.}
{9313101}{}{Ваулт Сити}
{9313102}{}{Сыыыыр!}

# 9314 - Artifacts of the Ancient Order
{9314001}{}{Если вы когда-нибудь окажетесь в Глоу и найдете карточки доступа, отдайте их Джошуа. Похоже он коллекционирует всякий хлам и вознаградит вас сполна.}
{9314101}{}{Яма}
{9314102}{}{Артефакты прошлого}

# 9316 - Subversive Citizen
{9316001}{}{Один из граждан, Найджел, открыто критикует политику правительства. Вас попросили убедить его остановиться. Обычно его можно встретить где-то в парке Ваулт Сити.}
{9316002}{}{Вы попытались заговорить с Найджелом, но он вас проигнорировал, может стоит попробовать поискать к нему другой подход.}
{9316003}{}{Вы выслушали некоторые из претензий Найджела к правительству города, но вскоре он разозлился  потерял всякий интерес к продолжению вашего разговора. Возвращайтесь к МакКлюру.}
{9316004}{}{Вы выслушали некоторые из претензий Найджела к правительству города, но вскоре он разозлился  потерял всякий интерес к продолжению вашего разговора. Возвращайтесь к МакКлюру.}
{9316005}{}{Вы выслушали некоторые из претензий Найджела к правительству города, но вскоре он разозлился  потерял всякий интерес к продолжению вашего разговора. Возвращайтесь к МакКлюру.}
{9316006}{}{Вы выслушали некоторые из претензий Найджела к правительству города, но вскоре он разозлился  потерял всякий интерес к продолжению вашего разговора. Возвращайтесь к МакКлюру.}
{9316007}{}{Похоже вам удалось убедить Найджела прекратить его подрывную деятельность. Возвращайтесь и расскажите МакКлюру о вашем успехе.}
{9316008}{}{Теперь вы разделяете взгляды Найджела на политику города. Возвращайтесь к МакКлюру и попробуйте убедить его в своей правоте.}
{9316009}{}{Выполнено: Хотя вам не удалось убедить Найджела прекратить его подрывную деятельностьs, вам удалось выяснитьпричину, по которой он так расстроен. Возвращайтеь к МакКлюру и расскажите ему об этом.}
{9316010}{}{Выполнено: Вам удалось убедить Найджела прекратить его подрывную деяельность. Консул МакКлюр очень доволен.}
{9316011}{}{Выполнено: вам удалось убедить Макклюра в разумности доводов Найджела. Похоже в Ваулт Сити наступит время реформ.}
{9316101}{}{Ваулт Сити}
{9316102}{}{Подрывной элемент}

# 9317 - Well, well, well...
{9317001}{}{В адитуме сломан колодец. Пестис попросил вас починить его.}
{9317002}{}{Теперь колодец исправен. Возвращайтесь к Пестису.}
{9317003}{}{Узнайте, почему пересох колодец.}
{9317004}{}{вы прикрепили веревку к колодцу. Самое время спуститься вниз.}
{9317005}{}{Похоже кто-то качает воду налево. Поговорите с Пестисом.}
{9317006}{}{Похоже это дело рук людей, обосновавшихся на соседней ферме. Идите туда и разберитесь в ситуации.}
{9317007}{}{Возвращайтесь к насосу и подумайте как найти выход из сложившейся ситуации.}
{9317010}{}{Вы сломали панель, поток воды так и будет идти только на ферму. Возвращайтесь к Джереми.}
{9317011}{}{Выполнено: Вы решили, что вода будет поступать только на ферму, и сломали панель, чтобы все оставалось так как есть.}
{9317020}{}{Вы переключили насос, теперь вода будет поступать только в Адитум. Поговорите с Пестисом.}
{9317021}{}{Выполнено: Вы решили переключить насос, направив весь поток воды в Адитум.}
{9317030}{}{Вы переключили насос, направив поток воды в оба направления. Поговорите с Пестисом.}
{9317031}{}{Пестис согласился заключить сделку с людьми на ферме. Поговорите с Джереми.}
{9317032}{}{Выполено: Вы заставили обе стороны конфликта заключить сделку. Никто не остался без воды.}
{9317101}{}{Адитум}
{9317102}{}{Решение проблемы}

# 9318 QUESTNOTICES
{9318001}{}{Вы починили колодец, поговорите с Пестисом.}
{9318002}{}{Вам не хватает опыта, чтобы починить колодец.}
{9318003}{}{Вы привязали веревку, теперь можно спуститься в колодец.}
{9318004}{}{Без веревки в колодец не спуститься.}
{9318005}{}{Он мертв.}

# 9319 - Deathclaws group quest
{9319001}{}{Целый выводок маленьких смертокогтов обосновался в пещере рядом с фермой Пестиса. Помогите ему избавиться от них.}
{9319002}{}{Вы разобрались с когтями смерти, возвращайтесь к пестису и сообщите о своем успехе.}
{9319101}{}{Адитум}
{9319102}{}{Потенциальная угроза}

# 9321 - Raiders group quest
{9321001}{}{Шериф Чарльз хочет, чтобы вы разобрались с рейдерами терроризирующими проходящие караваны.}
{9321002}{}{Вы успешно избавились от присутствия рейдеров в близлежащих окрестностях. Возвращайтесь и сообщите об этом шерифу.}
{9321101}{}{Хаб}
{9321102}{}{Рука правосудия}

# 9323 - Molerats group quest
{9323001}{}{У Варрена возникли проблемы с расплодившимися кротокрысами. Вы пообещали помочь разобраться с его проблемой.}
{9323002}{}{Все кротокрысы уничтожены. Возвращайтесь к Варрену.}
{9323101}{}{Джанктаун}
{9323102}{}{Грызуны повсюду}

# 9325 - Drifters quest
{9325003}{}{Джек, торговец из старого Хаба, хочет, чтобы вы решили его проблему с бродягами, облюбовавшими его склад.}
{9325004}{}{Вам удалось убедить бродяг покинуть склад без применения силы. Возвращайтесь к Джеку.}
{9325005}{}{Используя свои выдающиеся способности в красноречии вам удалось убедить бродяг покинуть склад, прямо в светлое будующее. Возвращайтесь к Джеку.}
{9325006}{}{Выполнено: С уходом бродяг, Джек вновь может свободно использовать свой склад. Он даже дополнительно отблагодарил вас за мирное разрешение проблемы.}
{9325007}{}{Выполнено: Вы "нейтрализовали" всех бродяг, что обосновались на складе у Джона. Ваше твердое решение о применении насилия очень впечатлило его. Хорошая работа.Убийца убогих.} 
{9325101}{}{Хаб}
{9325102}{}{Никто не будет селиться на моей земле!}

# 9334 - BoS
{9334001}{}{Вы только что стали рекрутом Братства стали. Направляйтесь к писарю Кендрик для получения первого задания.}
{9334002}{}{Направляйтесь в Ваулт Сити и свяжитесь с кем либо из правительства города. Вам необходимо выяснить отношение города к Братству, и убедить их установить официальные отношения с Лост Хиллс.}
{9334003}{}{Консул МакКлюр отклонил предложение Братства и это все, чего вы смогли от него добиться. Возвращайтесь в Лост Хиллс и доложите об этом Кендрику.}
{9334004}{}{Консул МакКлюр отклонил предложение Братства, единственное, чего удалось от него добиться это заверения в полном нейтралитете Ваулт Сити. Возвращайтесь в Лост Хиллс и доложите об этом Кендрику.}
{9334005}{}{Несмотря на то что Консул МакКлюр отклонил предложение Братства, вам удалосьнемного разобраться во внутренней политике Ваулт Сити. Доложите о ваших наблюдениях Кендрику.}
{9334006}{}{Ваши успехи вовсе не впечатлили Кендрик. Было бы неплохо не повторять таких ошибок. Доложите ее попоздже.}
{9334007}{}{Хотя Кендрик и не была слишком довольна вашими успехами, вы все же убедились в нейтралитете Ваулт Сити. Доложите ей попозже, чтобы получить новые указания.}
{9334008}{}{Хотя Кендрик и не была слишком довольна вашими успехами, информация, полученная вами о политике города позволяет с надеждой смотреть в будующее. Доложите ей попозже, чтобы получить новые указания.}
{9334009}{}{Вы получили новый приказ. Вашим новым заданием будет эвакуация частей двигателя вертиберда, упавшего неподалеку от Адитума.}
{9334010}{}{Вам удалось разобраться со спасательной командой Анклава и эвакуировать части двигателя вертиберда. Возвращайтесь в Лост Хиллс и доложите Кендрик.}
{9334011}{}{Вам удалось разобраться со спасательной командой Анклава и эвакуировать части двигателя вертиберда. Возвращайтесь в Лост Хиллс и доложите Кендрик.}
{9334012}{}{Доставленные вами детали сильно повреждены. Вы неуверены произошло ли это из-за падения вертиберда, либо из-за ваших неумелых действий по их извлечению. Доложите ей попозже, чтобы получить новые указания.}
{9334013}{}{Доставленные вами детали в основном целы, Кендрик похоже довольна. Доложите ей попозже, чтобы получить новые указания.}
{9334014}{}{Вы получили очередное задание. Необходимо проникнуть на завод Анклава, располагающийся где то к югу от Сан-Франциско. Отыщите радиоуправляемую взрывчатку, взведите таймер и покиньте место дислокации как можно быстрее. Вполне возможно база будет серьезно охраняться, поэтому следует по возможности избегать открытой конфронтацииn.}
{9334015}{}{Вы нашли взрывчатку. Осталось найти радиодетонатор.}
{9334016}{}{Вам нужно найти радиодетонатор и установить таймер. Убирайтесь отсюда как можно быстрее и возвращайтесь в Лост Хиллс.}
{9334017}{}{Вы успешно справилсь с заданием. Теперь вы инициированный член братства. Доложите Кендрик чуть позже для получения новых прикахов.}
{9334021}{}{Как ни стараетесь, вы не можете вспомнить координаты упавшего вертиберда. Нужно навестить Кендрика.}
{9334022}{}{Пока вы занимались своими делами координаты аванпоста Анклава были стерты из Пип-боя. Возвратитесь к Кендрику.}
{9334101}{}{Лост Хиллс}
{9334102}{}{Братья по оружию}

# 9335 - Enclave
{9335001}{}{}
{9335002}{}{Вашим первым заданием будет посещение места под названием Глоу. Необходимо подсоединить ваш пип-бой к суперкомпьютеру и установить контакт с сетью Анклава.}
{9335003}{}{Вы успешно скачали все данные. Возвращайтесь на заправочную станцию и доложите об этом Крису.}
{9335004}{}{Ваше задание состоит в изъятии тела писаря Братства стали из деревни дикарей. В случае оказания сопротивления разрешается применить силу.}
{9335005}{}{Дикари напали на вас как только увидели, пришлось "усмирить" целую деревню. Теперь команда зачистки может без проблем забрать тело писаря. Возвращайтесь на заправочную станцию.}
{9335006}{}{Ваше следующее задание: пробраться на заброшенный аванпост Братства стали и скачать базу данных центрального компьютера. Защита периметра базы все еще включена, продвигайтесь с осторожностью.}
{9335007}{}{Вы успешно скачали базу данных. Возвращайтесь на заправочную станцию и поговорите с Крисом.}
{9335008}{}{Вы успешно выполнили все задания и теперь являетесь полноправным солдатом Анклава.}
{9335021}{}{Как ни стараетесь, вы не можете вспомнить координаты деревни. Нужно навестить Криса.}
{9335022}{}{Пока вы занимались своими делами координаты аванпоста Братства стали были стерты из Пип-боя. Возвратитесь к Крису.}
{9335101}{}{Заправочная станция}
{9335102}{}{Боже, благослови Америку}

# 9630 - Finders Keepers
{9630001}{}{Knight Matthews did not acknowledge that the holodisk you found is Brotherhood's property, and dismissed your claims entirely. You will have to find some proofto make him talk.}
{9630002}{}{Bill wasn't able to help you much, but he pointed you the the Vault City's Mainframe. You will need a permission to access the Vault which it is located in.}
{9630003}{}{{You have managed to read just a small portion of the holodisk's data. It is probably some kind of Brotherhood's communications archive. Head to Lost Hills.}
{9630004}{}{Knight Matthews took the holodisk, but gave you no explanation or reward.}
{9630005}{}{Knight Matthews took the holodisk, and pointed you to Scribe Kendrick.}
{9630006}{}{Scribe Kendrick listened to your report, but was reluctant to divulge any information, and told you to wait for new orders.}
{9630007}{}{Scribe Kendrick listened to your report, but was reluctant to divulge any information, and told you to wait for new orders.}
{9630008}{}{Scribe Kendrick listened to your report, and confirmed your assumptions. Wait for new orders.}
{9630101}{}{Lost Hills}
{9630102}{}{Finders Keepers}