{10}{}{BG mężczyzna}
{20}{}{BG kobieta}
{30}{}{Mieszkaniec wioski}
{40}{}{Mieszkanka wioski}
{50}{}{Radskorpion}
{51}{}{Mały, zmutowany radskorpion.}
{60}{}{Radskorpion}
{61}{}{Zmutowany radskorpion.}
{70}{}{Szpon śmierci}
{71}{}{Młodociany szpon śmierci.}
{80}{}{Szpon śmierci}
{81}{}{Młodociany szpon śmierci.}
{90}{}{Pies}
{91}{}{Prawdopodobnie skundlony przedstawiciel rodziny psowatych.}
{100}{}{Bramin}
{101}{}{Dwugłowa, zmutowana krowa.}
{110}{}{Szczur}
{111}{}{Typowy, duży szczur.}
{120}{}{Modliszka}
{121}{}{Zmutowana modliszka.}
{130}{}{Starsza}
{140}{}{Hakunin}
{150}{}{Mynoc}
{160}{}{Drapieżna roślina}
{161}{}{Mięsożerna roślina.}
{170}{}{Piękna niewolnica}
{180}{}{Przystojny niewolnik}
{190}{}{Zdrowa niewolnica}
{200}{}{Zdrowy niewolnik}
{210}{}{Silna niewolnica}
{220}{}{Silny niewolnik}
{230}{}{Waleczna niewolnica}
{240}{}{Waleczny niewolnik}
{250}{}{Sprytna niewolnica}
{260}{}{Sprytny niewolnik}
{270}{}{Niewolnica}
{280}{}{Niewolnik}
{290}{}{Anna}
{300}{}{Twardy bandzior}
{310}{}{Twarda bandytka}
{320}{}{Bandzior walczący wręcz}
{330}{}{Bandytka walcząca wręcz}
{340}{}{Zręczny bandzior}
{350}{}{Zręczna bandytka}
{360}{}{Bandzior ze spluwą}
{370}{}{Bandytka ze spluwą}
{380}{}{Bandzior z wielką spluwą}
{390}{}{Bandytka z wielką spluwą}
{400}{}{Twardy strażnik}
{410}{}{Twarda strażniczka}
{420}{}{Strażnik walczący wręcz}
{430}{}{Strażniczka walcząca wręcz}
{440}{}{Zręczny strażnik}
{450}{}{Zręczna strażniczka}
{460}{}{Strażnik ze spluwą}
{470}{}{Strażniczka ze spluwą}
{480}{}{Strażnik z wielką spluwą}
{490}{}{Strażniczka z wielką spluwą}
{500}{}{Chłopczyk-sierota}
{510}{}{Dziewczynka-sierota}
{520}{}{Chłopiec}
{530}{}{Dziewczynka}
{540}{}{Przegrany}
{550}{}{Przegrana}
{560}{}{Zły handlarz}
{570}{}{Zła handlarka}
{580}{}{Średni handlarz}
{590}{}{Średnia handlarka}
{600}{}{Mistrz handlu}
{610}{}{Mistrzyni handlu}
{620}{}{Vic}
{630}{}{Osoba}
{640}{}{Osoba}
{650}{}{Osoba}
{660}{}{Osoba}
{670}{}{Osoba}
{680}{}{Osoba}
{690}{}{Strażnik}
{700}{}{Strażnik}
{710}{}{Strażnik}
{720}{}{Strażnik}
{730}{}{Robot naprawczy}
{740}{}{Ulepszony robot naprawczy}
{750}{}{Robomózg}
{760}{}{Lewitujące Oko}
{770}{}{Robot strażniczy}
{780}{}{Ulepszony robot strażniczy}
{790}{}{Robomózg}
{800}{}{Mały gekon}
{810}{}{Twardy mały gekon}
{820}{}{Dziki pies}
{821}{}{Przynoszący pecha kundel.}
{830}{}{Złoty gekon}
{840}{}{Szpon śmierci}
{850}{}{Pomiot szpona śmierci}
{860}{}{Twardy złoty gekon}
{870}{}{Lynette}
{880}{}{Dr Troy}
{890}{}{John Cassidy}
{900}{}{Gregory}
{910}{}{Obywatelka}
{920}{}{Obywatel}
{930}{}{Obywatelka klasy wyższej}
{940}{}{Obywatel klasy wyższej}
{950}{}{Traper}
{960}{}{Traperka}
{970}{}{Sulik}
{980}{}{Maida Buckner}
{990}{}{Torr}
{1000}{}{Lumpy}
{1010}{}{Świecący z reaktora}
{1020}{}{Ghul z reaktora}
{1030}{}{Strażnik reaktora}
{1040}{}{Zomak}
{1050}{}{Skeeter}
{1060}{}{Mózg}
{1070}{}{Lenny}
{1080}{}{Wooz}
{1090}{}{Harold}
{1100}{}{Kretoszczur}
{1110}{}{Większy kretoszczur}
{1120}{}{Świnioszczur}
{1130}{}{Twardy świnioszczur}
{1140}{}{Osłabiony bramin}
{1141}{}{Dwugłowa, zmutowana krowa.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Zmutowany szczur}
{1161}{}{Twardy, zmutowany szczur.}
{1170}{}{Zmutowany kretoszczur}
{1171}{}{Twardy, zmutowany kretoszczur.}
{1180}{}{Zmutowany świnioszczur}
{1181}{}{Twardy, zmutowany świnioszczur.}
{1190}{}{Supermutant}
{1200}{}{Mutant}
{1210}{}{Super Mutant}
{1220}{}{Hero Andro (don't use)}
{1230}{}{Hero Andro (don't use)}
{1240}{}{Hero Male (don't use)}
{1250}{}{Hero Female (don't use)}
{1260}{}{Hero Male (don't use)}
{1270}{}{Hero Female (don't use)}
{1280}{}{Hero Male (don't use)}
{1290}{}{Hero Female (don't use)}
{1300}{}{Hero Male (don't use)}
{1310}{}{Hero Female (don't use)}
{1320}{}{Hero Male (don't use)}
{1330}{}{Hero Female (don't use)}
{1340}{}{Strażnik bramy Kryptopolis}
{1350}{}{Strażniczka bramy Kryptopolis}
{1360}{}{Cyberpies}
{1370}{}{Strażnik RNK}
{1380}{}{Strażnik RNK}
{1390}{}{Walczący wręcz strażnik RNK}
{1400}{}{Łowca niewolników}
{1410}{}{Nadzorca niewolników}
{1420}{}{Mistrz handlu}
{1430}{}{Mistrzyni handlu}
{1440}{}{Tandi}
{1450}{}{Merc}
{1460}{}{Ratch}
{1470}{}{Skeeter}
{1480}{}{Mikey}
{1490}{}{Barmanka RNK}
{1500}{}{Właściciel sklepu}
{1510}{}{Gruthar}
{1520}{}{Goris}
{1530}{}{Kretoszczur-wojownik}
{1540}{}{Kretoszczur-wojownik}
{1550}{}{Kretoszczur-wojownik}
{1560}{}{Kretoszczur-wojownik}
{1570}{}{Kretoszczur-wojownik}
{1580}{}{Kretoszczur-wojownik}
{1590}{}{Ghul}
{1600}{}{Myron}
{1610}{}{Marcus}
{1620}{}{Doc Jones}
{1630}{}{Davin}
{1640}{}{Miria}
{1650}{}{Laddie}
{1660}{}{Rondo}
{1670}{}{Kowboj}
{1680}{}{Kowbojka}
{1690}{}{Kowboj}
{1700}{}{Bramkarz}
{1710}{}{Bramkarz}
{1720}{}{Słaby Pan Złota Rączka}
{1730}{}{Świecący}
{1740}{}{Dar}
{1750}{}{Dalia}
{1760}{}{Gordon}
{1770}{}{Test (don't use)}
{1780}{}{Ghul z reaktora}
{1790}{}{Ghul}
{1800}{}{Matt}
{1810}{}{Szef łowców nagród (1-6)}
{1820}{}{Łowca nagród (1-6)}
{1830}{}{Szefowa łowców nagród (7-12)}
{1840}{}{Łowca nagród (7-12)}
{1850}{}{Łowczyni nagród (7-12)}
{1860}{}{Szefowa łowców nagród (13-18)}
{1870}{}{Łowca nagród (13-18)}
{1880}{}{Łowczyni nagród (13-18)}
{1890}{}{Szef łowców nagród (19-?)}
{1900}{}{Łowca nagród (19-?)}
{1910}{}{Bess}
{1911}{}{Dwugłowa, zmutowana krowa.}
{1920}{}{Balthas}
{1930}{}{Grisham}
{1940}{}{Phil}
{1950}{}{Tchórz}
{1960}{}{Karl}
{1970}{}{Jonny}
{1980}{}{Jo}
{1990}{}{Zeke}
{2000}{}{Rzeźnik}
{2010}{}{Petey}
{2020}{}{Prymitywny łowca}
{2030}{}{Prymitywna łowczyni}
{2040}{}{Kanibal}
{2050}{}{Kanibalka}
{2060}{}{Święty Człowiek}
{2070}{}{Święta Kobieta}
{2080}{}{Koczownik - sł.}
{2090}{}{Koczownik - śr.}
{2100}{}{Koczowniczka - sł.}
{2110}{}{Koczowniczka - śr.}
{2120}{}{Bandyta}
{2130}{}{Bandytka}
{2140}{}{Wieśniak}
{2150}{}{Wieśniaczka}
{2160}{}{Modliszka}
{2170}{}{Łowca niewolników}
{2180}{}{Łowczyni niewolników}
{2190}{}{Dziki bramin}
{2200}{}{Posiadacz ziemski}
{2210}{}{Posiadaczka ziemska}
{2220}{}{Członek patrolu Kryptopolis}
{2230}{}{Członkini patrolu Kryptopolis}
{2240}{}{Silny łowca niewolników}
{2250}{}{Silna łowczyni niewolników}
{2260}{}{Świry}
{2270}{}{Ścierwojady}
{2280}{}{Świry z Blasku}
{2290}{}{Ścierwojady z Blasku}
{2300}{}{Rybak}
{2310}{}{Rybaczka}
{2320}{}{Dziki człowiek}
{2330}{}{Dzika kobieta}
{2340}{}{Trep}
{2350}{}{Trepka}
{2360}{}{Poszukiwacz złota}
{2370}{}{Poszukiwaczka złota}
{2380}{}{Bandyta}
{2390}{}{Bandytka}
{2400}{}{Ognisty gekon}
{2410}{}{Twardy ognisty gekon}
{2420}{}{Obcy}
{2430}{}{Twardy obcy}
{2440}{}{Twardy szpon śmierci}
{2450}{}{Twardy szpon śmierci}
{2460}{}{Wisielec}
{2470}{}{Wredny wisielec}
{2480}{}{Centaur}
{2490}{}{Wredny centaur}
{2500}{}{Członek patrolu Enklawy}
{2510}{}{Członkini patrolu Enklawy}
{2520}{}{Członek gangu}
{2530}{}{Członkini gangu}
{2540}{}{Najemnik}
{2550}{}{Najemniczka}
{2560}{}{Pomiot Nocy}
{2570}{}{Twardy Pomiot Nocy}
{2580}{}{Twardy ghul}
{2590}{}{Mafioso}
{2600}{}{Yakuza}
{2610}{}{Strażnik RNK}
{2620}{}{Strażniczka RNK}
{2630}{}{Bandyta}
{2640}{}{Bandytka}
{2650}{}{Piękniś Lloyd}
{2660}{}{Widmowy szczur}
{2670}{}{Mężczyzna z Krypty 13}
{2680}{}{Kobieta z Krypty 13}
{2690}{}{Strażnik mostu}
{2700}{}{Tajemniczy nieznajomy}
{2710}{}{Tajemnicza nieznajoma}
{2720}{}{Hakeswill}
{2730}{}{Duży Jesus Mordino}
{2740}{}{Dumar}
{2741}{}{Dumar, the brahmin trader.}
{2750}{}{Matka szponów śmierci}
{2760}{}{Smok}
{2770}{}{Lo Pan}
{2780}{}{Centrolog}
{2790}{}{Centrolożka}
{2800}{}{Tajemniczy nieznajomy}
{2810}{}{Tajemnicza nieznajoma}
{2820}{}{Tajemniczy nieznajomy}
{2830}{}{Tajemnicza nieznajoma}
{2840}{}{Tajemniczy nieznajomy}
{2850}{}{Tajemnicza nieznajoma}
{2860}{}{Tajemniczy nieznajomy}
{2870}{}{Tajemnicza nieznajoma}
{2880}{}{Ochroniarz prezydenta}
{2890}{}{Jajo szponów śmierci}
{2900}{}{Metzger}
{2910}{}{Strażnik Enklawy}
{2920}{}{Strażniczka Enklawy}
{2930}{}{Prezydent}
{2940}{}{Wiceprezydent}
{2950}{}{Technik}
{2960}{}{Badger}
{2970}{}{Dr Fung}
{2980}{}{Dziecko}
{2990}{}{Dziecko}
{3000}{}{Handlarz bronią}
{3010}{}{Technik laboratorium Shi}
{3020}{}{Strażnik Shi}
{3030}{}{Wieśniak Shi}
{3040}{}{Wieśniaczka Shi}
{3050}{}{Wieśniak Lo Pana}
{3060}{}{Wieśniaczka Lo Pana}
{3070}{}{Pracownik doków}
{3080}{}{Kupiec Shi}
{3090}{}{Kruul Szczu'ur}
{3100}{}{Sulik - poziom 1}
{3110}{}{Sulik - poziom 2}
{3120}{}{Sulik - poziom 3}
{3130}{}{Sulik - poziom 4}
{3140}{}{Sulik - poziom 5}
{3150}{}{Sulik - poziom 6}
{3160}{}{Lenny - poziom 1}
{3170}{}{Lenny - poziom 2}
{3180}{}{Lenny - poziom 3}
{3190}{}{Goris - poziom 1}
{3200}{}{Goris - poziom 2}
{3210}{}{Goris - poziom 3}
{3220}{}{Goris - poziom 4}
{3230}{}{Goris - poziom 5}
{3240}{}{Goris - poziom 6}
{3250}{}{Myron - poziom 1}
{3260}{}{Myron - poziom 2}
{3270}{}{Myron - poziom 3}
{3280}{}{Myron - poziom 4}
{3290}{}{Marcus - poziom 1}
{3300}{}{Marcus - poziom 2}
{3310}{}{Marcus - poziom 3}
{3320}{}{Marcus - poziom 4}
{3330}{}{Marcus - poziom 5}
{3340}{}{Cyberpies - poziom 1}
{3350}{}{Cyberpies - poziom 2}
{3360}{}{Cyberpies - poziom 3}
{3370}{}{Cyberpies - poziom 4}
{3380}{}{Cassidy - poziom 1}
{3390}{}{Cassidy - poziom 2}
{3400}{}{Cassidy - poziom 3}
{3410}{}{Cassidy - poziom 4}
{3420}{}{Dogmeat}
{3430}{}{Dogmeat - poziom 1}
{3440}{}{Dogmeat - poziom 2}
{3450}{}{Dogmeat - poziom 3}
{3460}{}{Dogmeat - poziom 4}
{3470}{}{Dogmeat - poziom 5}
{3480}{}{Dogmeat - poziom 6}
{3490}{}{Robomózg - poziom 1}
{3500}{}{Robomózg - poziom 2}
{3510}{}{Robomózg - poziom 3}
{3520}{}{Robomózg - poziom 4}
{3530}{}{Robomózg - poziom 5}
{3540}{}{Królowa obcych}
{3550}{}{Czarny radskorpion}
{3560}{}{Czarny radskorpion}
{3570}{}{Spud}
{3580}{}{Kapitan najemników}
{3590}{}{Najemnik}
{3600}{}{Najemnik}
{3610}{}{Cień-Który-Chodzi}
{3620}{}{Punkówa}
{3630}{}{Punk}
{3640}{}{Mark}
{3650}{}{Dave H.}
{3660}{}{Kpt. A. Ron Meyers}
{3670}{}{Chip}
{3680}{}{UKC-9}
{3690}{}{Strażnik Centrologów}
{3700}{}{Strażniczka Centrologów}
{3710}{}{Juan}
{3720}{}{Vikki}
{3730}{}{Vic - poziom 1}
{3740}{}{Vic - poziom 2}
{3750}{}{Vic - poziom 3}
{3760}{}{Vic - poziom 4}
{3770}{}{Vic - poziom 5}
{3780}{}{Vic - poziom 6}
{3790}{}{Robomózg - szympans}
{3800}{}{Robomózg - nienormalny}
{3810}{}{Robomózg - człowiek}
{3820}{}{Olbrzymia mrówka}
{3830}{}{Twarda olbrzymia mrówka}
{3840}{}{Wychudły pies}
{3850}{}{Zurak}
{3860}{}{Imbot}
{3870}{}{Jimmy}
{3880}{}{Wejungh}
{3890}{}{Herb}
{3900}{}{Loopal}
{3910}{}{Jobe}
{3920}{}{Smitty}
{3930}{}{Rube}
{3940}{}{Mistrz Krall}
{3950}{}{Ziggy}
{3960}{}{Mistrz Khung}
{3970}{}{John Bishop}
{3980}{}{Angela Bishop}
{3990}{}{Pani Bishop}
{4000}{}{Strażnik Bishopów}
{4010}{}{Strażnik Bishopów}
{4020}{}{Zbir Bishopów}
{4030}{}{Zbir Bishopów}
{4040}{}{Wściekły bramin}
{4050}{}{Mały Jesus}
{4060}{}{Duży Jesus}
{4070}{}{Człowiek rodziny Mordino}
{4080}{}{Człowiek rodziny Mordino}
{4090}{}{Człowiek rodziny Mordino}
{4100}{}{Strażnik Myrona}
{4110}{}{Strażnik Myrona}
{4120}{}{Pan Wright}
{4130}{}{Pani Wright}
{4140}{}{Chris Wright}
{4150}{}{Keith Wright}
{4160}{}{Syn Wrightów}
{4170}{}{Syn Wrightów}
{4180}{}{Córka Wrightów}
{4190}{}{Córka Wrightów}
{4200}{}{Pan Salvatore}
{4210}{}{Mason}
{4220}{}{Zbir rodziny Salvatore}
{4230}{}{Zbir rodziny Salvatore}
{4240}{}{Barman}
{4250}{}{Barman}
{4260}{}{Barman}
{4270}{}{Bokser}
{4280}{}{Bokser}
{4290}{}{Bokser}
{4300}{}{Bokser}
{4310}{}{Mike Przeżuwacz}
{4320}{}{Holyfeld}
{4330}{}{McKneely}
{4340}{}{Stuart Malutki}
{4350}{}{Korsykańscy bracia}
{4360}{}{Korsykańskie dziwki}
{4370}{}{Ojciec Tully}
{4380}{}{Bramkarz kasyna}
{4390}{}{Bramkarz kasyna}
{4400}{}{Dziewczynka z kasyna}
{4410}{}{Dealer}
{4420}{}{Dealer}
{4430}{}{Dealer}
{4440}{}{Dealer}
{4450}{}{McGee}
{4460}{}{Panna Kitty}
{4470}{}{Dziwka}
{4480}{}{Dziwka}
{4490}{}{Jagged Jimmy J}
{4500}{}{Renesco}
{4510}{}{Naukowiec}
{4520}{}{Eldridge}
{4530}{}{Algernon}
{4540}{}{Jules}
{4550}{}{Biurokrata}
{4560}{}{Biurokratka}
{4570}{}{Kupiec}
{4580}{}{Kupiec}
{4590}{}{Strażnik}
{4600}{}{Strażnik}
{4610}{}{Strażniczka}
{4620}{}{Strażniczka}
{4630}{}{Żołnierz}
{4640}{}{Żołnierz}
{4650}{}{Żołnierz}
{4660}{}{Żołnierz}
{4670}{}{Sierż. Stark}
{4680}{}{"Doc" Andrew}
{4690}{}{Barman}
{4700}{}{Wieżyczka strzelnicza}
{4701}{}{Automatyczna wieżyczka strzelnicza wyposażona w podwójne działko plazmowe.}
{4710}{}{Wild Dog}
{4720}{}{Wild Dog}
{4730}{}{Wild Dog}
{4740}{}{Wild Dog}
{4750}{}{Coyote}
{4760}{}{Cybierpies}
{4770}{}{Jajo Wanamingo}
{4780}{}{Strażnik Lo Pana}
{4790}{}{Marjorie}
{4800}{}{Działko Automatyczne}
{4810}{}{Wyjątkowa istota z Gecko}
{4820}{}{Śmierć}
{4830}{}{Frank Horrigan}
{4831}{}{Ochroniarz prezydenta}
{4840}{}{Wilk}
{4850}{}{Wściekły pies}
{4860}{}{Kojot}
{4870}{}{Zmutowany Radskorpion}
{4880}{}{Mały złoty gekon}
{4890}{}{Buntownik}
{4900}{}{Żuk}
{4910}{}{Inżynier}
{4920}{}{Żołnierz Enklawy}
{4930}{}{Inżynier}
{4940}{}{Rycerz Bractwa}
{4950}{}{Komandos}
{4960}{}{Żołnierz Enklawy}
{4970}{}{Paladyn Bractwa}
{4980}{}{Regulator}
{4990}{}{Bandyta}
{5000}{}{Bandyta}
{5010}{}{Najeźdźca}
{5020}{}{Najeźdźca}
{5030}{}{Najeźdźca}
{5040}{}{Najeźdźca}
{5050}{}{Gigantyczna osa}
{5051}{}{Огромное кровожадное насекомое}
{5060}{}{Гвардеец}
{5061}{}{Боец Гвардии ГУ}
{5070}{}{Duży nietoperz}
{5080}{}{Zwiadowca Arroyo}
{5090}{}{Zwiadowca Arroyo}
{5100}{}{Zwiadowca Arroyo}
{5110}{}{Ścigany}
{5120}{}{Ścigany}
{5130}{}{Ścigany}
{5140}{}{Ścigany}
{5150}{}{Ścigany}
{5160}{}{Eli}
{5170}{}{Champion}
{5180}{}{Helacyton type  1}
{5181}{}{A strange creature resembling Master's pets.}
{5190}{}{Angry helacyton type  1}
{5191}{}{A strange creature resembling Master's pets.}
{5200}{}{Helacyton type  2}
{5201}{}{A strange creature resembling Master's pets.}
{5210}{}{Angry helacyton type  2}
{5211}{}{A strange creature resembling Master's pets.}
{5220}{}{Helacyton type  3}
{5221}{}{A strange creature resembling Master's pets.}
{5230}{}{Henrietta}
{5231}{}{Skin of this animal looks like one big callus.}
{5240}{}{Android}
{5250}{}{Tim Cain}
{5260}{}{Carlos Jackal}
{5270}{}{Carlos Jackal}
{5280}{}{Behemoth}
{5281}{}{Огромный механический жук на шести лапах, оснащен крупнокалиберным пулеметом.}
{5300}{}{Strażnik Złomowa}
{5301}{}{Ten cżłowiek zdaje się uważnie obserwować okolicę.}
{5310}{}{Strażnik Złomowa}
{5311}{}{Ten mężczyzna uważnie obserwuje swoje otoczenie.}
{5320}{}{Ron Winkley}
{5321}{}{Strażnik więzienia.}
{5330}{}{Strażnik}
{5331}{}{Strażnik pilnujący Zabójcy.}
{5340}{}{Zabójca}
{5341}{}{Zabójca.}
{5350}{}{Strażnik Złomowa}
{5351}{}{Ten strażnik uważnie rejestruje twój każdy krok.}
{5360}{}{Strażnik Hub}
{5361}{}{Stróż prawa uważnie obserwujący swoje otoczenie.}
{5370}{}{Strażnik Hub}
{5371}{}{Ten człowiek patroluje okolicę.}
{5380}{}{Pomiot Nocy}
{5381}{}{Silny i agresywny Supermutant.}
{5390}{}{Pomiot Nocy}
{5391}{}{Potężny Supermutant. Z jakiegoś powodu jest bardzo słabo widoczny.}
{5400}{}{Supermutant}
{5401}{}{Typowy Supermutant.}
{5410}{}{Uciekinier}
{5420}{}{Uciekinier}
{5430}{}{Uciekinier}
{5440}{}{Uciekinier}
{5450}{}{Uciekinier}
{5460}{}{Chuck Lee}
{5461}{}{Chuck Lee, strażnik karawany.}
{5470}{}{Manekin}
{5480}{}{Manekin}
{5490}{}{Manekin}
{5500}{}{Manekin}
{5510}{}{Manekin}
{5520}{}{Manekin}
{5530}{}{Manekin}
{5540}{}{Manekin}
{5550}{}{Manekin}
{5560}{}{Manekin}
{5570}{}{Manekin}
{5580}{}{Manekin}
{5590}{}{Manekin}
{5600}{}{Manekin}
{5610}{}{Manekin}
{5620}{}{Manekin}
{5630}{}{Manekin}
{5640}{}{Manekin}
{5650}{}{Manekin}
{5660}{}{Manekin}
{5670}{}{Manekin}
{5680}{}{Manekin}
{5690}{}{Manekin}
{5700}{}{Manekin}
{5710}{}{Manekin}
{5720}{}{Manekin}
{5730}{}{Manekin}
{5740}{}{Manekin}
{5750}{}{Manekin}
{5760}{}{Manekin}
{5770}{}{Manekin}
{5780}{}{Manekin}
{5790}{}{Manekin}
{5800}{}{Manekin}
{5810}{}{Manekin}
{5820}{}{Manekin}
{5830}{}{Manekin}
{5840}{}{Manekin}
{5850}{}{Manekin}
{5860}{}{Manekin}
{5870}{}{Manekin}
{5880}{}{Manekin}
{5890}{}{Manekin}
{5900}{}{Manekin}
{5910}{}{Manekin}
{5920}{}{Manekin}
{5930}{}{Manekin}
{5940}{}{Manekin}
{5950}{}{Manekin}
{5960}{}{Manekin}
{5970}{}{Manekin}
{5980}{}{Manekin}
{5990}{}{Manekin}
{6000}{}{Manekin}
{6010}{}{Silny strażnik Złomowa}
{6011}{}{Imponująco prezentujący się strażnik.}
{6030}{}{Silny strażnik Złomowa}
{6031}{}{Lepiej z nim nie zaczynać.}
{6040}{}{Silny strażnik Złomowa}
{6041}{}{Ten człowiek dyskretnie obserwuje każdy twój ruch.}
{6050}{}{Trader KLAMATH}
{6060}{}{Trader DEN}
{6070}{}{Trader REDDING}
{6080}{}{Trader MODOC}
{6090}{}{Trader GECKO}
{6100}{}{Trader VC OUT}
{6110}{}{Trader VC IN}
{6120}{}{Trader BROKEN HILLS}
{6130}{}{Trader NEW RENO}
{6140}{}{Trader SAN FRANCISCO}
{6150}{}{Trader NCR OUT}
{6160}{}{Trader NCR IN}
{6170}{}{Trader HUB}
{6180}{}{Trader BONEYARD}
{6190}{}{Doctor VC IN}
{6200}{}{Doctor VC OUT}
{6210}{}{Doctor NCR}
{6220}{}{Doctor HUB}
{6230}{}{Doctor BONEYARD}
{6240}{}{Doctor SANFRANCISCO}
{6250}{}{Doctor NEW RENO}
{6260}{}{Doctor BROKEN HILLS}
{6270}{}{Doctor REDDING}
{6280}{}{BAR SF}
{6290}{}{BAR BH}
{6300}{}{BAR BHWIFE}
{6310}{}{BAR SALVNR}
{6320}{}{BAR CASINONR}
{6330}{}{BAR GECKO}
{6340}{}{BAR VC}
{6350}{}{BAR MODOC}
{6360}{}{BAR WIFEKLAMATH}
{6370}{}{BAR DUDEKLAMATH}
{6380}{}{BAR CASINODEN}
{6390}{}{BAR DEN}
{6400}{}{BAR MOMDEN}
{6410}{}{BAR HUB}
{6420}{}{BAR JT}
{6430}{}{BAR MALAMUTREDDING}
{6440}{}{BAR COFFINREDDING}
{6450}{}{BAR NCROUT}
{6460}{}{BAR NCRIN}
{6470}{}{SFTANK GUNS}
{6480}{}{SFTANK ARMOR}
{6490}{}{BALDCHINA}
{6500}{}{BH CARAVANDUDE}
{6510}{}{BH HUSBAND}
{6520}{}{NEWR ARMS}
{6530}{}{GECKO SKEET}
{6540}{}{GECKO SHERIFF}
{6550}{}{VC A ARMOR}
{6560}{}{VC B WEAPON}
{6570}{}{MODOC TANNER}
{6580}{}{MODOC WILLY}
{6590}{}{DEN SECOND}
{6600}{}{HUB JACOB}
{6610}{}{HUB GUNS}
{6620}{}{BONE GUNRUNNERS}
{6630}{}{Samica Szpona Śmierci}
{6631}{}{Kurwa, lepiej stąd spierdalać!}
{6640}{}{Szpon Smierci}
{7000}{}{Uciekinier}
{7010}{}{Bandyta}
{7020}{}{Bandyta}
{7030}{}{Bandyta}
{7040}{}{Bandyta}
{7050}{}{Bandyta}
{7060}{}{Bandyta}
{7070}{}{Rabuś}
{7080}{}{Rabuś}
{7090}{}{Rabuś}
{7100}{}{Rabuś}
{7110}{}{Rabuś}
{7120}{}{Rabuś}
{7130}{}{Przemytnik}
{7140}{}{Przemytnik}
{7150}{}{Przemytnik}
{7160}{}{Przemytnik}
{7170}{}{Bandzior}
{7180}{}{Bandzior}
{7190}{}{Bandzior}
{7200}{}{Bandzior}
{7210}{}{Bandzior}
{7220}{}{Bandzior}
{7230}{}{Bimbrownik}
{7240}{}{Bimbrownik}
{7250}{}{Bimbrownik}
{7260}{}{Bimbrownik}
{7270}{}{Bimbrownik}
{7280}{}{Bimbrownik}
{7290}{}{Dezerter}
{7300}{}{Dezerter}
{7310}{}{Dezerter}
{7320}{}{Dezerter}
{7330}{}{Dezerter}
{7340}{}{Dezerter}
{7350}{}{Najeźdźca}
{7360}{}{Najeźdźca}
{7370}{}{Najeźdźca}
{7380}{}{Najeźdźca}
{7390}{}{Najeźdźca}
{7400}{}{Najeźdźca}
{7410}{}{Ghul}
{7420}{}{Ghul}
{7430}{}{Ghul}
{7440}{}{Ghul}
{7450}{}{Ghul}
{7460}{}{Punk}
{7470}{}{Punk}
{7480}{}{Punk}
{7490}{}{Punk}
{7500}{}{Punk}
{7510}{}{Rozpruwacz}
{7520}{}{Rozpruwacz}
{7530}{}{Rozpruwacz}
{7540}{}{Rozpruwacz}
{7550}{}{Rozpruwacz}
{7560}{}{Najeźdźca}
{7570}{}{Najeźdźca}
{7580}{}{Najeźdźca}
{7590}{}{Najeźdźca}
{7600}{}{Najeźdźca}
{7610}{}{Strzelec}
{7620}{}{Stuknięta zdzira}
{7630}{}{Kozak}
{7640}{}{Wykidajło}
{7650}{}{Gangster}
{7660}{}{Rzezimieszek}
{7670}{}{Rzezimieszek}
{7680}{}{Rzezimieszek}
{7690}{}{Rzezimieszek}
{7700}{}{Rzezimieszek}
{7710}{}{Wściekła menda}
{7720}{}{Świr}
{7730}{}{Szaleniec}
{7740}{}{Paskuda}
{7750}{}{Ścierwo}
{7760}{}{Najemnik}
{7770}{}{Najemnik}
{7780}{}{Najemnik}
{7790}{}{Najemnik}
{7800}{}{Najemnik}
{7810}{}{Ghul}
{7820}{}{Regulator}
{7830}{}{Regulator}
{7840}{}{Regulator}
{7850}{}{Regulator}
{7860}{}{Wojownik Chanów}
{7870}{}{Wojownik Chanów}
{7880}{}{Wojownik Chanów}
{7890}{}{Wojownik Chanów}
{7900}{}{Wojownik Chanów}
{7910}{}{Łotr}
{7920}{}{Łotr}
{7930}{}{Łotr}
{7940}{}{Łotr}
{7950}{}{Łotr}
{7960}{}{Rekrut Enklawy}
{7970}{}{Żołnierz Enklawy}
{7980}{}{Żołnierz Enklawy}
{7990}{}{Weteran Enklawy}
{8000}{}{Weteran Enklawy}
{8010}{}{Supermutant}
{8020}{}{Supermutant}
{8030}{}{Supermutant}
{8040}{}{Pomiot Nocy}
{8050}{}{Pomiot Nocy}
{8060}{}{Ghul}
{8070}{}{Ghul}
{8080}{}{Ghul}
{8090}{}{Ghul}
{8100}{}{Ghul}
{8110}{}{Ghul}
{8120}{}{Ghul}
{8130}{}{Ghul}
{8140}{}{Ghul}
{8150}{}{Ghul}
{8160}{}{Ghul}
{8170}{}{Rekrut Enklawy}
{8180}{}{Rekrut Enklawy}
{8190}{}{Żołnierz Enklawy}
{8200}{}{Weteran Enklawy}
{8210}{}{Kadet Bractwa}
{8220}{}{Rycerz Bractwa}
{8230}{}{Rycerz Bractwa}
{8240}{}{Paladyn Bractwa}
{8250}{}{Paskudztwo}
{8260}{}{Potworność}
{8270}{}{Szczur jaskiniowy}
{8280}{}{Zmutowany świnioszczur}
{8290}{}{Zmutowany kretoszczur}
{8300}{}{Gore}
{8301}{}{Niezwykły zmutowany kretoszczur.}
{8310}{}{Robomózg}
{8320}{}{Lewitujące Oko}
{8330}{}{Ghul Strażnik}
{8340}{}{Zed}
{8350}{}{Wojownik Khanów}
{8360}{}{Wojownik Khanów}
{8370}{}{Wojownik Khanów}
{8380}{}{Wojownik Khanów}
{8390}{}{Wojownik Khanów}
{8400}{}{Zwiadowca Złomowa}
{8410}{}{Zwiadowca Złomowa}
{8420}{}{Zwiadowca Złomowa}
{8430}{}{Zwiadowca Złomowa}
{8440}{}{Zwiadowca Złomowa}
{8450}{}{Ochroniaż Karawany}
{8460}{}{Ochroniaż Karawany}
{8470}{}{Ochroniaż Karawany}
{8480}{}{Ochroniaż Karawany}
{8490}{}{Kupiec}
{8500}{}{Bandyta}
{8510}{}{Bandyta}
{8520}{}{Bandyta}
{8530}{}{Bandyta}
{8540}{}{Bandyta}
{8550}{}{Bandyta}
{8560}{}{Złodziej}
{8570}{}{Złodziej}
{8580}{}{Złodziej}
{8590}{}{Złodziej}
{8600}{}{Złodziej}
{8610}{}{Złodziej}
{8620}{}{Dowódca Karawany}
{8630}{}{Ochroniaż Karawany}
{8640}{}{Ochroniaż Karawany}
{8650}{}{Ochroniaż Karawany}
{8660}{}{Ochroniaż Karawany}
{8670}{}{Ochroniaż Karawany}
{8680}{}{Ochroniaż Karawany}
{8690}{}{Ochroniaż Karawany}
{8700}{}{Ochroniaż Karawany}
{8710}{}{Rekrut Bractwa Stali}
{8720}{}{Żołnierz Bractwa Stali}
{8730}{}{Żołnierz Bractwa Stali}
{8740}{}{Paladyn Bractwa Stali}
{8750}{}{Paladyn Bractwa Stali}
{8760}{}{Strażnik Hub}
{8770}{}{Strażnik Hub}
{8780}{}{Strażnik Hub}
{8790}{}{Strażnik Hub}
{8800}{}{Strażnik Hub}
{8810}{}{Strażnik Kryptopolis}
{8820}{}{Strażnik Kryptopolis}
{8830}{}{Strażnik Kryptopolis}
{8840}{}{Strażnik Kryptopolis}
{8850}{}{Strażnik Kryptopolis}
{8860}{}{Ghul}
{8870}{}{Ghul}
{8880}{}{Ghul}
{8890}{}{Ghul}
{8900}{}{Ghul}
{8910}{}{Brzytwa}
{8920}{}{Brzytwa}
{8930}{}{Brzytwa}
{8940}{}{Brzytwa}
{8950}{}{Brzytwa}
{8960}{}{Członek Jedności}
{8970}{}{Członek Jedności}
{8980}{}{Członek Jedności}
{8990}{}{Strażnik RNK}
{9000}{}{Strażnik RNK}
{9010}{}{Strażnik RNK}
{9020}{}{Piechur RNK}
{9030}{}{Rekrut RNK}
{9040}{}{Dowódca Karawany}
{9050}{}{Ochroniaż Karawany}
{9060}{}{Ochroniaż Karawany}
{9070}{}{Ochroniaż Karawany}
{9080}{}{Ochroniaż Karawany}
{9090}{}{Ochroniaż Karawany}
{9100}{}{Ochroniaż Karawany}
{9110}{}{Ochroniaż Karawany}
{9120}{}{Ochroniaż Karawany}
{9130}{}{Farmer}
{9140}{}{Farmer}
{9150}{}{Farmer}
{9160}{}{Farmer}
{9170}{}{Dziecko}
{9180}{}{Wieśniak}
{9190}{}{Wieśniak}
{9200}{}{Wieśniak}
{9210}{}{Wieśniak}
{9220}{}{Dziecko}
{9230}{}{Wieśniak}
{9240}{}{Zbieracz}
{9250}{}{Zbieracz}
{9260}{}{Zbieracz}
{9270}{}{Zbieracz}
{9280}{}{Zbieracz}
{9290}{}{Włóczęga}
{9300}{}{Włóczęga}
{9310}{}{Włóczęga}
{9320}{}{Włóczęga}
{9330}{}{Trapper}
{9340}{}{Trapper}
{9350}{}{Trapper}
{9360}{}{Myśliwy}
{9370}{}{Myśliwy}
{9380}{}{Myśliwy}
{9390}{}{Prospektor}
{9400}{}{Prospektor}
{9410}{}{Prospektor}
{9420}{}{Mieszkaniec}
{9430}{}{Mieszkaniec}
{9440}{}{Mieszkaniec}
{9450}{}{Mieszkaniec}
{9460}{}{Hubulog}
{9470}{}{Hubolog}
{9480}{}{Hubolog}
{9490}{}{Hubolog}
{9500}{}{Hubolog}
{9510}{}{Chupacabra}
{9511}{}{Better run!}
{9520}{}{Aberration}
{9530}{}{Patrol leader}
{9540}{}{Vayne}
{9550}{}{Junktown Scout}
{9560}{}{Junktown Scout}
{9570}{}{Junktown Scout}
{9580}{}{Junktown Scout}
{9590}{}{Junktown Scout}
{9600}{}{Pomiot Nocy}
{9610}{}{Podejrzany człowiek w kapturze}
{9620}{}{Cyngiel Bishopa}
{9630}{}{Zbir Bishopa}
{9640}{}{Bandzior Bishopa}
{9650}{}{Wykidajło Bishopa}
{9660}{}{Syn Wright'a}
{9670}{}{Syn Wright'a}
{9680}{}{Syn Wright'a}
{9690}{}{Syn Wright'a}
{9700}{}{Herszt}
{9710}{}{26}
{9720}{}{31}
{9730}{}{40}
{9740}{}{41}
{9750}{}{43}
{9760}{}{44}
{9770}{}{45}
{9780}{}{48}
{9790}{}{56}
{9800}{}{57}
{9810}{}{62}
{9820}{}{64}
{9830}{}{72}
{9840}{}{77}
{9850}{}{78}
{9860}{}{82}
{9870}{}{87}
{9880}{}{88}
{9890}{}{Chemist}
{9900}{}{91}
{9910}{}{92}
{9920}{}{93}
{9930}{}{95}
{9940}{}{96}
{9950}{}{98}
{9960}{}{105}
{9970}{}{110}
{9980}{}{135}
{9990}{}{136}
{10000}{}{137}
{10010}{}{139}
{10020}{}{140}
{10030}{}{33}
{10040}{}{34}
{10050}{}{35}
{10060}{}{36}
{10070}{}{37}
{10080}{}{61}
{10090}{}{73}
{10100}{}{94}
{10110}{}{145}
{10120}{}{146}
{10130}{}{148}
{10140}{}{149}
{10150}{}{Furniture Scavenger}
{10160}{}{Toxic Gecko}
{10170}{}{Mature Toxic Gecko}
{10180}{}{Small Radiated Gecko}
{10190}{}{Radiated Gecko}
{10200}{}{Tough Radiated Gecko}
{10210}{}{Nightmare}
{10220}{}{Deathbringer}
{10230}{}{Caravan Leader}
{10240}{}{Vault Dweller}
{10250}{}{Tribal Leader}
{11200}{}{Mężczyzna}
{11210}{}{Kobieta}
{14000}{}{Radscorpion Egg}
{14010}{}{Ant Egg}
{14020}{}{Gecko Egg}
{14030}{}{Deathclaw Egg}
{14040}{}{Alien Egg}
{14050}{}{Centaur Egg}
