{1}{}{PID_BPACK_TENT@Uma tenda portátil, empacotada, comumente utilizada como abrigo no ambiente inóspito que é o Deserto.@@@PID_BRAHMIN_SKIN 10&PID_FIREWOOD 2@@PID_BPACK_TENT 1@exp 230 script fix_boy@fix_AnyStuff}
{50}{}{PID_ZIP_GUN@Uma pistola feita à mão, de tiro único. Min FO: 4.@@@PID_TUBE 1&PID_JUNK 1@@PID_ZIP_GUN 1@exp 35 script fix_boy@fix_AnyStuff}
{51}{}{PID_SPRINGER_RIFLE@Esta é uma espingarda de tiro único. Min FO: 5.@@@PID_JUNK 1&PID_TUBE 1&PID_FIREWOOD 1@@PID_SPRINGER_RIFLE 1@exp 50 script fix_boy@fix_AnyStuff}
{52}{}{PID_10MM_PISTOL@Uma pistola Colt 6520 10mm semi-automática. Cada acionamento do gatilho recarregará automaticamente a arma de fogo até que o cilindro esteja vazio. Disparo único usando o potente calibre de 10 mm. Min FO: 3.@@SK_SMALL_GUNS 70@PID_JUNK 1&PID_TUBE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_10MM_PISTOL 1@exp 85 script fix_boy@fix_AnyStuff}
{53}{}{PID_SHOTGUN@Uma escopeta Winchester Widowmaker com cano duplo de calibre 12. Cano curto e cabo de mogno. Min FO: 4.@@SK_SMALL_GUNS 70@PID_METAL_TRASH 1&PID_TUBE 2&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_SHOTGUN 1@exp 105 script fix_boy@fix_AnyStuff}
{54}{}{PID_SAWED_OFF_SHOTGUN@Alguém levou muito tempo para cortar os últimos centímetros do cano desta espingarda. Agora, a ampla disseminação de tiros curtos a torna perfeito para controlar a multidão de curta distância. Min FO: 4.@@SK_SMALL_GUNS 70@PID_SHOTGUN 1@PID_SPECIAL_WB1 1@PID_SAWED_OFF_SHOTGUN 1@script fix_boy@fix_AnyStuff}
{55}{}{PID_44_MAGNUM_REVOLVER@Sendo esta a arma mais poderosa do mundo, capaz de explodir sua cabeça. Min FO: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_44_MAGNUM_REVOLVER 1@exp 135 script fix_boy@fix_AnyStuff}
{56}{}{PID_44_MAGNUM_SPEEDLOADER@Uma Magnum .44 com um carregador rápido. Min FO: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_44_MAGNUM_REVOLVER 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 60 script fix_boy@fix_AnyStuff}
{57}{}{PID_DESERT_EAGLE@Uma antiga pistola Desert Eagle, magnum .44. Participou de varios filmes no final do século 20 fez desta uma das armas mais populares de todos os tempos. Min FO: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 2@PID_SPECIAL_WB1 1@PID_DESERT_EAGLE 1@exp 135 script fix_boy@fix_AnyStuff}
{58}{}{PID_DESERT_EAGLE_EXT_MAG@Uma antiga pistola Desert Eagle, magnum .44. Participou de varios filmes no final do século 20 fez desta uma das armas mais populares de todos os tempos. Foi equipada com um carregador expandido para uma diversão maior! Min FO: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_DESERT_EAGLE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 35 script fix_boy@fix_AnyStuff}
{59}{}{PID_9MM_MAUSER@Uma Mauser M/96, em 9x19mm Parabellum. Em excelente estado de conservação. Extremamente preciso. Min FO: 3.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_9MM_MAUSER 1@exp 85 script fix_boy@fix_AnyStuff}
{60}{}{PID_10MM_SMG@Sub-metralhadora H & K MP9 (variante de 10mm). A SMG de tamanho médio é capaz de: dar um tiro único e possui um modo de rajada. Min FO: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 1&PID_METAL_TRASH 3&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_10MM_SMG 1@exp 180 script fix_boy@fix_AnyStuff}
{61}{}{PID_GREASE_GUN@Esta metralhadora cheia arsenais da Guarda Nacional depois que o Exército a substituiu por armas mais recentes. No entanto, a "Grease Gun" era simples e barato de fabricar assim, há muito poucas em uso. Min FO: 4.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_JUNK 1&PID_METAL_TRASH 4@PID_SPECIAL_WB1 1@PID_GREASE_GUN 1@exp 235 script fix_boy@fix_AnyStuff}
{62}{}{PID_TOMMY_GUN@Esta é uma metralhadora Thompson M1928 uma arma de aparencia sinistra; A Thompson tem um grande tambor que cabe 50 balas. Min FO: 6.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_METAL_TRASH 3&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_TOMMY_GUN 1@exp 185 script fix_boy@fix_AnyStuff}
{63}{}{PID_COMBAT_SHOTGUN@Uma espingarda de combate Winchester City-Killer de calibre 12. Em excelentes condições, com um selante ambiental opcional DesertWarfare para maior confiabilidade. Min FO: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_FIREWOOD 1&PID_METAL_TRASH 4@PID_SPECIAL_WB1 1@PID_COMBAT_SHOTGUN 1@exp 235 script fix_boy@fix_AnyStuff}
{64}{}{PID_HUNTING_RIFLE@Um Rifle Colt Rangemaster semi-automático, de calibre .223. Min FO: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_TUBE 1&PID_FIREWOOD 1&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_HUNTING_RIFLE 1@exp 65 script fix_boy@fix_AnyStuff}
{65}{}{PID_SCOPED_HUNTING_RIFLE@Nada é melhor do que ver Aquele olhar surpreso no rosto de seu alvo. A mira x20 neste rifle de caça torna mais fácil do que nunca. Precisa do primeiro ao último tiro, não importa em que você está atirando. Min FO: 5.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_HUNTING_RIFLE 1&PID_METAL_TRASH 1@PID_SPECIAL_WB1 1@PID_SCOPED_HUNTING_RIFLE 1@exp 35 script fix_boy@fix_AnyStuff}
{66}{}{PID_14MM_PISTOL@Uma pistola automática Sig-Sauer de 14mm. Uma grande arma de disparo único. Excelente artesanato. Min FO: 4.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 2&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_14MM_PISTOL 1@exp 150 script fix_boy@fix_AnyStuff}
{67}{}{PID_NEEDLER_PISTOL@Você suspeita que esta Pistola de Ponteira uma vez foi usada para estudos científicos. Ela usa pequenos dardos hipodérmicos de plástico duro como munição. Min FO: 3.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 2&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_NEEDLER_PISTOL 1@exp 150 script fix_boy@fix_AnyStuff}
{68}{}{PID_ASSAULT_RIFLE@Um rifle de assalto AK-112 de 5mm. Um modelo militar antigo, depreciado em tempos de guerra. Pode disparar um único tiro ou explosão, usando balas de 5mm de alta velocidade. Min FO: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_FIREWOOD 2&PID_METAL_TRASH 8@PID_SPECIAL_WB1 1@PID_ASSAULT_RIFLE 1@exp 450 script fix_boy@fix_AnyStuff}
{69}{}{PID_ASSAULT_RIFLE_EXT_MAG@Este rifle de assalto tem um porte militar, cartucho de munição ampliado. A capacidade de cartucho ampliada a torna mais divertida do que nunca. Min FO: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_ASSAULT_RIFLE 1&PID_METAL_TRASH 3@PID_SPECIAL_WB1 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 100 script fix_boy@fix_AnyStuff}
{70}{}{PID_FN_FAL@Este rifle foi mais utilizado pelas forças armadas do que qualquer outro rifle na história. É uma arma de assalto confiável para qualquer tipo de terreno ou situação tática. Min FO: 5.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 1&PID_METAL_TRASH 4&PID_JUNK 1&PID_HIGH_GRADE_STEEL 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_FN_FAL 1@exp 500 script fix_boy@fix_AnyStuff}
{71}{}{PID_HK_CAWS@O CAWS, é uma abreviatura de Close Assault Weapons System, é uma espingarda útil para combates de curto alcançe. Arma projeta para um manuseio simples e curto, mas seu cano é bastante longo para disparar em alta velocidade. Min FO: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 2&PID_METAL_TRASH 10@PID_SPECIAL_WB1 1@PID_HK_CAWS 1@exp 540 script fix_boy@fix_AnyStuff}
{72}{}{PID_HK_P90C@A Heckler & Koch P90c era muito usada na época da guerra. Seu designer compacto a torna mais facil de controlar.  A durável P90c é valorizada pela sua confiabilidade e alto poder de fogo, robusto e compacto. Min FO: 4.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_HK_P90C 1@exp 420 script fix_boy@fix_AnyStuff}
{73}{}{PID_223_PISTOL@Uma rifle .223 modificado e modelado como pistola. Trata-se de uma arma única, obviamente feita com carinho e habilidade. Min FO: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_223_PISTOL 1@exp 420 script fix_boy@fix_AnyStuff}
{74}{}{PID_INDEPENDENT@Esta foi uma arma experimental na época da grande guerra. Fabricada principalmente com resistentes polímeros, a arma é praticamente indestrutível. É leve, dispara rápidamente, precisa e pode ser desmontada sem usar qualquer ferramenta. Min FO: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_KEVLAR_POLYMER 1&PID_METAL_TRASH 6&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_INDEPENDENT 1@exp 720 script fix_boy@fix_AnyStuff}
{75}{}{PID_SNIPER_RIFLE@Um rifle franco-atirador DKS-501. Uma excelente arma de longo alcance. Originalmente de calibre .308, mas foi modificado para um calibre mais comum .223. Min FO: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 5@PID_SPECIAL_WB1 1@PID_SNIPER_RIFLE 1@exp 520 script fix_boy@fix_AnyStuff}
{76}{}{PID_PANCOR_JACKHAMMER@Uma britadeira, apesar do nome, é um fácil de controlar, mesmo no modo de disparo automático. O seu designer foi projetado no estilo bullpup, quando se coloca o dedo no gatilho faz com que a arma fique equilibrada e fácil de controlar. Min FO: 5.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_TUBE 1&PID_KEVLAR_POLYMER 1&PID_METAL_TRASH 4&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_PANCOR_JACKHAMMER 1@exp 620 script fix_boy@fix_AnyStuff}
{100}{}{PID_LASER_PISTOL@Uma pistola laser de 1000 Wattz. Modelo civil, com potência menor do que as versões militares e da policía. Usa células PE de energia. Min FO: 3.@SK_ENERGY_WEAPONS 0@SK_ENERGY_WEAPONS 60|PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_LASER_PISTOL 1@exp 160 script fix_boy@fix_AnyStuff}
{101}{}{PID_MAGNETO_LASER_PISTOL@Esta pistola de laser Wattz 1000 foi atualizada com um sistema de campo magnético que afina a emissão laser, proporcionando a esta arma um poder de penetração extra. Min FO: 3.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_LASER_PISTOL 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_MAGNETO_LASER_PISTOL 1@exp 40 script fix_boy@fix_AnyStuff}
{102}{}{PID_PLASMA_PISTOL@Pistola de plasma Glock 86. Desenhado pelo Gaston Glock AI. Atira um pequeno feixe de plasma superaquecido. Desenvolvido por PE células de energia. Min FO: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_JUNK 1&PID_ELECTRONIC_PART 3@PID_SPECIAL_WB1 1@PID_PLASMA_PISTOL 1@exp 345 script fix_boy@fix_AnyStuff}
{103}{}{PID_PLASMA_PISTOL_EXT_CART@Esta Pistola de plasma Glock 86 teve sua câmara magnética reajustada para reduzir o consumo em sua célula de energia. Sua eficiência dobrou, permitindo-lhe disparar mais tiros antes que termine a bateria. Min FO: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_PLASMA_PISTOL 1&PID_METAL_TRASH 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 120 script fix_boy@fix_AnyStuff}
{104}{}{PID_LASER_RIFLE@Um rifle laser Wattz 2000. Usa celuas de micro fusão para um laser mais potente e um cano estendido para maior alcance. Min FO: 6.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 5&PID_JUNK 2&PID_ELECTRONIC_PART 6@PID_SPECIAL_WB1 1@PID_LASER_RIFLE 1@exp 640 script fix_boy@fix_AnyStuff}
{105}{}{PID_LASER_RIFLE_EXT_CAP@Este rifle de laser Wattz 2000 teve seu sistema de recarga atualizado e um chip especial instalado que a reciclagem reduz o consumo da célula micro fusão em 50%. Min FO: 6.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_LASER_RIFLE 1&PID_ENERGY_TRANSFORMER 1@PID_SPECIAL_WB1 1@PID_LASER_RIFLE_EXT_CAP 1@exp 200 script fix_boy@fix_AnyStuff}
{106}{}{PID_YK32_PULSE_PISTOL@O YK32 é uma arma de pulso elétrico que foi desenvolvido por Yuma Flats Energy Consortium. Apesar de poderosa, a YK32 nunca foi considerada uma arma prática devido ao seu uso ineficiente da energia e design volumoso. Min FO: 3.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 3&PID_ENERGY_TRANSFORMER 1@PID_SPECIAL_WB1 1@PID_YK32_PULSE_PISTOL 1@exp 630 script fix_boy@fix_AnyStuff}
{107}{}{PID_PLASMA_RIFLE@Um rifle de plasma modelo Winchester P94. Uma arma energética de grade industrial, que dispara raios de plasma superaquecido por um supercondutor. Alimentado por células MF de micro fusão. Min FO: 6.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_ENERGY_TRANSFORMER 1&PID_METAL_TRASH 4&PID_ELECTRONIC_PART 4@PID_SPECIAL_WB1 1@PID_PLASMA_RIFLE 1@exp 740 script fix_boy@fix_AnyStuff}
{130}{}{PID_FLAMER@Um Lança-Chamas modelo Flambe 450. Dispara um curto líquido inflamável extremamente quente. Requer combustível especializado para funcionar corretamente. Min FO: 6.@SK_BIG_GUNS 0@SK_BIG_GUNS 60|PE_PROF_GUNSMITH 1@PID_FIREWOOD 1&PID_TUBE 3&PID_METAL_TRASH 3&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_FLAMER 1@exp 255 script fix_boy@fix_AnyStuff}
{131}{}{PID_M60@Esta metralhadora é relativamente leve e foi muito valorizada pelos militares em todo o mundo por sua alta taxa de disparo. Esta arma é confiável e comprovada no campo de batalha, foi usado em veículos para os esquadrões de apoio de fogo. Min FO: 7.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 5&PID_TUBE 3&PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_M60 1@exp 340 script fix_boy@fix_AnyStuff}
{132}{}{PID_IMPROVED_FLAMETHROWER@Um Lança-Chamas modelo Flambe 450. Dispara um curto líquido inflamável extremamente quente. Requer combustível especializado para funcionar corretamente. Este modelo foi modificado para disparar uma mistura mais quente que causa maior combustibilidade. Min FO: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_FLAMER 1&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_IMPROVED_FLAMETHROWER 1@exp 170 script fix_boy@fix_AnyStuff}
{133}{}{PID_ROCKET_LAUNCHER@Um lançador de foguetes Rockwell BigBazooka. Com gatilho de luxo de 3 lb. Dipara foguetes explosivos. Min FO: 6.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_JUNK 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_ROCKET_LAUNCHER 1@exp 275 script fix_boy@fix_AnyStuff}
{134}{}{PID_LIGHT_SUPPORT_WEAPON@Esta arma de nível esquadrão de apoio tem um design bullpup. O design bullpup torna a arma difícil de ser usada enquanto deitado. Por isso, foi devolvido para as unidades da Guarda Nacional. Ela, no entanto, ganhou uma reputação como uma arma confiável com boa potência para o seu tamanho.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 3&PID_METAL_TRASH 4&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 410 script fix_boy@fix_AnyStuff}
{135}{}{PID_MINIGUN@Uma metralhadora pessoal Rockwell CZ53. Uma metralhadora de cano multiplo que dispara munições de 5mm a mais de 60.000 RPM. Min FO: 7.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_TUBE 6&PID_METAL_TRASH 3&PID_HIGH_GRADE_STEEL 1@PID_SPECIAL_WB1 1@PID_MINIGUN 1@exp 760 script fix_boy@fix_AnyStuff}
{136}{}{PID_AVENGER_MINIGUN@Rochawell desenhou a Vingadora para substituir o seu antigo modelo CZ53. As melhorias no projeto desta giratória que incluem refrigeração em gel e canos cromados com pequenos furos. Isto aumenta seu alcance e letalidade. Min FO: 7.@PE_PROF_GUNSMITH 3@PE_PROF_GUNSMITH 3@PID_MINIGUN 1&PID_HIGH_GRADE_STEEL 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_AVENGER_MINIGUN 1@exp 250 script fix_boy@fix_AnyStuff}
{160}{}{PID_THROWING_KNIFE@Uma faca, projetada especificamente para arremesso. Feita de titânio e afiada a laser. Min FO: 3.@@SK_THROWING 50@PID_METAL_TRASH 2&PID_FIREWOOD 2@PID_SPECIAL_WB1 1@PID_THROWING_KNIFE 10@exp 60 script fix_boy@fix_AnyStuff}
{161}{}{PID_MOLOTOV_COCKTAIL@Uma granada inflamável caseira. Min FO: 3.@@SK_THROWING 50@PID_ROT_GUT 5@PID_SPECIAL_WB1 1@PID_MOLOTOV_COCKTAIL 10@exp 75 script fix_boy@fix_AnyStuff}
{162}{}{PID_FRAG_GRENADE@Uma granada de fragmentação genérica. Contém uma pequena quantidade de explosivos, o próprio recipiente formando a maioria dos fragmentos prejudiciais. Explode em contato. Min FO: 3.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_FRAG_GRENADE 10@exp 225 script fix_boy@fix_AnyStuff}
{163}{}{PID_PLASMA_GRENADE@Uma unidade de plasma magneticamente selada, com explosivos de detonação. Explode uma rajada de plasma superaquecido em contato. Min FO: 4.@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_METAL_TRASH 4&PID_REFINED_ORE 2@PID_SPECIAL_WB1 1@PID_PLASMA_GRENADE 10@exp 300 script fix_boy@fix_AnyStuff}
{180}{}{PID_KNIFE@Uma lâmina afiada feita para corte e esfaqueamento. Min FO: 2.@@@PID_JUNK 1&PID_FIREWOOD 1@@PID_KNIFE 1@exp 30 script fix_boy@fix_AnyStuff}
{181}{}{PID_COMBAT_KNIFE@Uma faca de combate de alta qualidade de SharpWit Inc. Esta lâmina afiada tem garantia de uso por mais de uma década! Min FO: 2.@SK_UNARMED 70@SK_UNARMED 100@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_COMBAT_KNIFE 1@exp 75 script fix_boy@fix_AnyStuff}
{182}{}{PID_BRASS_KNUCKLES@Aperto da junta endurecido feito de aço. Eles protegem sua mão e causam mais danos em combate desarmado. Min FO: 1.@@@PID_JUNK 2@@PID_BRASS_KNUCKLES 1@exp 30 script fix_boy@fix_AnyStuff}
{183}{}{PID_SPIKED_KNUCKLES@Uma versão melhorada do Clássico Soqueiro Inglês. A Soqueira com espinhos faz mais danos, rasgando a carne de seu oponente em um combate desarmado. Min FO: 1.@SK_UNARMED 70@SK_UNARMED 100@PID_BRASS_KNUCKLES 1&PID_JUNK 1@@PID_SPIKED_KNUCKLES 1@exp 10 script fix_boy@fix_AnyStuff}
{184}{}{PID_CLUB@Um bastão de policial militar. Feito de madeira pesada. Min FO: 3.@SK_UNARMED 70@SK_UNARMED 100@PID_METAL_TRASH 1&PID_JUNK 1@PID_SPECIAL_WB1 1@PID_CLUB 1@exp 75 script fix_boy@fix_AnyStuff}
{185}{}{PID_SLEDGEHAMMER@Um grande martelo. Muito popular entre as pessoas fortes. Min FO: 6.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_SLEDGEHAMMER 1@exp 30 script fix_boy@fix_AnyStuff}
{186}{}{PID_SUPER_SLEDGE@Um Super Martelo forjado pela Irmandade do Aço, utilizando a tecnologia mais fina disponível. Inclui um dispositivo de armazenamento de energia cinética, para aumentar nocaute. Min FO: 5.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_FIREWOOD 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_SUPER_SLEDGE 1@exp 285 script fix_boy@fix_AnyStuff}
{187}{}{PID_SPEAR@Uma lança com a ponta bem afiada. A base é de madeira e a ponta é de aço trabalhado. Min FO: 4.@@@PID_JUNK 1&PID_FIREWOOD 1@@PID_SPEAR 1@exp 30 script fix_boy@fix_AnyStuff}
{188}{}{PID_SHARP_SPEAR@Um cabo de madeira com uma ponta de aço afiada. Min FO: 4.@@@PID_SPEAR 1&PID_FLINT 1@PID_SPECIAL_WB1 1@PID_SHARP_SPEAR 1@exp 5 script fix_boy@fix_AnyStuff}
{189}{}{PID_CATTLE_PROD@Um aparelho de tocar o gado modelo 'O melhor amigo do fazendeiro', de Wattz Electronics. Utiliza células PE de energia. Min FO: 4.@PE_PROF_SCIENTIST 1@PE_PROF_SCIENTIST 1@PID_METAL_TRASH 2&PID_JUNK 1&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_CATTLE_PROD 1@exp 235 script fix_boy@fix_AnyStuff}
{190}{}{PID_SUPER_CATTLE_PROD@Um aparelho de tocar o gado modelo 'O melhor amigo do fazendeiro', de Wattz Electronics. Este modelo foi atualizado para aumentar a descarga elétrica. Min FO: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_CATTLE_PROD 1&PID_METAL_TRASH 2&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_SUPER_CATTLE_PROD 1@exp 150 script fix_boy@fix_AnyStuff}
{191}{}{PID_RIPPER@Uma motoserra Estripadora(TM). Alimentada por uma PE célula de energia, a motoserra estripa e rasga seu alvo. Min FO: 4.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_RIPPER 1@exp 270 script fix_boy@fix_AnyStuff}
{192}{}{PID_POWER_FIST@Uma Manopla de energia de BeatCo. Considerada por muitos como a melhor arma de uso em combate desarmado. As outras apenas assustam. Desenvolvido por células de energia de pequeno porte. Min FO: 1.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_ELECTRONIC_PART 2&PID_REFINED_ORE 1@PID_SPECIAL_WB1 1@PID_POWER_FIST 1@exp 380 script fix_boy@fix_AnyStuff}
{193}{}{PID_MEGA_POWER_FIST@Uma manopla de energia de BeatCo. Considerada por muitos como a melhor arma de uso em combate desarmado. Esta versão foi melhorada para uma maior resistência. Desenvolvido por células de energia de pequeno porte. Min FO: 1@PE_PROF_SCIENTIST 3@PE_PROF_SCIENTIST 3@PID_POWER_FIST 1&PID_METAL_TRASH 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_MEGA_POWER_FIST 1@exp 110 script fix_boy@fix_AnyStuff}
{210}{}{PID_LEATHER_JACKET@Uma jaqueta preta, pesada, de couro.@@SK_OUTDOORSMAN 20@PID_CORD 1&PID_JUNK 1&PID_BRAHMIN_SKIN 1@PID_SPECIAL_WB1 1@PID_LEATHER_JACKET 1@exp 55 script fix_boy@fix_AnyStuff}
{211}{}{PID_CURED_LEATHER_ARMOR@Esta jaqueta de couro fortemente acolchoadas é incomum, pois tem duas mangas. Definitivamente você vai fazer um desfile de moda quando e onde você quiser e vai arrasar.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 2&PID_JUNK 1&PID_BRAHMIN_SKIN 2&PID_LEATHER_JACKET 1@PID_SPECIAL_WB1 1@PID_CURED_LEATHER_ARMOR 1@exp 50 script fix_boy@fix_AnyStuff}
{212}{}{PID_LEATHER_ARMOR@Uma roupa de couro. Finamente trabalhada a partir de couro curtido de brahmin.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 1&PID_GECKO_PELT 3&PID_GOLDEN_GECKO_PELT 1@PID_SPECIAL_WB1 1@PID_LEATHER_ARMOR 1@exp 170 script fix_boy@fix_AnyStuff}
{213}{}{PID_LEATHER_ARMOR_MK_II@Uma versão melhorada da básica Leather Armor com uma capa extra de proteção. Finamente trabalhada com couro curtido brahmin.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_CORD 1&PID_GOLDEN_GECKO_PELT 2&PID_LEATHER_ARMOR 1@PID_SPECIAL_WB1 1@PID_LEATHER_ARMOR_MK_II 1@exp 100 script fix_boy@fix_AnyStuff}
{214}{}{PID_METAL_ARMOR@Placas de metal polidas, presas de forma grosseira a dar forma à uma armadura.@PE_PROF_ARMORER 1@PE_PROF_ARMORER 1@PID_JUNK 1&PID_METAL_TRASH 4&PID_BRAHMIN_SKIN 1@PID_SPECIAL_WB1 1@PID_METAL_ARMOR 1@exp 235 script fix_boy@fix_AnyStuff}
{215}{}{PID_METAL_ARMOR_MK_II@Placas de metal polidas, presas manualmente em uma armadura.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_HIGH_GRADE_STEEL 1&PID_METAL_ARMOR 1@PID_SPECIAL_WB1 1@PID_METAL_ARMOR_MK_II 1@exp 180 script fix_boy@fix_AnyStuff}
{216}{}{PID_TESLA_ARMOR@Uma armadura com tecnologia avançada. Alimentado por um reator de micro-fusão, com combustível suficiente para durar cem anos.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_ENERGY_TRANSFORMER 1&PID_ELECTRONIC_PART 1&PID_METAL_ARMOR_MK_II 1@PID_SPECIAL_WB1 1@PID_TESLA_ARMOR 1@exp 360 script fix_boy@fix_AnyStuff}
{217}{}{PID_COMBAT_ARMOR@Armadura de alta tecnologia, feito de polímeros defensivas avançadas.@PE_PROF_ARMORER 2@PE_PROF_ARMORER 2@PID_KEVLAR_POLYMER 3&PID_BRAHMIN_SKIN 1&PID_CORD 3@PID_SPECIAL_WB1 1@PID_COMBAT_ARMOR 1@exp 530 script fix_boy@fix_AnyStuff}
{218}{}{PID_COMBAT_ARMOR_MK_II@Armadura de alta tecnologia, feito de polímeros defensivas avançadas.@PE_PROF_ARMORER 3@PE_PROF_ARMORER 3@PID_KEVLAR_POLYMER 2&PID_METAL_TRASH 3&PID_COMBAT_ARMOR 1@PID_SPECIAL_WB1 1@PID_COMBAT_ARMOR_MK_II 1@exp 380 script fix_boy@fix_AnyStuff}
{219}{}{PID_BLACK_ROBE@Uma túnica feita de materiais de ponta de design Centrologista cujo absorve fótons dando um efeito de camuflagem.@PE_PROF_ARMORER 3@PE_PROF_ARMORER 3@PID_CORD 4&PID_CHEMICAL_COMPONENTS 2&PID_KEVLAR_POLYMER 2&PID_FIRE_GECKO_PELT 2@PID_SPECIAL_WB1 1@PID_BLACK_ROBE 1@exp 540 script fix_boy@fix_AnyStuff}
{240}{}{PID_10MM_JHP@Munições calibre: 10mm, ponta oca e jaqueta metálica@@@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_10MM_JHP 100@exp 155 script fix_boy@fix_AnyStuff}
{241}{}{PID_10MM_AP@Munições calibre: 10mm, perfurante.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_10MM_AP 100@exp 275 script fix_boy@fix_AnyStuff}
{242}{}{PID_SHOTGUN_SHELLS@Munição de escopeta. Esta munição especial indica que: "munição 12, proibido para crianças com idade inferior a 3 anos."@@@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_SHOTGUN_SHELLS 100@exp 155 script fix_boy@fix_AnyStuff}
{243}{}{PID_FLAMETHROWER_FUEL@Um cilindro contendo um combustível líquido extremamente inflamável para lança-chamas.@@@PID_ROT_GUT 5@PID_SPECIAL_WB1 1@PID_FLAMETHROWER_FUEL 30@exp 75 script fix_boy@fix_AnyStuff}
{244}{}{PID_FLAMETHROWER_FUEL_MK_II@Este combustível para lança-chamas utiliza um mix avançado de super-combustíveis@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_CHEMICAL_COMPONENTS 1&PID_FLAMETHROWER_FUEL 30@PID_SPECIAL_WB1 1@PID_FLAMETHROWER_FUEL_MK_II 30@exp 60 script fix_boy@fix_AnyStuff}
{245}{}{PID_SMALL_ENERGY_CELL@A small, self-contained energy storage unit.@@@PID_METAL_TRASH 2&PID_ELECTRONIC_PART 2&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_SMALL_ENERGY_CELL 50@exp 250 script fix_boy@fix_AnyStuff}
{246}{}{PID_44_MAGNUM_JHP@Munições calibre: .44 Magnum, ponta oca.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_44_MAGNUM_JHP 100@exp 155 script fix_boy@fix_AnyStuff}
{247}{}{PID_44_FMJ_MAGNUM@Munição de calibre .44 para magnum, com jaqueta metálica.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_44_FMJ_MAGNUM 100@exp 275 script fix_boy@fix_AnyStuff}
{248}{}{PID_9MM_BALL@Uma coleção de antigas balas 9x19mm. Contem um monte de graxa para preservá-los do ambiente. Balas padrão.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 3@PID_SPECIAL_WB1 1@PID_9MM_BALL 100@exp 105 script fix_boy@fix_AnyStuff}
{249}{}{PID_45_CALIBER_AMMO@Munições calibre .45.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_JUNK 2&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_45_CALIBER_AMMO 100@exp 30 script fix_boy@fix_AnyStuff}
{250}{}{PID_223_FMJ@Uma cartucheira de munições calibre .223, com jaqueta metálica.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_JUNK 2&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_223_FMJ 100@exp 330 script fix_boy@fix_AnyStuff}
{251}{}{PID_7_62MM_AMMO@Munições calibre: 7.62mm.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 3&PID_JUNK 2&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_7_62MM_AMMO 100@exp 330 script fix_boy@fix_AnyStuff}
{252}{}{PID_EXPLOSIVE_ROCKET@Um foguete com uma grande ogiva explosiva.@PE_PROF_GUNSMITH 1@PE_PROF_GUNSMITH 1@PID_METAL_TRASH 6&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_EXPLOSIVE_ROCKET 10@exp 425 script fix_boy@fix_AnyStuff}
{253}{}{PID_ROCKET_AP@Um colete com explosivo de baixa potência, desenhado para perfurar blindagens.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 8&PID_GUNPOWDER 6&PID_ELECTRONIC_PART 2@PID_SPECIAL_WB1 1@PID_ROCKET_AP 10@exp 670 script fix_boy@fix_AnyStuff}
{254}{}{PID_14MM_AP@Munições de grande calibre. 14mm perfurante.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_14MM_AP 100@exp 325 script fix_boy@fix_AnyStuff}
{255}{}{PID_HN_NEEDLER_CARTRIDGE@Munições. Este cartucho parece ser munição para "Pistola de Ponteiras". Cada 'bala' é uma pequena seringa projetada para injetar seu conteúdo no momento do impacto.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 3&PID_GUNPOWDER 5@PID_SPECIAL_WB1 1@PID_HN_NEEDLER_CARTRIDGE 100@exp 275 script fix_boy@fix_AnyStuff}
{257}{}{PID_5MM_JHP@Uma munição peso-leve. Calibre: 5mm, de ponta oca e jaqueta metálica.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 4&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_5MM_JHP 100@exp 350 script fix_boy@fix_AnyStuff}
{258}{}{PID_5MM_AP@Municões de pequeno calibre. 5mm perfurante.@PE_PROF_GUNSMITH 2@PE_PROF_GUNSMITH 2@PID_METAL_TRASH 6&PID_GUNPOWDER 6@PID_SPECIAL_WB1 1@PID_5MM_AP 100@exp 450 script fix_boy@fix_AnyStuff}
{259}{}{PID_MICRO_FUSION_CELL@Uma unidade de produção de energia de tamanho médio. com reator de fusão autônomo.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_SMALL_ENERGY_CELL 100@PID_SPECIAL_WB1 1@PID_MICRO_FUSION_CELL 30@exp 100 script fix_boy@fix_AnyStuff}
{260}{}{PID_MICRO_FUSION_CELL@Uma unidade de produção de energia de tamanho médio. com reator de fusão autônomo.@PE_PROF_SCIENTIST 2@PE_PROF_SCIENTIST 2@PID_METAL_TRASH 3&PID_REFINED_ORE 3@PID_SPECIAL_WB1 1@PID_MICRO_FUSION_CELL 100@exp 450 script fix_boy@fix_AnyStuff}
{280}{}{PID_METAL_TRASH@Algumas partes de metal que podem ser usadas para montar algo.@@@PID_METAL_ORE 2@PID_SPECIAL_WB1 1|PID_SPECIAL_WB2 1@PID_METAL_TRASH 1@exp 20 script fix_boy@fix_AnyStuff}
{281}{}{PID_GUNPOWDER@Uma caixa de pólvora negra.@@@PID_MINERAL 2@PID_SPECIAL_WB1 1|PID_SPECIAL_WB2 1@PID_GUNPOWDER 1@exp 20 script fix_boy@fix_AnyStuff}
{282}{}{PID_ROT_GUT@Uma bebida bem forte ou um líquido para limpeza, você decide.@@@PID_MUTATED_FRUIT 5&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_ROT_GUT 5@exp 40 script fix_boy@fix_AnyStuff}
{283}{}{PID_CIGARETTES@Cigarros absolutamente comuns do mundo pós-nuclear enrolados a mão guardados em uma estilosa caixa de cigarros "Nukeboro".@@@PID_TOBACCO 1&PID_TORN_PAPER 5@PID_SPECIAL_WB1 1@PID_CIGARETTES 1@exp 105 script fix_boy@fix_AnyStuff}
{284}{}{PID_HEALING_POWDER@Um poderoso pó mágico de cura. Causa sonolência.@@@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@@PID_HEALING_POWDER 1@exp 10 script fix_boy@fix_AnyStuff}
{285}{}{PID_ANTIDOTE@Uma garrafa contendo um antídoto caseiro para o veneno. Um líquido leitoso com pedaços flutuantes de carne de radscorpião.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_SCORPION_TAIL 2@@PID_ANTIDOTE 1@exp 20 script fix_boy@fix_AnyStuff}
{286}{}{PID_STIMPAK@Um produto químico de cura quando injetada, a bioquímica fornece cura imediata de pequenas feridas.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_HYPODERMIC_NEEDLE 1@PID_SPECIAL_WB1 1@PID_STIMPAK 1@exp 20 script fix_boy@fix_AnyStuff}
{287}{}{PID_SUPER_STIMPAK@Um avançado produto químico de cura. Muito poderoso. Super Estimulante irá causar uma pequena quantidade de danos após um período de tempo, devido à natureza potente dos produtos químicos utilizados.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_BROC_FLOWER 2&PID_XANDER_ROOT 2&PID_CHEMICAL_COMPONENTS 2&PID_HYPODERMIC_NEEDLE 5@PID_SPECIAL_WB1 1@PID_SUPER_STIMPAK 5@exp 270 script fix_boy@fix_AnyStuff}
{288}{}{PID_MENTATS@Uma caixa de comprimidos que alteram a mente. Aumenta funções relacionadas a memória e acelera outros processos mentais. Altamente viciante.@PE_PROF_CHEMIST 1@PE_PROF_CHEMIST 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_MUTATED_FRUIT 5&PID_CHEMICAL_COMPONENTS 1@PID_SPECIAL_WB1 1@PID_MENTATS 1@exp 135 script fix_boy@fix_AnyStuff}
{289}{}{PID_RADAWAY@Uma solução química que elimina partículas de radiação de seus sistema. Leva tempo para fazer efeito.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_CHEMICAL_COMPONENTS 1&PID_HYPODERMIC_NEEDLE 1&PID_XANDER_ROOT 2&PID_ROENTGEN_RUM 2@PID_SPECIAL_WB1 1@PID_RADAWAY 1@exp 140 script fix_boy@fix_AnyStuff}
{290}{}{PID_RAD_X@Produto químico Anti-radiação deve ser tomado antes da exposição. Efeitos colaterais desconhecidos.@PE_PROF_CHEMIST 2@PE_PROF_CHEMIST 2@PID_CHEMICAL_COMPONENTS 1&PID_GAMMA_GULP_BEER 2&PID_BROC_FLOWER 2@PID_SPECIAL_WB1 1@PID_RAD_X 1@exp 130 script fix_boy@fix_AnyStuff}
{291}{}{PID_PSYCHO@Um elemento único com produtos químicos estranhos e desconhecidos, provavelmente de origem militar. Supõe-se que é para aumentar a potencial de combate de um soldado.@PE_PROF_CHEMIST 3@PE_PROF_CHEMIST 3@PID_CHEMICAL_COMPONENTS 6&PID_HYPODERMIC_NEEDLE 1@PID_SPECIAL_WB1 1@PID_PSYCHO 1@exp 610 script fix_boy@fix_AnyStuff}
{292}{}{PID_BUFFOUT@Esteróides altamente avançados. Quando fazem efeito aumentam a força e reflexos. Muito viciante.@PE_PROF_CHEMIST 3@PE_PROF_CHEMIST 3@PID_CHEMICAL_COMPONENTS 3@PID_SPECIAL_WB1 1@PID_BUFFOUT 1@exp 300 script fix_boy@fix_AnyStuff}
{293}{}{PID_JET@Jet é uma poderosa metanfetamina que estimula o sistema nervoso central. A euforia inicial raramente dura mais do que alguns minutos, mas durante esse tempo, o usuário é preenchido com uma onda de energia e força.@PE_PROF_CHEMIST 3@PE_PROF_CHEMIST 3@PID_CHEMICAL_COMPONENTS 3@PID_SPECIAL_WB1 1@PID_JET 1@exp 300 script fix_boy@fix_AnyStuff}
{309}{}{PID_PICKAXE@Uma picareta qualquer, utilizada é utilizada para atividade relacionados a mineração. Simples, porém efetivo.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_PICKAXE 1@exp 30 script fix_boy@fix_AnyStuff}
{310}{}{PID_AXE@Machado desgastado, embora sua lâmina ainda esteja em boas condições.@@@PID_JUNK 1&PID_FIREWOOD 1@PID_SPECIAL_WB1 1@PID_AXE 1@exp 30 script fix_boy@fix_AnyStuff}
{311}{}{PID_ROPE@Uma corda forte e grossa. Cerca de 45 metros de comprimento.@@@PID_CORD 3@PID_SPECIAL_WB1 1@PID_ROPE 1@exp 60 script fix_boy@fix_AnyStuff}
{312}{}{PID_LOCKPICKS@Um conjunto de ferramentas de serralheiro. Com tudo que é necessário para abrir fechaduras convencionais.@@@PID_METAL_TRASH 1&PID_JUNK 2@PID_SPECIAL_WB1 1@PID_LOCKPICKS 1@exp 70 script fix_boy@fix_AnyStuff}
{313}{}{PID_FLARE@Um sinalizador. Cria uma luz durante um curto período de tempo. O papel está um pouco desgastado, mas está em boas condições. Gire a parte superior para ativá-lo. Está aceso.@@SK_SCIENCE 30@PID_CHEMICAL_COMPONENTS 2&PID_MINERAL 1&PID_TUBE 1@PID_SPECIAL_WB1 1@PID_FLARE 1@exp 125 script fix_boy@fix_AnyStuff}
{314}{}{PID_RADIO@Modelo 2043B Radio Communicator, de uma excelente marca Wattz Electronics. Confiável, robusto e camuflados. Com interface opcional RS-121.@@SK_REPAIR 30@PID_JUNK 1&PID_ELECTRONIC_PART 1@PID_SPECIAL_WB1 1@PID_RADIO 1@exp 75 script fix_boy@fix_AnyStuff}
{315}{}{PID_PRIMITIVE@Rocha atachada em um pedaço de madeirado jeito mais rústico possível, pode ser útil como ferramenta para várias tarefas.@@@PID_FLINT 1@@PID_PRIMITIVE 1@exp 5 script fix_boy@fix_AnyStuff}
{316}{}{PID_MOVABLE_AMMO_BOX_L1@Uma caixa de madeira para armazenar munição.@@@PID_FIREWOOD 20&PID_CORD 5&PID_METAL_TRASH 8@@PID_MOVABLE_AMMO_BOX_L1 1@exp 800 script fix_boy@fix_AnyStuff}
{317}{}{PID_MOVABLE_AMMO_BOX_S1@Uma caixa de madeira para armazenar munição.@@@PID_FIREWOOD 10&PID_CORD 2&PID_METAL_TRASH 4@@PID_MOVABLE_AMMO_BOX_S1 1@exp 390 script fix_boy@fix_AnyStuff}
{318}{}{PID_MOVABLE_POOR_BOX@Uma caixinha doações.@@@PID_FIREWOOD 5&PID_CORD 3@@PID_MOVABLE_POOR_BOX 1@exp 135 script fix_boy@fix_AnyStuff}
{319}{}{PID_MOVABLE_CHEST@Um baú de madeira.@@@PID_FIREWOOD 15&PID_CORD 5@@PID_MOVABLE_CHEST 1@exp 325 script fix_boy@fix_AnyStuff}
{329}{}{PID_MOVABLE_CRATE@Um baú de madeira.@@@PID_FIREWOOD 10&PID_CORD 5@@PID_MOVABLE_CRATE 1@exp 250 script fix_boy@fix_AnyStuff}
{330}{}{PID_MOVABLE_FOOTLOCKER1@Um baú. Armazena coisas.@@@PID_METAL_TRASH 12@PID_SPECIAL_WB1 1@PID_MOVABLE_FOOTLOCKER1 1@exp 600 script fix_boy@fix_AnyStuff}
{331}{}{PID_MOVABLE_LOCKER1@Um contêiner de armazenamento.@@@PID_METAL_TRASH 18@PID_SPECIAL_WB1 1@PID_MOVABLE_LOCKER1 1@exp 900 script fix_boy@fix_AnyStuff}
{332}{}{PID_MOVABLE_SAFE@Um cofre pesado de metal.@@@PID_METAL_TRASH 25@PID_SPECIAL_WB1 1@PID_MOVABLE_SAFE 1@exp 1250 script fix_boy@fix_AnyStuff}
{401}{}{PID_YK42B_PULSE_RIFLE@O YK42B é uma arma de pulso elétrico que foi desenvolvido por Yuma Flats Energy Consortium. Considera-se uma arma muito superior a pistola YK32, tendo uma maior capacidade de carga e alcance.@@@PID_YK42B_PULSE_RIFLE_RECIPE 1&PID_PARTICLE_ACCELERATOR 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 3&PID_METAL_TRASH 6@PID_T4_WBSierra 1@PID_YK42B_PULSE_RIFLE 1@exp 1000 script fix_boy@fix_Sierra}
{402}{}{PID_GATLING_LASER@Uma Gatling Laser L30 H & K. Projetado especificamente para uso militar, estava em fase de protótipo no início da guerra. Seus multiplos barris permitem mais tiros sem superaquecimento. Desenvolvido para células de Micro Fusão.@@@PID_GATLING_LASER_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 4&PID_METAL_TRASH 8@PID_T4_WBSierra 1@PID_GATLING_LASER 1@exp 1000 script fix_boy@fix_Sierra}
{403}{}{PID_BOZAR@O aperfeiçoamento da arte do franco-atirador. Embora, um pouco meticuloso e propenso a interferência se não for mantida rigorosamente limpas, a grande precisão deste rifle compensa os seus requisitos de manutenção extra.@@@PID_BOZAR_RECIPE 1&PID_RECOIL_COMPENSATOR 1&PID_TELESCOPIC_SIGHTS 1&PID_HIGH_GRADE_STEEL 4&PID_METAL_TRASH 10@PID_T4_WBSierra 1@PID_BOZAR 1@exp 1000 script fix_boy@fix_Sierra}
{404}{}{PID_VINDICATOR_MINIGUN@Rockwell desenhou a Vingadora para substituir o seu antigo modelo CZ53. As melhorias no projeto desta giratória que incluem refrigeração em gel e canos cromados com pequenos furos.@@@PID_VINDICATOR_MINIGUN_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_ROTARY_CHAMBER 1&PID_HIGH_GRADE_STEEL 3&PID_METAL_TRASH 8@PID_T4_WBSierra 1@PID_VINDICATOR_MINIGUN 1@exp 1000 script fix_boy@fix_Sierra}
{405}{}{PID_HK_G11@Esta arma revolucionou o designer de armamentos para esquadrões de apoio. Dispara cartuchos sem deformar a bala, constituído por um bloco de propulsor com uma bala no interior. O peso e a economia de espaço permite que ela tenha uma alta capacidade de carga.@@@PID_HK_G11_RECIPE 1&PID_ROTARY_CHAMBER 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 2&PID_METAL_TRASH 8&PID_TUBE 1@PID_T4_WBSierra 1@PID_HK_G11 1@exp 1000 script fix_boy@fix_Sierra}
{406}{}{PID_HK_G11E@Esta arma revolucionou o designer de armamentos para esquadrões de apoio. Dispara cartuchos sem deformar a bala, constituído por um bloco de propulsor com uma bala no interior. O peso e a economia de espaço permite que ela tenha uma alta capacidade de carga.@@@PID_HK_G11E_RECIPE 1&PID_HK_G11 1&PID_ELECTRONIC_FIRE_MECHANISM 1@PID_T4_WBSierra 1@PID_HK_G11E 1@exp 1000 script fix_boy@fix_Sierra}
{407}{}{PID_PK12_GAUSS_PISTOL@Elogiada por seu alcance e poder incomparavel, a PPK12 Gauss Pistol é de design alemão. Impulsiona um campo eletromagnético a uma velocidade tremenda e atravessa quase todas as armaduras. @@@PID_PPK12_GAUSS_PISTOL_RECIPE 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_PARTICLE_ACCELERATOR 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 6@PID_T4_WBSierra 1@PID_PK12_GAUSS_PISTOL 1@exp 1000 script fix_boy@fix_Sierra}
{408}{}{PID_M72_GAUSS_RIFLE@O M72 tem um design alemão. Impulsiona um campo eletromagnético a uma velocidade tremenda... e penetram em quase qualquer obstáculo. Seu longo alcance, precisão e poder de fogo são quase incomparáveis.@@@PID_M72_GAUSS_RIFLE_RECIPE 1&PID_PK12_GAUSS_PISTOL 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 4&PID_TUBE 1@PID_T4_WBSierra 1@PID_M72_GAUSS_RIFLE 1@exp 1000 script fix_boy@fix_Sierra}
{409}{}{PID_POWERED_ARMOR@Uma armadura com tecnologia avançada. Alimentado por um reator de micro-fusão, com combustível suficiente para durar cem anos.@@@PID_POWER_ARMOR_SHELL 1&PID_HIFLO_HYDRAULIC 1&PID_MICRO_FUSION_PACK 1&PID_TECHNICAL_MANUAL 1@PID_T4_WBSierra 1@PID_POWERED_ARMOR 1@exp 1000 script fix_boy@fix_Sierra}
{410}{}{PID_ADVANCED_POWER_ARMOR@Esta armadura potente é composta por ligas metálicas leves, reforçadas com peças fundidas de cerâmica em pontos-chave. Os servo-motores ajudam no movimento, também parecem ser modelos de alta qualidade.@@@PID_ADVANCED_POWER_ARMOR_SHELL 1&PID_IMPROVED_SERVOS 1&PID_MICRO_FUSION_PACK 1&PID_ADVANCED_POWER_ARMOR_MANUAL 1@PID_T4_WBSierra 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000 script fix_boy@fix_Sierra}
{411}{}{PID_YK42B_PULSE_RIFLE@O YK42B é uma arma de pulso elétrico que foi desenvolvido por Yuma Flats Energy Consortium. Considera-se uma arma muito superior a pistola YK32, tendo uma maior capacidade de carga e alcance.@@@PID_YK42B_PULSE_RIFLE_RECIPE 1&PID_PARTICLE_ACCELERATOR 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 3&PID_METAL_TRASH 6&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_YK42B_PULSE_RIFLE 1@exp 1000 script fix_boy@fix_Vault}
{412}{}{PID_GATLING_LASER@Uma Gatling Laser L30 H & K. Projetado especificamente para uso militar, estava em fase de protótipo no início da guerra. Seus multiplos barris permitem mais tiros sem superaquecimento. Desenvolvido para células de Micro Fusão.@@@PID_GATLING_LASER_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_EMISSION_CONCENTRATOR 1&PID_ENERGY_TRANSFORMER 4&PID_METAL_TRASH 8&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_GATLING_LASER 1@exp 1000 script fix_boy@fix_Vault}
{413}{}{PID_BOZAR@O aperfeiçoamento da arte do franco-atirador. Embora, um pouco meticuloso e propenso a interferência se não for mantida rigorosamente limpas, a grande precisão deste rifle compensa os seus requisitos de manutenção extra.@@@PID_BOZAR_RECIPE 1&PID_RECOIL_COMPENSATOR 1&PID_TELESCOPIC_SIGHTS 1&PID_HIGH_GRADE_STEEL 4&PID_METAL_TRASH 10&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_BOZAR 1@exp 1000 script fix_boy@fix_Vault}
{414}{}{PID_VINDICATOR_MINIGUN@he German Rheinmetal AG company created the ultimate minigun. The Vindicator throws over 90,000 caseless shells per minute down its six carbon-polymer barrels. As the pinnacle of Teutonic engineering skill, it is the ultimate hand-held weapon.@@@PID_VINDICATOR_MINIGUN_RECIPE 1&PID_TITANIUM_BARRELS 1&PID_ROTARY_CHAMBER 1&PID_HIGH_GRADE_STEEL 3&PID_METAL_TRASH 8&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_VINDICATOR_MINIGUN 1@exp 1000 script fix_boy@fix_Vault}
{415}{}{PID_HK_G11@Esta arma revolucionou o designer de armamentos para esquadrões de apoio. Dispara cartuchos sem deformar a bala, constituído por um bloco de propulsor com uma bala no interior. O peso e a economia de espaço permite que ela tenha uma alta capacidade de carga.@@@PID_HK_G11_RECIPE 1&PID_ROTARY_CHAMBER 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 2&PID_METAL_TRASH 8&PID_TUBE 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_HK_G11 1@exp 1000 script fix_boy@fix_Vault}
{416}{}{PID_HK_G11E@Esta arma revolucionou o designer de armamentos para esquadrões de apoio. Dispara cartuchos sem deformar a bala, constituído por um bloco de propulsor com uma bala no interior. O peso e a economia de espaço permite que ela tenha uma alta capacidade de carga.@@@PID_HK_G11E_RECIPE 1&PID_HK_G11 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_HK_G11E 1@exp 1000 script fix_boy@fix_Vault}
{417}{}{PID_PK12_GAUSS_PISTOL@Elogiada por seu alcance e poder incomparavel, a PPK12 Gauss Pistol é de design alemão. Impulsiona um campo eletromagnético a uma velocidade tremenda e atravessa quase todas as armaduras.@@@PID_PPK12_GAUSS_PISTOL_RECIPE 1&PID_ELECTRONIC_FIRE_MECHANISM 1&PID_PARTICLE_ACCELERATOR 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 6&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_PK12_GAUSS_PISTOL 1@exp 1000 script fix_boy@fix_Vault}
{418}{}{PID_M72_GAUSS_RIFLE@O M72 tem um design alemão. Impulsiona um campo eletromagnético a uma velocidade tremenda... e penetram em quase qualquer obstáculo. Seu longo alcance, precisão e poder de fogo são quase incomparáveis.@@@PID_M72_GAUSS_RIFLE_RECIPE 1&PID_PK12_GAUSS_PISTOL 1&PID_BOLT_ASSIST 1&PID_HIGH_GRADE_STEEL 1&PID_METAL_TRASH 4&PID_TUBE 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_M72_GAUSS_RIFLE 1@exp 1000 script fix_boy@fix_Vault}
{419}{}{PID_POWERED_ARMOR@Uma armadura com tecnologia avançada. Alimentado por um reator de micro-fusão, com combustível suficiente para durar cem anos.@@@PID_POWER_ARMOR_SHELL 1&PID_HIFLO_HYDRAULIC 1&PID_MICRO_FUSION_PACK 1&PID_TECHNICAL_MANUAL 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_POWERED_ARMOR 1@exp 1000 script fix_boy@fix_Vault}
{420}{}{PID_ADVANCED_POWER_ARMOR@Esta armadura potente é composta por ligas metálicas leves, reforçadas com peças fundidas de cerâmica em pontos-chave. Os servo-motores ajudam no movimento, também parecem ser modelos de alta qualidade.@@@PID_ADVANCED_POWER_ARMOR_SHELL 1&PID_IMPROVED_SERVOS 1&PID_MICRO_FUSION_PACK 1&PID_ADVANCED_POWER_ARMOR_MANUAL 1&PID_BOTTLE_CAPS 100000@PID_T4_WBVault 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000 script fix_boy@fix_Vault}
{500}{}{PID_CATS_PAW@ONLY FOR SCIENCING@ST_STRENGTH 200@ST_STRENGTH 200@PID_TORN_PAPER 3@PID_SPECIAL_WB1 1@PID_CATS_PAW 1@script fix_boy@fix_AnyStuff}
