{10}{}{Herói}
{20}{}{Heroína}
{30}{}{Aldeão}
{40}{}{Aldeã}
{50}{}{Radscorpião}
{51}{}{Um pequeno escopião mutante.}
{60}{}{Radscorpião}
{61}{}{Um escorpião mutado.}
{70}{}{Pequeno Iucapiã}
{71}{}{Um Iucapiã jovem.}
{80}{}{Iucapiã Macho Alfa}
{81}{}{O predador mais perigoso do deserto.}
{90}{}{Cão}
{91}{}{Um canino, provavelmente de uma raça mista.}
{100}{}{Brahmin}
{101}{}{Vaca mutante de duas cabeças.}
{110}{}{Rato gigante}
{111}{}{Um grande e típico rato.}
{120}{}{Mantis}
{121}{}{Um mantis mutante.}
{130}{}{Anciã}
{140}{}{Hakunin}
{150}{}{Mynoc}
{160}{}{Planta de esporas}
{161}{}{Uma planta carnivora.}
{170}{}{Escrava charmosa}
{180}{}{Escravo charmoso}
{190}{}{Escrava saudável}
{200}{}{Escravo saudável}
{210}{}{Escrava forte}
{220}{}{Escravo forto}
{230}{}{Escrava de combate}
{240}{}{Escravo de combate}
{250}{}{Escrava Inteligente}
{260}{}{Escravo Inteligente}
{270}{}{Escrava qualquer}
{280}{}{Escravo qualquer}
{290}{}{Anna}
{300}{}{Bandida forte}
{310}{}{Bandido forte}
{320}{}{Bandida lutadora}
{330}{}{Bandida lutadora}
{340}{}{Bandida ágil}
{350}{}{Bandido ágil}
{360}{}{Bandida armada}
{370}{}{Bandido armado}
{380}{}{Bandida muito bem armada}
{390}{}{Bandido muito bem armado}
{400}{}{Guarda forte}
{410}{}{Guarda forte}
{420}{}{Guarda desarmada}
{430}{}{Guarda desarmado}
{440}{}{Guarda ágil}
{450}{}{Guarda ágil}
{460}{}{Guarda armada}
{470}{}{Guarda armado}
{480}{}{Guarda muito bem armada}
{490}{}{Guarda muito bem armado}
{500}{}{Órfão}
{510}{}{Órfã}
{520}{}{Menino}
{530}{}{Menina}
{540}{}{Oário}
{550}{}{Otária}
{560}{}{Vendedor ruim}
{570}{}{Vendedor ruim}
{580}{}{Vendedor mais ou menos}
{590}{}{Vendedor mais ou menos}
{600}{}{Bom vendedor}
{610}{}{Bom vendedor}
{620}{}{Vic}
{630}{}{Pessoa}
{640}{}{Pessoa}
{650}{}{Pessoa}
{660}{}{Pessoa}
{670}{}{Pessoa}
{680}{}{Pessoa}
{690}{}{Guarda}
{700}{}{Guarda}
{710}{}{Guarda}
{720}{}{Guarda}
{730}{}{Robô de Reparos}
{740}{}{Robô de Reparos Mark II}
{750}{}{Robôneural}
{760}{}{Vigia}
{770}{}{Sentinela}
{780}{}{Sentinela Mark II}
{790}{}{Robôneural}
{800}{}{Kalango-de-prata}
{810}{}{Kalanguinho forte}
{820}{}{Cão selvagem}
{821}{}{Um cão feroz de raça mista.}
{830}{}{Kalango-dourado}
{840}{}{Iucapiã}
{850}{}{Prole Iucapiã}
{860}{}{Kalango-dourado forte}
{870}{}{Lynette}
{880}{}{Dr. Mórbido}
{890}{}{John Cassidy}
{900}{}{Gregório}
{910}{}{Cidadão}
{920}{}{Cidadã}
{930}{}{Cidadão da alta sociedade}
{940}{}{Cidadã da alta sociedade}
{950}{}{Caçador}
{960}{}{Caçadora}
{970}{}{Sulik}
{980}{}{Maida Buckner}
{990}{}{Torr}
{1000}{}{Lumpy}
{1010}{}{Luminescente do Reator}
{1020}{}{Carniçal do reator}
{1030}{}{Guarda do reator}
{1040}{}{Zomak}
{1050}{}{Skeeter}
{1060}{}{O Cérebro}
{1070}{}{Lenny}
{1080}{}{Wooz}
{1090}{}{Harold}
{1100}{}{Ratoupeira}
{1110}{}{Ratoupeira}
{1120}{}{Rato-porco}
{1130}{}{Rato-porco forte}
{1140}{}{Brahmin fraco}
{1141}{}{Uma vaca mutante de duas cabeças.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Rato mutante}
{1161}{}{Um rato mutante bem forte.}
{1170}{}{Ratoupeira mutante}
{1171}{}{Um Ratoupeira bem forte.}
{1180}{}{Rato-porco mutante}
{1181}{}{Um rato porco bem forte.}
{1190}{}{Super Mutante}
{1200}{}{Mutante}
{1210}{}{Super Mutante}
{1220}{}{Hero Andro (don't use)}
{1230}{}{Hero Andro (don't use)}
{1240}{}{Hero Male (don't use)}
{1250}{}{Hero Female (don't use)}
{1260}{}{Hero Male (don't use)}
{1270}{}{Hero Female (don't use)}
{1280}{}{Hero Male (don't use)}
{1290}{}{Hero Female (don't use)}
{1300}{}{Hero Male (don't use)}
{1310}{}{Hero Female (don't use)}
{1320}{}{Hero Male (don't use)}
{1330}{}{Hero Female (don't use)}
{1340}{}{Guarda da Cidade do Abrigo}
{1350}{}{Guarda da Cidade do Abrigo}
{1360}{}{Cyberdog}
{1370}{}{Guarda da RNC}
{1380}{}{Guarda da RNC}
{1390}{}{Guarda de luta da RNC}
{1400}{}{Guarda dos Traficante de escravos}
{1410}{}{Chefe dos Traficante de escravos}
{1420}{}{Mercador Grão-Mestre}
{1430}{}{Mercadora Grã-Mestra}
{1440}{}{Tandi}
{1450}{}{Merc}
{1460}{}{Ratch}
{1470}{}{Skeeter}
{1480}{}{Mikey}
{1490}{}{Atendente de bar da RNC}
{1500}{}{Dono da loja}
{1510}{}{Gruthar}
{1520}{}{Goris}
{1530}{}{Ratoupeira lutador}
{1540}{}{Ratoupeira lutador}
{1550}{}{Ratoupeira lutador}
{1560}{}{Ratoupeira lutador}
{1570}{}{Ratoupeira lutador}
{1580}{}{Ratoupeira lutador}
{1590}{}{Carniçal comum}
{1600}{}{Myron}
{1610}{}{Marcus}
{1620}{}{Doc Jones}
{1630}{}{Davin}
{1640}{}{Miria}
{1650}{}{Guri}
{1660}{}{Rondo}
{1670}{}{Trabalhador do Rancho}
{1680}{}{Trabalhador do Rancho}
{1690}{}{Trabalhador do Rancho}
{1700}{}{Capataz}
{1710}{}{Capataz}
{1720}{}{Mr. Handy fraco}
{1730}{}{Luminescente genérico}
{1740}{}{Dar}
{1750}{}{Dalia}
{1760}{}{Gordon}
{1770}{}{test (don't use)}
{1780}{}{Carniçal do reator}
{1790}{}{Carniçal qualquer}
{1800}{}{Matt}
{1810}{}{Líder caçador de recompensas}
{1820}{}{Caçador de recompensas}
{1830}{}{Líder caçador de recompensas}
{1840}{}{Caçador de recompensas}
{1850}{}{Caçador de recompensas}
{1860}{}{Líder caçador de recompensas}
{1870}{}{Caçador de recompensas}
{1880}{}{Caçador de recompensas}
{1890}{}{Líder caçador de recompensas}
{1900}{}{Caçador de recompensas}
{1910}{}{Bess}
{1911}{}{Uma vaca mutante de duas cabeças.}
{1920}{}{Baltazar}
{1930}{}{Grisham}
{1940}{}{Phil}
{1950}{}{Frango}
{1960}{}{Karl}
{1970}{}{Jonny}
{1980}{}{Jo}
{1990}{}{Zeke}
{2000}{}{Açougueiro}
{2010}{}{Petey}
{2020}{}{Caçador primitivo}
{2030}{}{Caçador primitivo}
{2040}{}{Canibal}
{2050}{}{Canibal}
{2060}{}{Santo}
{2070}{}{Santa}
{2080}{}{Nômade- Baixo}
{2090}{}{Nômade- Médio}
{2100}{}{Nômade- Baixo}
{2110}{}{Nômade- Médio}
{2120}{}{Bandido}
{2130}{}{Bandido}
{2140}{}{Fazendeiro}
{2150}{}{Fazendeiro}
{2160}{}{Mantis}
{2170}{}{Traficante de escravos}
{2180}{}{Traficante de escravos}
{2190}{}{Brahmin selvagem}
{2200}{}{Fazendeiro}
{2210}{}{Fazendeiro}
{2220}{}{Patrulha da Cidade do Abrigo}
{2230}{}{Patrulha da Cidade do Abrigo}
{2240}{}{Traficante de escravos fortão}
{2250}{}{Traficante de escravos fortona}
{2260}{}{Doidões}
{2270}{}{Catador de lixos}
{2280}{}{Doidos do Clarão}
{2290}{}{Catador de lixo do Clarão}
{2300}{}{Pescador}
{2310}{}{Pescadora}
{2320}{}{Wilder}
{2330}{}{Wilder}
{2340}{}{Contrabandista}
{2350}{}{Contrabandista}
{2360}{}{Minerador}
{2370}{}{Minerador}
{2380}{}{Ladrão de estrada}
{2390}{}{Ladra de estrada}
{2400}{}{Kalango-de-fogo}
{2410}{}{Kalango-de-fogo forte}
{2420}{}{Wanamingo}
{2430}{}{Wanamingo reistente}
{2440}{}{Iucapiã}
{2450}{}{Iucapiã forte}
{2460}{}{Caravela}
{2470}{}{Caravela Nojenta}
{2480}{}{Centauro}
{2490}{}{Centauro agressivo}
{2500}{}{Patrulha da Enclave}
{2510}{}{Patrulha da Enclave}
{2520}{}{Gangue da Imprensa}
{2530}{}{Gangue da Imprensa}
{2540}{}{Mercenário}
{2550}{}{Mercenária}
{2560}{}{Noturno}
{2570}{}{Noturno forte}
{2580}{}{Carniçal forte}
{2590}{}{Mobster}
{2600}{}{Yakuza}
{2610}{}{Patrulheiro da RNC}
{2620}{}{Patrulheiro da RNC}
{2630}{}{Assaltante de estrada}
{2640}{}{Assaltante de estrada}
{2650}{}{Pretty Boy Lloyd}
{2660}{}{Rato Vorpal}
{2670}{}{Homem do Abrigo 13}
{2680}{}{Mulher do Abrigo 13}
{2690}{}{Guardião da Ponte}
{2700}{}{Estranho misterioso}
{2710}{}{Estranha misteriosa}
{2720}{}{Hakeswill}
{2730}{}{Jesus Mordino Pai}
{2740}{}{Dumar}
{2741}{}{Dumar, o mercador de brahmin.}
{2750}{}{Matriarca Iucapiã}
{2760}{}{O Dragão}
{2770}{}{Lo Pan}
{2780}{}{Centrologista}
{2790}{}{Centrologista}
{2800}{}{Estranho misterioso}
{2810}{}{Estranho misterioso}
{2820}{}{Estranho misterioso}
{2830}{}{Estranho misterioso}
{2840}{}{Estranho misterioso}
{2850}{}{Estranho misterioso}
{2860}{}{Estranho misterioso}
{2870}{}{Estranho misterioso}
{2880}{}{Guarda-costas Presidencial}
{2890}{}{Ovo de Iucapiã}
{2900}{}{Metzger}
{2910}{}{Guarda da Enclave}
{2920}{}{Guarda da Enclave}
{2930}{}{Presidente}
{2940}{}{Vice Presidente}
{2950}{}{Técnico}
{2960}{}{Badger}
{2970}{}{Dr. Fung}
{2980}{}{Criança}
{2990}{}{Criança}
{3000}{}{Mercador de armas}
{3010}{}{Téc. em Laboratório Shi}
{3020}{}{Guarda Shi}
{3030}{}{Camponês Shi}
{3040}{}{Camponêsa Shi}
{3050}{}{Camponês Lo Pan }
{3060}{}{Camponêsa Lo Pan}
{3070}{}{Estivador}
{3080}{}{Shi Merchant}
{3090}{}{Rêei Ra'tu}
{3100}{}{Sulik - Fase 1}
{3110}{}{Sulik - Fase 2}
{3120}{}{Sulik - Fase 3}
{3130}{}{Sulik - Fase 4}
{3140}{}{Sulik - Fase 5}
{3150}{}{Sulik - Fase 6}
{3160}{}{Lenny - Fase 1}
{3170}{}{Lenny - Fase 2}
{3180}{}{Lenny - Fase 3}
{3190}{}{Goris - Fase 1}
{3200}{}{Goris - Fase 2}
{3210}{}{Goris - Fase 3}
{3220}{}{Goris - Fase 4}
{3230}{}{Goris - Fase 5}
{3240}{}{Goris - Fase 6}
{3250}{}{Myron - Fase 1}
{3260}{}{Myron - Fase 2}
{3270}{}{Myron - Fase 3}
{3280}{}{Myron - Fase 4}
{3290}{}{Marcus - Fase 1}
{3300}{}{Marcus - Fase 2}
{3310}{}{Marcus - Fase 3}
{3320}{}{Marcus - Fase 4}
{3330}{}{Marcus - Fase 5}
{3340}{}{Cyberdog - Fase 1}
{3350}{}{Cyberdog - Fase 2}
{3360}{}{Cyberdog - Fase 3}
{3370}{}{Cyberdog - Fase 4}
{3380}{}{Cassidy - Fase 1}
{3390}{}{Cassidy - Fase 2}
{3400}{}{Cassidy - Fase 3}
{3410}{}{Cassidy - Fase 4}
{3420}{}{Dogmeat}
{3430}{}{Dogmeat - Fase 1}
{3440}{}{Dogmeat - Fase 2}
{3450}{}{Dogmeat - Fase 3}
{3460}{}{Dogmeat - Fase 4}
{3470}{}{Dogmeat - Fase 5}
{3480}{}{Dogmeat - Fase 6}
{3490}{}{Robôneural - Fase 1}
{3500}{}{Robôneural - Fase 2}
{3510}{}{Robôneural - Fase 3}
{3520}{}{Robôneural - Fase 4}
{3530}{}{Robôneural - Fase 5}
{3540}{}{Rainha Wanamingo}
{3550}{}{Radscorpião negro}
{3560}{}{Radscorpião negro}
{3570}{}{Spud}
{3580}{}{Capitão Mercenário}
{3590}{}{Mercenário}
{3600}{}{Mercenário}
{3610}{}{Sombra-Que-Andas}
{3620}{}{Punk}
{3630}{}{Punk}
{3640}{}{Marc}
{3650}{}{Dave H.}
{3660}{}{Capt. A. Ron Meyers}
{3670}{}{Chip}
{3680}{}{AHS-9}
{3690}{}{Guarda Centrologista}
{3700}{}{Guarda Centrologista}
{3710}{}{Juan}
{3720}{}{Vikki}
{3730}{}{Vic}
{3740}{}{Vic}
{3750}{}{Vic}
{3760}{}{Vic}
{3770}{}{Vic}
{3780}{}{Vic}
{3790}{}{Robôneural - Chimp}
{3800}{}{Robôneural - Anormal}
{3810}{}{Robôneural - Humano}
{3820}{}{Formiga gigante}
{3830}{}{Formiga gigante forte}
{3840}{}{Cão Párias}
{3850}{}{Zurak}
{3860}{}{Imbot}
{3870}{}{Jimmy}
{3880}{}{Wejungh}
{3890}{}{Herb}
{3900}{}{Loopal}
{3910}{}{Jobe}
{3920}{}{Smitty}
{3930}{}{Rube}
{3940}{}{Mestre Krall}
{3950}{}{Ziggy}
{3960}{}{Mestre Khung}
{3970}{}{John Bishop}
{3980}{}{Angela Bishop}
{3990}{}{Sra. Bishop}
{4000}{}{Guarda do Bishop}
{4010}{}{Guarda do Bishop}
{4020}{}{Capanga do Bishop}
{4030}{}{Capanga do Bishop}
{4040}{}{Brahmin-louca}
{4050}{}{Jesus Filho}
{4060}{}{Jesus Pai}
{4070}{}{Capanga do Mordino}
{4080}{}{Capanga do Mordino}
{4090}{}{Capanga do Mordino}
{4100}{}{Guarda do Myron}
{4110}{}{Guarda do Myron}
{4120}{}{Sr. Wright}
{4130}{}{Sra. Wright}
{4140}{}{Chris Wright}
{4150}{}{Keith Wright}
{4160}{}{Filho de Wright}
{4170}{}{Filho de Wright}
{4180}{}{Filha de Wright}
{4190}{}{Filha de Wright}
{4200}{}{Sr. Salvatore}
{4210}{}{Mason}
{4220}{}{Capanga do Salvatore}
{4230}{}{Capanga do Salvatore}
{4240}{}{Atendente do bar}
{4250}{}{Atendente do bar}
{4260}{}{Atendente do bar}
{4270}{}{Boxeador}
{4280}{}{Boxeador}
{4290}{}{Boxeador}
{4300}{}{Boxeador}
{4310}{}{Mike o Mastigador}
{4320}{}{Holyfeld}
{4330}{}{McKneely}
{4340}{}{Pequeno Stuart}
{4350}{}{Irmãos Corsican}
{4360}{}{Vadias Corsican}
{4370}{}{Padre Tully}
{4380}{}{Guarda do Casino}
{4390}{}{Guarda do Casino}
{4400}{}{Funcionária do Casino}
{4410}{}{Traficante de Drogas}
{4420}{}{Traficante de Drogas}
{4430}{}{Traficante de Drogas}
{4440}{}{Traficante de Drogas}
{4450}{}{McGee}
{4460}{}{Miss Kitty}
{4470}{}{Slut}
{4480}{}{Slut}
{4490}{}{Jagged Jimmy J}
{4500}{}{Renesco}
{4510}{}{Cientista}
{4520}{}{Eldridge}
{4530}{}{Barbosa}
{4540}{}{Júlio}
{4550}{}{Político}
{4560}{}{Político}
{4570}{}{Mercador}
{4580}{}{Mercador}
{4590}{}{Guarda}
{4600}{}{Guarda}
{4610}{}{Guarda}
{4620}{}{Guarda}
{4630}{}{Soldado}
{4640}{}{Soldado}
{4650}{}{Soldado}
{4660}{}{Soldado}
{4670}{}{Sgt. Stark}
{4680}{}{"Doc" Andrew}
{4690}{}{Atendente}
{4700}{}{Torre armada}
{4701}{}{Esta é uma torre armada com dois canhões plasma.}
{4710}{}{Cão selvagem}
{4720}{}{Cão selvagem}
{4730}{}{Cão selvagem}
{4740}{}{Cão selvagem}
{4750}{}{Coiote}
{4760}{}{Cão selvagem}
{4770}{}{Ovo de Wanamingo}
{4780}{}{Guarda de Lo Pan}
{4790}{}{Marjorie}
{4800}{}{Canhão automatizado}
{4810}{}{Kalango especial}
{4820}{}{Estripador Sinistro}
{4830}{}{Frank Horrigan}
{4831}{}{O guarda-costas do Presidente}
{4840}{}{Lobo}
{4850}{}{Cão doente}
{4860}{}{Coiote}
{4870}{}{Radscorpião mutante}
{4880}{}{Kalango-dourado pequeno}
{4890}{}{Rebelde}
{4900}{}{Inseto assassino}
{4910}{}{Engenheiro}
{4920}{}{Infrantaria Enclave}
{4930}{}{Engenheiro}
{4940}{}{Novato da Irmandade}
{4950}{}{Soldado de Operações Especiais}
{4960}{}{Soldado da Enclave}
{4970}{}{Paladino da Irmandade}
{4980}{}{Regulador}
{4990}{}{Bandido}
{5000}{}{Bandida}
{5010}{}{Ladrão de estrada}
{5020}{}{Ladra de estrada}
{5030}{}{Ladrão de estrada}
{5040}{}{Ladra de estrada}
{5050}{}{Vespa gigante}
{5051}{}{Огромное кровожадное насекомое}
{5060}{}{Гвардеец}
{5061}{}{Боец Гвардии ГУ}
{5070}{}{Morcego gigante}
{5080}{}{Patrulha de Arroyo}
{5090}{}{Patrulha de Arroyo}
{5100}{}{Patrulha de Arroyo}
{5110}{}{Fugitivo}
{5120}{}{Fugitivo}
{5130}{}{Fugitivo}
{5140}{}{Fugitivo}
{5150}{}{Fugitivo}
{5160}{}{Eli}
{5170}{}{Champion}
{5180}{}{Helacyton type  1}
{5181}{}{A strange creature resembling Master's pets.}
{5190}{}{Angry helacyton type  1}
{5191}{}{A strange creature resembling Master's pets.}
{5200}{}{Helacyton type  2}
{5201}{}{A strange creature resembling Master's pets.}
{5210}{}{Angry helacyton type  2}
{5211}{}{A strange creature resembling Master's pets.}
{5220}{}{Helacyton type  3}
{5221}{}{A strange creature resembling Master's pets.}
{5230}{}{Henrietta}
{5231}{}{Skin of this animal looks like one big callus.}
{5240}{}{Andróide}
{5250}{}{Tim Cain}
{5260}{}{Carlos}
{5270}{}{Carlos}
{5280}{}{Behemoth}
{5281}{}{Огромный механический жук на шести лапах, оснащен крупнокалиберным пулеметом.}
{5300}{}{Guarda do Sucatão}
{5301}{}{Um guarda esperto que sabe como usar sua arma.}
{5310}{}{Guarda do Sucatão}
{5311}{}{Uma guarda esperto que sabe como usar sua arma.}
{5320}{}{Rui}
{5321}{}{Rui, o carcereiro local.}
{5330}{}{Guarda}
{5331}{}{Guarda do Matador.}
{5340}{}{O Matador}
{5341}{}{O Matador.}
{5350}{}{Guarda do Sucatão}
{5351}{}{Um guarda esperto que sabe como usar sua arma.}
{5360}{}{Policial do Ponto Central}
{5361}{}{Policial do Ponto Central, que está de olho na área.}
{5370}{}{Policial do Ponto Central}
{5371}{}{Policial do Ponto Central, que está de olho na área.}
{5380}{}{Noturno}
{5381}{}{Super Mutante forte e agressivo.}
{5390}{}{Noturno}
{5391}{}{Super Mutante forte. Ele parece usar algo para fazer difícil de vê-lo.}
{5400}{}{Mutante}
{5401}{}{Super Mutante. Ele parece bem agressivo.}
{5410}{}{Posseiro}
{5420}{}{Posseiro}
{5430}{}{Posseiro}
{5440}{}{Posseiro}
{5450}{}{Posseiro}
{5460}{}{Chuck Lee}
{5461}{}{Chuck Lee, o líder da caravana.}
{5470}{}{Manequin}
{5480}{}{Manequin}
{5490}{}{Manequin}
{5500}{}{Manequin}
{5510}{}{Manequin}
{5520}{}{Manequin}
{5530}{}{Manequin}
{5540}{}{Manequin}
{5550}{}{Manequin}
{5560}{}{Manequin}
{5570}{}{Manequin}
{5580}{}{Manequin}
{5590}{}{Manequin}
{5600}{}{Manequin}
{5610}{}{Manequin}
{5620}{}{Manequin}
{5630}{}{Manequin}
{5640}{}{Manequin}
{5650}{}{Manequin}
{5660}{}{Manequin}
{5670}{}{Manequin}
{5680}{}{Manequin}
{5690}{}{Manequin}
{5700}{}{Manequin}
{5710}{}{Manequin}
{5720}{}{Manequin}
{5730}{}{Manequin}
{5740}{}{Manequin}
{5750}{}{Manequin}
{5760}{}{Manequin}
{5770}{}{Manequin}
{5780}{}{Manequin}
{5790}{}{Manequin}
{5800}{}{Manequin}
{5810}{}{Manequin}
{5820}{}{Manequin}
{5830}{}{Manequin}
{5840}{}{Manequin}
{5850}{}{Manequin}
{5860}{}{Manequin}
{5870}{}{Manequin}
{5880}{}{Manequin}
{5890}{}{Manequin}
{5900}{}{Manequin}
{5910}{}{Manequin}
{5920}{}{Manequin}
{5930}{}{Manequin}
{5940}{}{Manequin}
{5950}{}{Manequin}
{5960}{}{Manequin}
{5970}{}{Manequin}
{5980}{}{Manequin}
{5990}{}{Manequin}
{6000}{}{Manequin}
{6010}{}{Guarda forte do Sucatão}
{6011}{}{Um guarda que parece forte. Está atento a tudo o que acontece ao seu redor.}
{6030}{}{Guarda forte do Sucatão}
{6031}{}{Um guarda que parece forte. Está atento a tudo o que acontece ao seu redor.}
{6040}{}{Guarda forte do Sucatão}
{6041}{}{Um guarda que parece forte. Está atento a tudo o que acontece ao seu redor.}
{6050}{}{Trader KLAMATH}
{6060}{}{Trader DEN}
{6070}{}{Trader REDDING}
{6080}{}{Trader MODOC}
{6090}{}{Trader GECKO}
{6100}{}{Trader VC OUT}
{6110}{}{Trader VC IN}
{6120}{}{Trader BROKEN HILLS}
{6130}{}{Trader NEW RENO}
{6140}{}{Trader SAN FRANCISCO}
{6150}{}{Trader NCR OUT}
{6160}{}{Trader NCR IN}
{6170}{}{Trader HUB}
{6180}{}{Trader BONEYARD}
{6190}{}{Doctor VC IN}
{6200}{}{Doctor VC OUT}
{6210}{}{Doctor NCR}
{6220}{}{Doctor HUB}
{6230}{}{Doctor BONEYARD}
{6240}{}{Doctor SANFRANCISCO}
{6250}{}{Doctor NEW RENO}
{6260}{}{Doctor BROKEN HILLS}
{6270}{}{Doctor REDDING}
{6280}{}{BAR SF}
{6290}{}{BAR BH}
{6300}{}{BAR BHWIFE}
{6310}{}{BAR SALVNR}
{6320}{}{BAR CASINONR}
{6330}{}{BAR GECKO}
{6340}{}{BAR VC}
{6350}{}{BAR MODOC}
{6360}{}{BAR WIFEKLAMATH}
{6370}{}{BAR DUDEKLAMATH}
{6380}{}{BAR CASINODEN}
{6390}{}{BAR DEN}
{6400}{}{BAR MOMDEN}
{6410}{}{BAR HUB}
{6420}{}{BAR JT}
{6430}{}{BAR MALAMUTREDDING}
{6440}{}{BAR COFFINREDDING}
{6450}{}{BAR NCROUT}
{6460}{}{BAR NCRIN}
{6470}{}{SFTANK GUNS}
{6480}{}{SFTANK ARMOR}
{6490}{}{BALDCHINA}
{6500}{}{BH CARAVANDUDE}
{6510}{}{BH HUSBAND}
{6520}{}{NEWR ARMS}
{6530}{}{GECKO SKEET}
{6540}{}{GECKO SHERIFF}
{6550}{}{VC A ARMOR}
{6560}{}{VC B WEAPON}
{6570}{}{MODOC TANNER}
{6580}{}{MODOC WILLY}
{6590}{}{DEN SECOND}
{6600}{}{HUB JACOB}
{6610}{}{HUB GUNS}
{6620}{}{BONE GUNRUNNERS}
{6630}{}{Matriarca Iucapiã}
{6631}{}{Puta que pariu, melhor sair correndo!}
{6640}{}{Iucapiã}
{7000}{}{Posseiro}
{7010}{}{Bandido}
{7020}{}{Bandido}
{7030}{}{Bandido}
{7040}{}{Bandido}
{7050}{}{Bandido}
{7060}{}{Bandido}
{7070}{}{Assaltante}
{7080}{}{Assaltante}
{7090}{}{Assaltante}
{7100}{}{Assaltante}
{7110}{}{Assaltante}
{7120}{}{Assaltante}
{7130}{}{Contrabandista}
{7140}{}{Contrabandista}
{7150}{}{Contrabandista}
{7160}{}{Contrabandista}
{7170}{}{Brutamonte}
{7180}{}{Brutamonte}
{7190}{}{Brutamonte}
{7200}{}{Brutamonte}
{7210}{}{Brutamonte}
{7220}{}{Brutamonte}
{7230}{}{Drogado}
{7240}{}{Drogado}
{7250}{}{Drogado}
{7260}{}{Drogado}
{7270}{}{Drogado}
{7280}{}{Drogado}
{7290}{}{Assaltante de estrada}
{7300}{}{Assaltante de estrada}
{7310}{}{Assaltante de estrada}
{7320}{}{Assaltante de estrada}
{7330}{}{Assaltante de estrada}
{7340}{}{Assaltante de estrada}
{7350}{}{Ladrão de estrada}
{7360}{}{Ladrão de estrada}
{7370}{}{Ladrão de estrada}
{7380}{}{Ladrão de estrada}
{7390}{}{Ladrão de estrada}
{7400}{}{Ladrão de estrada}
{7410}{}{Carniçal}
{7420}{}{Carniçal}
{7430}{}{Carniçal}
{7440}{}{Carniçal}
{7450}{}{Carniçal}
{7460}{}{Punker}
{7470}{}{Punker}
{7480}{}{Punker}
{7490}{}{Punker}
{7500}{}{Punker}
{7510}{}{Estripador}
{7520}{}{Estripador}
{7530}{}{Estripador}
{7540}{}{Estripador}
{7550}{}{Estripador}
{7560}{}{Ladrão de estrada}
{7570}{}{Ladrão de estrada}
{7580}{}{Ladrão de estrada}
{7590}{}{Ladrão de estrada}
{7600}{}{Ladrão de estrada}
{7610}{}{Cara armado}
{7620}{}{Puta louca}
{7630}{}{Fodão}
{7640}{}{Goon}
{7650}{}{Gângster}
{7660}{}{Ladrão de viagem}
{7670}{}{Ladrão de viagem}
{7680}{}{Ladrão de viagem}
{7690}{}{Ladrão de viagem}
{7700}{}{Ladrão de viagem}
{7710}{}{ALOKA}
{7720}{}{Doido}
{7730}{}{Cara louco}
{7740}{}{Saco de merda}
{7750}{}{Verme}
{7760}{}{Mercenário}
{7770}{}{Mercenário}
{7780}{}{Mercenário}
{7790}{}{Mercenário}
{7800}{}{Mercenário}
{7810}{}{Carniçal}
{7820}{}{Regulador}
{7830}{}{Regulador}
{7840}{}{Regulador}
{7850}{}{Regulador}
{7860}{}{Ladrão de estrada Khan}
{7870}{}{Ladrão de estrada Khan}
{7880}{}{Ladrão de estrada Khan}
{7890}{}{Ladrão de estrada Khan}
{7900}{}{Ladrão de estrada Khan}
{7910}{}{Ladrão}
{7920}{}{Ladrão}
{7930}{}{Ladrão}
{7940}{}{Ladrão}
{7950}{}{Ladrão}
{7960}{}{Recruta da Enclave}
{7970}{}{Soldado da Enclave}
{7980}{}{Soldado da Enclave}
{7990}{}{Soldado veterano da Enclave}
{8000}{}{Soldado veterano da Enclave}
{8010}{}{Mutante}
{8020}{}{Super Mutante}
{8030}{}{Super Mutante}
{8040}{}{Noturno}
{8050}{}{Noturno}
{8060}{}{Carniçal}
{8070}{}{Carniçal}
{8080}{}{Carniçal}
{8090}{}{Carniçal}
{8100}{}{Carniçal}
{8110}{}{Carniçal}
{8120}{}{Carniçal}
{8130}{}{Carniçal}
{8140}{}{Carniçal}
{8150}{}{Carniçal}
{8160}{}{Carniçal}
{8170}{}{Recruta da Enclave}
{8180}{}{Soldado da Enclave}
{8190}{}{Soldado da Enclave}
{8200}{}{Soldado veterano da Enclave}
{8210}{}{Novato da Irmandade}
{8220}{}{Cavaleiro da Irmandade}
{8230}{}{Cavaleiro da Irmandade}
{8240}{}{Paladino da Irmandade}
{8250}{}{Abominação}
{8260}{}{Monstruosidade}
{8270}{}{Rato de caverna}
{8280}{}{Porco-rato mutante}
{8290}{}{Ratoupeira mutante}
{8300}{}{Carniceiro}
{8301}{}{Furioso e esperto... qualquer tentativa de conversar é em vão.}
{8310}{}{Robôneural}
{8320}{}{Vigia}
{8330}{}{Guarda Carniçal}
{8340}{}{Zed}
{8350}{}{Ladrão de estrada Khan}
{8360}{}{Ladrão de estrada Khan}
{8370}{}{Ladrão de estrada Khan}
{8380}{}{Ladrão de estrada Khan}
{8390}{}{Ladrão de estrada Khan}
{8400}{}{Escolta do Sucatão}
{8410}{}{Escolta do Sucatão}
{8420}{}{Escolta do Sucatão}
{8430}{}{Escolta do Sucatão}
{8440}{}{Escolta do Sucatão}
{8450}{}{Escolta do mercador}
{8460}{}{Escolta do mercador}
{8470}{}{Escolta do mercador}
{8480}{}{Escolta do mercador}
{8490}{}{Mercador}
{8500}{}{Bandido}
{8510}{}{Bandido}
{8520}{}{Bandido}
{8530}{}{Bandido}
{8540}{}{Bandido}
{8550}{}{Bandido}
{8560}{}{Assaltante}
{8570}{}{Assaltante}
{8580}{}{Assaltante}
{8590}{}{Assaltante}
{8600}{}{Assaltante}
{8610}{}{Assaltante}
{8620}{}{Líder da caravana}
{8630}{}{Guarda da caravana}
{8640}{}{Guarda da caravana}
{8650}{}{Guarda da caravana}
{8660}{}{Guarda da caravana}
{8670}{}{Guarda da caravana}
{8680}{}{Guarda da caravana}
{8690}{}{Guarda da caravana}
{8700}{}{Guarda da caravana}
{8710}{}{Novato da Irmandade}
{8720}{}{Cavaleiro da Irmandade}
{8730}{}{Cavaleiro da Irmandade}
{8740}{}{Paladino da Irmandade}
{8750}{}{Paladino da Irmandade}
{8760}{}{Guarda do Ponto Central}
{8770}{}{Guarda do Ponto Central}
{8780}{}{Guarda do Ponto Central}
{8790}{}{Guarda do Ponto Central}
{8800}{}{Guarda do Ponto Central}
{8810}{}{Guarda da Cidade do Abrigo}
{8820}{}{Guarda da Cidade do Abrigo}
{8830}{}{Guarda da Cidade do Abrigo}
{8840}{}{Guarda da Cidade do Abrigo}
{8850}{}{Guarda da Cidade do Abrigo}
{8860}{}{Carniçal}
{8870}{}{Carniçal}
{8880}{}{Carniçal}
{8890}{}{Carniçal}
{8900}{}{Carniçal}
{8910}{}{Lâmina}
{8920}{}{Lâmina}
{8930}{}{Lâmina}
{8940}{}{Lâmina}
{8950}{}{Lâmina}
{8960}{}{Patrulha da Unidade}
{8970}{}{Patrulha da Unidade}
{8980}{}{Patrulha da Unidade}
{8990}{}{Patrulheiro da RNC}
{9000}{}{Patrulheiro da RNC}
{9010}{}{Patrulheiro da RNC}
{9020}{}{Soldado da RNC}
{9030}{}{Cabo da RNC}
{9040}{}{Líder da caravana}
{9050}{}{Guarda da caravana}
{9060}{}{Guarda da caravana}
{9070}{}{Guarda da caravana}
{9080}{}{Guarda da caravana}
{9090}{}{Guarda da caravana}
{9100}{}{Guarda da caravana}
{9110}{}{Guarda da caravana}
{9120}{}{Guarda da caravana}
{9130}{}{Fazendeiro}
{9140}{}{Fazendeiro}
{9150}{}{Fazendeiro}
{9160}{}{Fazendeiro}
{9170}{}{Criança}
{9180}{}{Camponês}
{9190}{}{Camponês}
{9200}{}{Camponês}
{9210}{}{Camponês}
{9220}{}{Criança}
{9230}{}{Camponês}
{9240}{}{Catador de lixo}
{9250}{}{Catador de lixo}
{9260}{}{Catador de lixo}
{9270}{}{Catador de lixo}
{9280}{}{Catador de lixo}
{9290}{}{Hobo}
{9300}{}{Hobo}
{9310}{}{Hobo}
{9320}{}{Hobo}
{9330}{}{Caçador}
{9340}{}{Caçador}
{9350}{}{Caçador}
{9360}{}{Caçador}
{9370}{}{Caçador}
{9380}{}{Caçador}
{9390}{}{Minerador}
{9400}{}{Minerador}
{9410}{}{Minerador}
{9420}{}{Fazendeiro}
{9430}{}{Fazendeiro}
{9440}{}{Fazendeiro}
{9450}{}{Fazendeiro}
{9460}{}{Centrologista}
{9470}{}{Centrologista}
{9480}{}{Centrologista}
{9490}{}{Centrologista}
{9500}{}{Centrologista}
{9510}{}{Chupacabra}
{9511}{}{Melhor correr!}
{9520}{}{Aberração}
{9530}{}{Líder do bando}
{9540}{}{Vayne}
{9550}{}{Escolta do Sucatão}
{9560}{}{Escolta do Sucatão}
{9570}{}{Escolta do Sucatão}
{9580}{}{Escolta do Sucatão}
{9590}{}{Escolta do Sucatão}
{9600}{}{Noturno}
{9610}{}{Homem suspeito sob uma túnica}
{9620}{}{Capanga do Bispo}
{9630}{}{Capanga do Bispo}
{9640}{}{Capanga do Bispo}
{9650}{}{Capanga do Bispo}
{9660}{}{Filho do Wright}
{9670}{}{Filho do Wright}
{9680}{}{Filho do Wright}
{9690}{}{Filho do Wright}
{9700}{}{Comandante}
{9710}{}{26}
{9720}{}{31}
{9730}{}{40}
{9740}{}{41}
{9750}{}{43}
{9760}{}{44}
{9770}{}{45}
{9780}{}{48}
{9790}{}{56}
{9800}{}{57}
{9810}{}{62}
{9820}{}{64}
{9830}{}{72}
{9840}{}{77}
{9850}{}{78}
{9860}{}{82}
{9870}{}{87}
{9880}{}{88}
{9890}{}{Químico}
{9900}{}{91}
{9910}{}{92}
{9920}{}{93}
{9930}{}{95}
{9940}{}{96}
{9950}{}{98}
{9960}{}{105}
{9970}{}{110}
{9980}{}{135}
{9990}{}{136}
{10000}{}{137}
{10010}{}{139}
{10020}{}{140}
{10030}{}{33}
{10040}{}{34}
{10050}{}{35}
{10060}{}{36}
{10070}{}{37}
{10080}{}{61}
{10090}{}{73}
{10100}{}{94}
{10110}{}{145}
{10120}{}{146}
{10130}{}{148}
{10140}{}{149}
{10150}{}{Catador de Mobília}
{10160}{}{Kalango-tóxico}
{10170}{}{Kalango-tóxico adulto}
{10180}{}{Pequeno kalango radioativo}
{10190}{}{Kalango radioativo}
{10200}{}{Kalango radioativo forte}
{10210}{}{Pesadelo}
{10220}{}{Soldado-do-diabo}
{10230}{}{Líder da caravana}
{10240}{}{Habitante do Abrigo}
{10250}{}{Líder tribal}
{14000}{}{Ovo de radscorpião}
{14010}{}{Ovo de formiga}
{14020}{}{Ovo de kalango}
{14030}{}{Ovo de Iucapiã}
{14040}{}{Ovo de Wanamigo}
{14050}{}{Ovo de Centauro}
